### ISSUE TITLE
SEO: deindex reliam servers

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#1]
Reliam servers are getting indexed by google. We need to remove the pages in the search results below from Google's index. 

https://www.google.com/search?q=site%3A+reliam.com+marketplace.akc.org&oq=site%3A+reliam.com+marketplace.akc.org&aqs=chrome..69i57j69i58.7376j0j1&sourceid=chrome&es_sm=93&ie=UTF-8#q=site:http://akc-prod-web01.reliam.com&start=50

**Comment by kylejbertelsen** [comment]
@spaulenoff: still valid? I've done some exact-phrase searches against some of the text on the example link, and reliam URLs are not returned.

**Comment by spaulenoff** [comment]
Moved to Jira
