### ISSUE TITLE
Individual content pages: Change up breadcrumb Structure

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#100]
and Individual content pages such as:
http://develop2.akc.org/content/westminster-dog-show/articles/cinderella-story-behind-1980-westminster
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-4
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-2

Update the breadcrumb structure as follows: AKC>[Category]>[Sub-Category]
- AKC should link to akc.org,  
- [category] to /content/[category], 
- [sub-category] to /content/[category]/[sub-category],

**Comment by spaulenoff** [comment]
@toshan2014 Breadcrumbs look good but the URL Structure should not have changed for content pieces For Example:
http://develop2.akc.org/content/westminster-dog-show/live-coverage/articles/westminster-group-results-day-2/
http://develop2.akc.org/content/westminster-dog-show/live-coverage/videos/westminster-test-video/
http://develop2.akc.org/content/westminster-dog-show/live-coverage/photo-galleries/westminster-test-gallery-3/?photo_id=0

**Comment by toshan2014** [comment]
@spaulenoff URL structure for display of subcats has been modified - please confirm

**Comment by spaulenoff** [comment]
@toshan2014 Breadcrumbs are looking good, however the following URLs are 404ing from the sub cat page:
http://develop2.akc.org/content/westminster-dog-show/live-coverage/articles/westminster-group-results-day-2/
http://develop2.akc.org/content/westminster-dog-show/live-coverage/articles/masters-agility-and-obedience-results/
http://develop2.akc.org/content/westminster-dog-show/live-coverage/articles/what-it-means-to-show-at-westminster/
http://develop2.akc.org/content/westminster-dog-show/live-coverage/articles/the-future-of-canine-sport-junior-handlers/

The videos and photo galleries are working correctly and also this Article: http://develop2.akc.org/content/westminster-dog-show/live-coverage/articles/westminster-group-results-day-1/

**Comment by toshan2014** [comment]
@spaulenoff The 404 were due to wrong cats being show on the subcat page. Please check again

**Comment by spaulenoff** [comment]
@stevepessah I have checked it out on dev 2:
**With Sub Cat**
http://develop2.akc.org/content/westminster-dog-show/articles/what-it-means-to-show-at-westminster/
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video/
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=0

**Without SubCat**
http://develop2.akc.org/content/westminster-dog-show/articles/the-voice-of-westminster-reflects-on-27-years-in-the-ring/
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/

**Comment by stevepessah** [comment]
@spaulenoff only issue I see is the extra carrot at the end of the breadcrumb on this page - http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/

**Comment by spaulenoff** [comment]
@toshan2014 Please fix per steve's comment

**Comment by toshan2014** [comment]
@spaulenoff please check

**Comment by spaulenoff** [comment]
@stevepessah Breadcrumbs look good to me: 
https://develop2.akc.org/content/westminster-dog-show/articles/author-fb-test-article/
https://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-2/
https://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by toshan2014** [comment]
@spaulenoff 
Added fix for "Need ability to add “noindex” and add keywords (AKC vocabulary) #101" in breadcrumb. Please double check.

https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

http://stage-ng.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/

**Comment by spaulenoff** [comment]
Verified on Dev and Stage

**Comment by toshan2014** [comment]
pf

Photos Gallery: 
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-2/?photo_id=0

Video:
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-2/

Article:
https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Comment by spaulenoff** [comment]
@toshan2014 Verified on Prod. Please add comment regarding time tracking for this ticket

**Comment by toshan2014** [comment]
Spent around: 7h ( cat structure was modified mid progress hence affecting initial estimate )
