### ISSUE TITLE
Article and Media Pages: Need ability to add “noindex” and add keywords (AKC vocabulary) 

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#101]
This functionality is currently on the “news” and “AKC Dog Lovers” pages, need to be added to the micro site 

Examples with above functionality
http://www.akc.org/news/snow-is-shipped-by-train-to-alaska-for-iditarod/
http://www.akc.org/learn/akc-training/akc-training-good-dog/
http://www.akc.org/akc-dog-lovers/watch-this-husky-treat-himself-to-some-ice-cubes/

![image](https://cloud.githubusercontent.com/assets/13648969/13577090/ca15d688-e45e-11e5-8f40-4a57f49cc802.png)
![image](https://cloud.githubusercontent.com/assets/13648969/13577133/fa78d6f4-e45e-11e5-9088-02e2eda5a47c.png)

**Comment by kylejbertelsen** [comment]
All you need to do is turn on this vocabulary for the proper content types. Admin > Channel Administration > Channels

**Comment by skt2** [comment]
Time Spent: 2h

**CMS Changes:**
Enable AKC Vocabulary and Extra Metatags for Article and Media channels.
Login to CMS: Admin > Channel Administration > Channels 
Click "Edit Group Assignment" for channel you want to edit(Article or Media)
In Category Group: Select additional values: AKC Vocabulary and Extra Metatags
Click Update.

**Comment by spaulenoff** [comment]
Verified on Dev2

**Comment by spaulenoff** [comment]
@skt2 Not Verified on Stage-ng. I am seeing a bread crumb show up for noindex nofollow when that is chosen. http://stage-ng.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/
![image](https://cloud.githubusercontent.com/assets/13648969/13749260/f2b2ea54-e9d6-11e5-8880-202255439786.png)

Related to #100

**Comment by toshan2014** [comment]
in the end i did not work on this ticket/branch. did my fix in #100

**Comment by spaulenoff** [comment]
@skt2 Not verified on prod. There should be the following line of code in the source when noindex,nofollow is chosen 
![image](https://cloud.githubusercontent.com/assets/13648969/13856465/b93c3fd8-ec4b-11e5-8978-72fd5ee70083.png)

Currently all that was added were CMS changes

**Comment by skt2** [comment]
@kylejbertelsen What we want to do about this? Because all I did is CMS changes according to this comment: "All you need to do is turn on this vocabulary for the proper content types. Admin > Channel Administration > Channels"

**Comment by kylejbertelsen** [comment]
That comment was not quite correct. Some testing of it would have been good, comparing the View Source of a page in production versus one in a development/dev/stage environment. Essentially, if there was no difference, something was wrong.

Ultimately, when in doubt ask questions until there is no more doubt. Some very basic questions would have cleared this up:
- what is the intended consequence of this ticket?
- once this ticket is implemented, what effect will it have on our output?
- are there any template changes necessary to make this work?
- this is meant to replicate functionality in the /news and /akc-dog-lovers sections. Does this use any of the same templates, or do I need to replicate any code from those templates to other templates?

**Comment by spaulenoff** [comment]
Verified on Dev2
Examples: http://develop2.akc.org/content/westminster-dog-show/articles/live-test-coverage-blah/
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video/
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-2/?photo_id=0

**Comment by spaulenoff** [comment]
Verified on Prod
