### ISSUE TITLE
Article/Video/Photo-Gallery Pages: add in the recommended photosizes for the hero and thumbnails in CMS 

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#102]
Hero Image: 
Article
![image](https://cloud.githubusercontent.com/assets/13648969/13577416/5eb82be6-e460-11e5-89d5-7f0e6a3cb4db.png)

Media
![image](https://cloud.githubusercontent.com/assets/13648969/13577491/b9bb27b4-e460-11e5-95f1-dcff6c1290b3.png)

Thumbnail:
Article
![image](https://cloud.githubusercontent.com/assets/13648969/13577437/751ef194-e460-11e5-99da-4e778116d63e.png)

Media
![image](https://cloud.githubusercontent.com/assets/13648969/13577477/a2b4c6ce-e460-11e5-8564-73f3b6bcf35b.png)

Remove Article Image:
![image](https://cloud.githubusercontent.com/assets/13648969/13577456/83e0a56a-e460-11e5-85cc-edc9305bbb7d.png)

**Comment by kylejbertelsen** [comment]
@spaulenoff: Please define these sizes, and assign to @skt2, who will implement

**Comment by spaulenoff** [comment]
Category Hero: 1170px X 420px
Article Hero: 1170px X 305px
Video/Photo-Gallery Background Image: 1579px X 368px

Article Thumbnail: 246px X 164px
Video/Photo-Gallery: 246px X 164px

**Comment by skt2** [comment]
**CMS Changes:**
Admin > Channel Administration > Channel Fields > Article.
Edit Instruction for Images fields with recommended sizes.
Repeat the process for "Category Page" and "Media" Channels.

Admin > Channel Administration > Channel Fields > Article.
Remove Article Image: Click Delete link and confirm.

**Comment by spaulenoff** [comment]
Verified on Dev 2

**Comment by spaulenoff** [comment]
Verified on Stage

**Comment by spaulenoff** [comment]
@skt2 Verified on Prod. Please add ticket with time tracking for this ticket

**Comment by skt2** [comment]
Time Spent: 1
