### ISSUE TITLE
Article: Add the Teads code to the pages 

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#103]
Needs to have ability to add Teeds Code to pages
[AKC inRead Updated.txt](https://github.com/akcdotorg/akc.org/files/161776/AKC.inRead.Updated.txt)

Page Types that currently have this:
- /news/ (always on)
  http://www.akc.org/news/new-tech-helps-search-and-rescue-dogs-find-earthquake-survivors/
- /learn/ (always on)
  http://www.akc.org/learn/dog-health/cephalexin-for-dogs/
- generic, generic2, generic3 (Can toggle on and off in the cms)
  http://www.akc.org/downloadable-forms/
  http://www.akc.org/dog-owners/training/akc-therapy-dog-program/

Will confirm with @Elie to see if this should always be on or toggleable

**Comment by kylejbertelsen** [comment]
In the layout templates, there is the {layout} vars `use_in_content_video_ad` -- you'll need to replicate the functionality (and form-fields) there from the `generic` content type.

**Comment by spaulenoff** [comment]
Per Elie, This should be on by default, toggleable in the CMS to turn off if necessary

**Comment by elieo** [comment]
To clarify, we only want this on article pages.

**Comment by skt2** [comment]
**CMS Changes:**
Add new field to article channel:
Admin > Channel Administration > Channel Fields > Article > Create a New Channel Field
Type: Select Dropdown
Label : Use In-content Video Ad
Name: use_in_content_video_ad_article
Populate the menu manually: 
Yes
No 
Click Update.

**Comment by spaulenoff** [comment]
Verified on Stage

**Comment by spaulenoff** [comment]
@skt2 Verified on Prod. Please add comment regarding time tracking for this ticket

**Comment by skt2** [comment]
Time Spent: 2
