### ISSUE TITLE
Header Nav: "learn Should be highlighted when in the New Microsite Section

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#105]

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev2 http://develop2.akc.org/content/westminster-dog-show/

Seeing it work correctly for me

**Comment by stevepessah** [comment]
@spaulenoff were we trying to get the orange underline below LEARN or just have it highlighted?

**Comment by spaulenoff** [comment]
@stevepessah Going by the rest of the site, we just want it to be highlighted. Example for breeds section below:
![image](https://cloud.githubusercontent.com/assets/13648969/13639590/6c7b3bd0-e5df-11e5-8dd2-82ffc0c02c82.png)

**Comment by stevepessah** [comment]
Ok cool, verified on dev2.

**Comment by toshan2014** [comment]
please verify on stg

**Comment by spaulenoff** [comment]
@toshan2014 not seeing this on Stage http://stage-ng.akc.org/content/westminster-dog-show/ Checked on Chrome and FF

**Comment by toshan2014** [comment]
stage cms refresh/updated - check again

**Comment by spaulenoff** [comment]
verified on stage

**Comment by toshan2014** [comment]
pf

Photos Gallery:
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-2/?photo_id=0

Video:
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-2/

Article:
https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Comment by spaulenoff** [comment]
@toshan2014  Verified on Prod. Please add ticket with time tracking for this ticket

**Comment by toshan2014** [comment]
Time spent : 1h
