### ISSUE TITLE
Mayday Sprint Log

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#106]
**Planned for this Sprint:**
https://github.com/akcdotorg/akc.org/issues/101
https://github.com/akcdotorg/akc.org/issues/51
https://github.com/akcdotorg/akc.org/issues/86
https://github.com/akcdotorg/akc.org/issues/85
https://github.com/akcdotorg/akc.org/issues/99
https://github.com/akcdotorg/akc.org/issues/103
https://github.com/akcdotorg/akc.org/issues/98
https://github.com/akcdotorg/akc.org/issues/52
https://github.com/akcdotorg/akc.org/issues/83
https://github.com/akcdotorg/akc.org/issues/102
https://github.com/akcdotorg/akc.org/issues/92
https://github.com/akcdotorg/akc.org/issues/105
https://github.com/akcdotorg/akc.org/issues/87
https://github.com/akcdotorg/akc.org/issues/89
https://github.com/akcdotorg/akc.org/issues/90
https://github.com/akcdotorg/akc.org/issues/100
https://github.com/akcdotorg/akc.org/issues/4
https://github.com/akcdotorg/akc.org/issues/88
https://github.com/akcdotorg/akc.org/issues/84
https://github.com/akcdotorg/akc.org/issues/54
https://github.com/akcdotorg/akc.org/issues/82
https://github.com/akcdotorg/akc.org/issues/104
https://github.com/akcdotorg/akc.org/issues/80
https://github.com/akcdotorg/akc.org/issues/81
https://github.com/akcdotorg/akc.org/issues/108

**In Progress:**

**Needs Attention:**

**On Dev2 ready for QA:**

**Dev2 Approved:**

**On Stage ready for QA:**

**Stage Approved:**

**On Pre-Flight QA:**

**Pre-Flight Approved:**

**On Production:**
https://github.com/akcdotorg/akc.org/issues/51
https://github.com/akcdotorg/akc.org/issues/85
https://github.com/akcdotorg/akc.org/issues/99
https://github.com/akcdotorg/akc.org/issues/103
https://github.com/akcdotorg/akc.org/issues/98
https://github.com/akcdotorg/akc.org/issues/52
https://github.com/akcdotorg/akc.org/issues/83
https://github.com/akcdotorg/akc.org/issues/102
https://github.com/akcdotorg/akc.org/issues/92
https://github.com/akcdotorg/akc.org/issues/105
https://github.com/akcdotorg/akc.org/issues/87
https://github.com/akcdotorg/akc.org/issues/89
https://github.com/akcdotorg/akc.org/issues/90
https://github.com/akcdotorg/akc.org/issues/100
https://github.com/akcdotorg/akc.org/issues/4
https://github.com/akcdotorg/akc.org/issues/88
https://github.com/akcdotorg/akc.org/issues/84
https://github.com/akcdotorg/akc.org/issues/86
https://github.com/akcdotorg/akc.org/issues/81
https://github.com/akcdotorg/akc.org/issues/108

**Rejected on Production:**
https://github.com/akcdotorg/akc.org/issues/101 (Functionality was difficult to QA in dev2 and stage, was not functional once it went to Prod.)

**Removed from Sprint:**
https://github.com/akcdotorg/akc.org/issues/82 (Low priority, not enough time for dev team to work on this)
https://github.com/akcdotorg/akc.org/issues/104 (Low priority, not enough time for dev team to work on this)
https://github.com/akcdotorg/akc.org/issues/80 (no longer an issue)
https://github.com/akcdotorg/akc.org/issues/54 (Resovled via ticket #83)

**Comment by stevepessah** [comment]
@spaulenoff is this list just this - https://github.com/akcdotorg/akc.org/milestones/MayDay%20Microsite%20Completion

**Comment by spaulenoff** [comment]
@stevepessah Correct. This is just the sprint log that @kylejbertelsen asked for so he can see a general status all in one place

**Comment by stevepessah** [comment]
@spaulenoff ok, is the Boards view not working for them? This ticket just means we need to update things in two places.

**Comment by spaulenoff** [comment]
@stevepessah The Boards View is working, this was just a request from Kyle

**Comment by spaulenoff** [comment]
Team Notes
• Video/Article/Photo Gallery: Implement Social Share Counters https://github.com/akcdotorg/akc.org/issues/51
o   Update to display social shares on new article, photo-gallery and video pages
• Category Page - Mobile: Entire page rework https://github.com/akcdotorg/akc.org/issues/85
o   Update to design of the mobile category pages 
o   Time Spent - 12 hours
• Subcategory: Need to create new subcategory pages https://github.com/akcdotorg/akc.org/issues/99
o   Updated the design of subcategory pages on desktop and mobile, as well as update of functionality for these pages
o   Time spent - 20 hours
• Article: Add the Teads code to the pages https://github.com/akcdotorg/akc.org/issues/103
o   Update to add in incontent video ad code into article page templates
o   Time spent - 2 hours
• Category/Subcategory Page - Left Sidebar Format/Structure https://github.com/akcdotorg/akc.org/issues/98
o   Added functionality to easily navigate between category pages and subcategory pages on desktop
o   Time spent - 24 hours
• Category Page - Mobile: Left Navigation not working correctly https://github.com/akcdotorg/akc.org/issues/52
o   Added functionality to easily navigate between category pages and subcategory pages on mobile
o   Time spent - 16 hours
 Time spent differs from estimate due toin progress direction changes
• Photo Gallery Page - Mobile: 3 issues https://github.com/akcdotorg/akc.org/issues/83
o   Updated styling and design of photo-galleries on mobile
o   Time spent - 4 hours
• Article/Video/Photo-Gallery Pages: add in the recommended photosizes for the hero and thumbnails in CMS https://github.com/akcdotorg/akc.org/issues/102
o   Update to CMS to make it more intuitive for the image sizes that need to be uploaded.
o   Time spent - 1 hour
• Photo Gallery Page - Desktop: 7 issues https://github.com/akcdotorg/akc.org/issues/92
o   Updated styling and design of photo-gallery pages on desktop
o   Time spent - 2 hours
• Header Nav: "learn Should be highlighted when in the New Microsite Section https://github.com/akcdotorg/akc.org/issues/105
o   Updated functionality to highlight header nav category that you are in
o   Time spent - 1 hour
• Sub-Category Page - Mobile: 1 issue https://github.com/akcdotorg/akc.org/issues/87
o   Update to styling and design of subcategory pages on mobile
o   Time spent - 2 hours
• Video Page - Desktop: 3 issues https://github.com/akcdotorg/akc.org/issues/89
o   Updated styling and design of video pages on desktop
o   Time spent - 5 hours
• Video Page - Mobile: 3 issues, Mobile Tweaks https://github.com/akcdotorg/akc.org/issues/90
o   Updated styling and design of video pages on mobile
o   Time spent - 3 hours
• Individual content pages: Change up breadcrumb Structure https://github.com/akcdotorg/akc.org/issues/100
o   Updated Bread crumb styling and functionality across content pages
o   Time spent - 7 hours
 Category structure was modified which affected time spent on the ticket vs estimate
• SEO: Author & Publisher OG Tags https://github.com/akcdotorg/akc.org/issues/4
o   SEO update to allow the author of a piece of content’s Facebook page to be linked in the Open Graph data
 Applicable on new article, photo-gallery, video, news article and akc dog lover’s article.
o   Time spent - 6 hours
• Article Page - Mobile: 2 issues https://github.com/akcdotorg/akc.org/issues/88
o   Updated style and functionality of new article pages on mobile
o   Time spent - 2 hours
• Global - Desktop: 2 issues https://github.com/akcdotorg/akc.org/issues/84
o   Updated styling and functionality of new category pages, subcategory pages and content pages on desktop
o   Time spent - 6 hours
• Article Page - Desktop: 3 issues https://github.com/akcdotorg/akc.org/issues/81
o   Updated style and functionality of new article pages on desktop
o   Time spent - 1 hour
• Create Separate Categories Field in CMS to slowly move content over from /learn/ to /content/ https://github.com/akcdotorg/akc.org/issues/108
o   Added feature to allow team to slowly migrate content from the old microblog pages to the new microsites.
o   Time spent - 6 hours
• Category Page - Desktop: 2 issues https://github.com/akcdotorg/akc.org/issues/86
o   Update to design of category page on desktop
o   Time spent - 3 hours

Planned tickets that were not included in final release
• Article and Media Pages: Need ability to add “noindex” and add keywords (AKC vocabulary) https://github.com/akcdotorg/akc.org/issues/101
o   Was difficult to QA in develop2 and stage environments due to those environments already having noindex tags associated with them
o   There was a miscommunication between team and developer, and developer thought that the change only had to be applied in the CMS
o   Development team has learned that if ticket isn’t completely clear, to ask question.
o   Project team has learned it needs to provide as much information as possible within the ticket to try and avoid confusion
• Sub-Category Page - Desktop: 2 issues https://github.com/akcdotorg/akc.org/issues/82
o   Removed from sprint due to low priority of this task and lack of time time for developers to work on this task
o   Will revisit in next sprint
• Category/Subcategory pages: Clean up CMS Templates  https://github.com/akcdotorg/akc.org/issues/104 
o   Removed from sprint due to low priority of this task and lack of time time for developers to work on this task
o   Will revisit in next sprint
