### ISSUE TITLE
Create Separate Categories Field in CMS to slowly move content over from /learn/ to /content/

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#108]

**Comment by kylejbertelsen** [comment]
-Entertainment
--Heartwarming
--Funny
--Cute
--Interesting 
--Things To Do With Your Dog

-Dog Training
--Basics
--Advance
--Tricks
--Agility
--Unwanted Behavoirs 
--Trainnig Tips 

-Dog Health
--Nutrition
--Fitness
--Care
--Grooming
--Health Tips
--Diseases
--Symptoms

-Breeders
--Education
--Science
--Genetics & DNA
--Health Testing
--Reproduction
--AKC Breeder Programs
--Business Advice 
--Registration

-Fancy
--AKC Sports
--Gazette
--Events
--History & Archive
--Rules and Regulations

-What to Expect 
--Puppy
--Adult Dog
--Senior Dog 

-Westminster Dog Show
--Live Coverage

**Comment by kylejbertelsen** [comment]
All are added in develop2. Will duplicate to stage, and eventually production.

**Comment by spaulenoff** [comment]
@elieo @stevepessah Please QA in the CMS and on Dev2 https://develop2.akc.org/content/westminster-dog-show/

**In Dev2 CMS:**
Admin>Channel Admin>Categories>Category Pages

**Comment by elieo** [comment]
@spaulenoff  can you confirm that you QAed this before I do?

**Comment by spaulenoff** [comment]
I QA'd this yes

**Comment by elieo** [comment]
@spaulenoff 
This looks good. Confirmed on Dev2. Thanks

**Comment by spaulenoff** [comment]
@kylejbertelsen Verified on Stage in the CMS, please confirm once the the sidebar links from #98 are pushed to stage

**Comment by kylejbertelsen** [comment]
Required in production, upon launch:
- Add any Channel Pages terms to Categories
- In database, find the unique ids for the Channel Pages we're converting (W-D-S, Live-Content, etc), and edit the exp_category_posts to match the new uids.
- Admin > Channel Admin > Channels, set 'Group Assignments' to use `Channel Pages` and not use `Microblogs` in 'Channel Pages', 'Article' and 'Media'
- Add-Ons > Extensions > Low SegCat - set to use only `Channel Pages`

**Comment by spaulenoff** [comment]
@kylejbertelsen Elie confirmed he wants the following categories available on production
-Events (Category)
--Westminster Dog Show (Sub Category)
---Live Coverage (Sub Sub Category)

**Comment by kylejbertelsen** [comment]
Approximate time spent: 6 hours

**Comment by spaulenoff** [comment]
@kylejbertelsen Verified on Prod. Please ad time tracking to this ticket
