### ISSUE TITLE
Add CTA to Delegates Portal page so if a delegate is logged out, they can click that link to log in

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#11]
http://www.akc.org/delegate/delegates-portal/
Let's add this copy at the end of the first sentence and hyperlink Login: "Login here."

**Comment by pps2010** [comment]
It seems when you are already logged in and are not a delegate and you reach this page then it may seem weird to be able to click on "Login"  - maybe the text / link needs to be conditional?

**Comment by kylejbertelsen** [comment]
I agree with Purvi. As part of this ticket, let's hide the usual AKC login link when adding this CTA.

**Comment by kylejbertelsen** [comment]
As per Steve, if You're logged-in as a delegate, this page will forward you on elsewhere, so don't worry about conditionals whether to show the link or not.

**Comment by toshan2014** [comment]
Please QA : http://develop2.akc.org/delegate/delegates-portal/

"Login Here" is below just because of the space allocated for these lines. We can increase the width of the area if we absolutely need it on the same line.

**Comment by spaulenoff** [comment]
@toshan2014 Can we please include the login here on the first line? Additionally, when i click sign in and login via the Gigya modal, it takes a few seconds to register and clears the space where enter my username and password. It ends up working after a few seconds.

**Comment by toshan2014** [comment]
Added "Login Here" on first line. For the lagging, please compare with main Sign In and let me know. Both are calling the same function so there can't be any difference normally.

**Comment by toshan2014** [comment]
Time spent: 1h15min

**Comment by spaulenoff** [comment]
@stevepessah Please QA on develop2. This looks good to me, please confirm http://develop2.akc.org/delegate/delegates-portal/

**Comment by toshan2014** [comment]
Should be fixed on mobile now

**Comment by stevepessah** [comment]
@toshan2014 on mobile, please put the "Login Here" link on a separate line below the previous copy.

**Comment by toshan2014** [comment]
please check : http://develop2.akc.org/delegate/delegates-portal/

**Comment by toshan2014** [comment]
Time spent: 1h30min

**Comment by spaulenoff** [comment]
Seeing this on Develop 2 Verified.

**Comment by toshan2014** [comment]
stg: http://stage-ng.akc.org/delegate/delegates-portal/

**Comment by spaulenoff** [comment]
Verified on Stage @stevepessah Please confirm it looks good to you as well

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by aalattili** [comment]
Title of 'Delegate portal' page is out of page boarders in portrait (Mobile-delegate portal.png)
![mobile-delegate portal](https://cloud.githubusercontent.com/assets/12289479/14529638/26560086-025e-11e6-9803-302df7709c28.png)

**Comment by toshan2014** [comment]
pf Please QA : http://develop2.akc.org/delegate/delegates-portal/

**Comment by aalattili** [comment]
QA retest failed on mobile web (Android & iOS).

![failed-delegate portal page](https://cloud.githubusercontent.com/assets/12289479/14629891/7bf139ae-0612-11e6-9b33-6833b12b4b1e.png)

**Comment by spaulenoff** [comment]
Verified on Prod
