### ISSUE TITLE
Mayday Photo-Gallery/Video Template: Remove bottom email signup and make lower 300x600 ad unit sticky

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#112]
Related to #81

**Comment by kylejbertelsen** [comment]
Define 'sticky'. By this, do you mean the sliding ad, like on the Articles?

Blocked until answered.

**Comment by spaulenoff** [comment]
@kylejbertelsen Confirmed, please make the sidebar sliding like it is on Articles

**Comment by kylejbertelsen** [comment]
Note: current implementation is in /public_html/src/js/components/ads.js, starting with "/\* Vertical dynamically-floating div within another div */"

You can do this by adjusting the jQuery selector for the page to include the pages you're targeting.

**Comment by toshan2014** [comment]
@kylejbertelsen 
My understanding:
- @spaulenoff I don't see a sign-up on this page for example, unless I'm missing something: http://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-1/
- Implement ad similar to http://www.akc.org/content/dog-breeding/articles/tax-tips-for-dog-breeders/

Note: I don't see ad x37 functioning on the page above. It will need to be looked into as well.

Estimate: 3h

**Comment by spaulenoff** [comment]
This Will only need to be updated on Photo Gallery and Video Pages:
http://www.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/
http://www.akc.org/content/dog-training/photo-galleries/teach-your-dog-to-give-you-a-high-five/

I will edit the ticket title to better represent this

**Comment by skt2** [comment]
Time Spent: 7h

Test Gallery and Video are here: http://develop2.akc.org/content/westminster-dog-show/

**Comment by AKCOsama** [comment]
QA passed, Applied on Stage and develop2 and only on Photo Gallery and Video Pages.

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by spaulenoff** [comment]
Verified on Prod
