### ISSUE TITLE
Ability to Add E-Book CTA to new Article Pages in the CMS

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#113]
Need ability to add E-Book CTA to new Article Pages in the CMS. Same way you can add ebook cta's to /news/ /akc-dog-lovers/ and /learn/

This needs to be added in the CMS but it also needs to show up on the pages it self.

Examples: 
http://www.akc.org/learn/akc-training/why-puppies-and-femal-dogs-hump-or-mount/
http://www.akc.org/learn/dog-health/diabetes-in-dogs/
http://www.akc.org/learn/family-dog/dog-fever-and-temperature/

**Comment by spaulenoff** [comment]
Only apply the CTA do article pages.

**Comment by toshan2014** [comment]
Add an ebook to article through the Article channel ( last entry ):

Please QA : 
https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/ ( has an ebook )

https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-1/ ( has no ebook )

**Comment by toshan2014** [comment]
Time spent: 1h30min

**Comment by toshan2014** [comment]
Stage : http://stage-ng.akc.org/content/westminster-dog-show/articles/tax-tips-for-dog-breeders/

**Comment by toshan2014** [comment]
pf : 
https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/ ( has an ebook )

https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-1/ ( has no ebook )

**Comment by toshan2014** [comment]
verified on prod - @spaulenoff please double check

**Comment by spaulenoff** [comment]
Verified on Prod
