### ISSUE TITLE
Article/Photo-Gallery/Video Pages - Most Popular in Section needs to pull in 6 most recent pieces of content, regardless of type

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#114]
Most Popular in Section needs to pull in 6 most recent pieces of content, regardless of type. Currently pulling in 2 most recent pieces of content of each type (article/photo-gallery/video), instead of overall newest 6 pieces of content.

related to https://github.com/akcdotorg/akc.org/issues/84

**Comment by skt2** [comment]
**Time Spent: 4h**

**Comment by spaulenoff** [comment]
@skt2 Verified on Dev2 http://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Comment by spaulenoff** [comment]
@stevepessah @elieo Please QA on Dev2:
http://develop2.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-2/

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage: http://stage-ng.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/
http://stage-ng.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/
http://stage-ng.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0
http://stage-ng.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by spaulenoff** [comment]
Verified on Prod
