### ISSUE TITLE
Combine all header snippets into one.

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#116]
Delete the others, both from filesystem and from the CMS.

**Comment by skt2** [comment]
Time Spent: 4h

**CMS Changes:**
CMS > Design > Templates > Snippets
Look for {snip-header-dynamic} and {snip-header-training}  -- Delete.

**Comment by skt2** [comment]
Going to delete {snip-header-dynamic} and {snip-header-training} snippets as it seems we are not using this anywhere. @kylejbertelsen @toshan2014 Please let me know if you know that we still need this.

Going to keep {snip-header-microblog} snippet until we get rid of /learn section so I am thinking not to spent time combining this one because eventually we gonna get rid of this.

**Comment by toshan2014** [comment]
@skt2 I've done a search and find for those two snippets. I can't see them being used anywhere. So I would think they can be deleted.

**Comment by skt2** [comment]
@kylejbertelsen so If understood this correctly, there is nothing left to combine, All I need to do is delete couple of snippets from CMS and File systems and I am done right?

**Comment by kylejbertelsen** [comment]
Make certain that they don't appear anywhere -- then, yes -- but delete them from both the CMS and from the filesystem.

**Comment by kylejbertelsen** [comment]
And ... actually -- check out the scss-to-compass branch, and do the same in that branch.

**Comment by skt2** [comment]
Thanks. Sure, I will delete above mentioned snippet from scss-to-compass branch, and push the changes to origin.

**Comment by skt2** [comment]
@spaulenoff, Here is how you can test this changes:
1. Make sure they are gone from CMS.
2. Make sure site is stable and nothing is broken after this action.

**Comment by spaulenoff** [comment]
@skt2 Where in the CMS do i check if they are gone?

**Comment by skt2** [comment]
CMS > Design > Templates > Snippets

**Comment by skt2** [comment]
@spaulenoff We don't want to delete {snip-header-microblog} until and unless we get rid of /learn/ section. FYI
