### ISSUE TITLE
Combine all footer snippets into one.

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#117]
Delete others from filesystem and CMS.

**Comment by skt2** [comment]
Time Spent: 4h

**CMS Changes:**
CMS > Design > Templates > Snippets
Look for {snip-footer-dynamic}, {snip-footer-microblog} and {snip-footer-training} -- Delete.

**Comment by skt2** [comment]
Going to delete {snip-footer-dynamic}, {snip-footer-training} and {snip-footer-microblog} snippets as it seems we are not using this anywhere. @toshan2014 Can you please confirm this at your end once, just to be double sure?

**Comment by skt2** [comment]
@kylejbertelsen  Snippets to delete: {snip-footer-dynamic}, {snip-footer-training} and {snip-footer-microblog}
