### ISSUE TITLE
Set up Compass and Foundation in your sandbox

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#119]
Instructions here: https://github.com/akcdotorg/akc.org/wiki/setup

Follow instructions. Ask questions/advice of Kyle. Reassign to Kyle when you're done.

**Comment by kylejbertelsen** [comment]
Familiarize yourself with the standards on: https://github.com/akcdotorg/akc.org/wiki/scss

When working with scss-to-compass branch, you'll want to update in the CMS any snippets that have been edited in that branch:
- snip-footer-dynamic
- snip-footer
- snip-header-dynamic
- snip-header-microblog
- snip-header
- snip-learn-detail

Let Kyle know of any others you come across, and he'll add them to this list.

**Comment by toshan2014** [comment]
Setting-up Compass and Foundation seems successful. Below is a screenshot of what I see:
<img width="418" alt="scss-compass" src="https://cloud.githubusercontent.com/assets/6847220/13930584/a6a34358-ef5c-11e5-88c5-a228d4f37e77.PNG">

Please inform if incorrect

**Comment by toshan2014** [comment]
Time spent : 45min
