### ISSUE TITLE
Category/Subcategory Page: Title tag isn't being pulled from CMS

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#120]
Title tag isn't being pulled from CMS for category pages. For Example - http://www.akc.org/content/westminster-dog-show/

What is in the CMS:
![image](https://cloud.githubusercontent.com/assets/13648969/13887973/1ff90d7c-ed15-11e5-82e8-77ff8b88a658.png)

**Comment by kylejbertelsen** [comment]
Please clarify what is missing, and what is currently there. Please give specifics: meta name="title"? < title >< /title >? etc. Please test by giving a cat page different values in existing form, so you can know what is coming from where.

**Comment by spaulenoff** [comment]
On the following page: http://develop2.akc.org/content/westminster-dog-show/ The Title tag is not pulling from source 
![image](https://cloud.githubusercontent.com/assets/13648969/13891576/58d11ae6-ed28-11e5-8169-4f9cf6028907.png)

CMS form:
![image](https://cloud.githubusercontent.com/assets/13648969/13891591/6cd5c744-ed28-11e5-8439-15fd0c950ac1.png)
![image](https://cloud.githubusercontent.com/assets/13648969/13891595/75ee6606-ed28-11e5-84f1-009dcc042b8a.png)

**Comment by kylejbertelsen** [comment]
Looks to me like it's appending Media. Just remove what's making it do that.

@spaulenoff: Should it also stop appending ' Video' and ' Photo Gallery' on those pages?

**Comment by spaulenoff** [comment]
Almost but tag of the page is not pulling correctly.
![image](https://cloud.githubusercontent.com/assets/13648969/13891780/8f74f8a0-ed29-11e5-89a0-506173390ffc.png)

Per the second note, do not change the other pages

**Comment by toshan2014** [comment]
Please QA :
https://develop2.akc.org/content/westminster-dog-show/
https://develop2.akc.org/content/westminster-dog-show/live-coverage/
https://develop2.akc.org/content/westminster-dog-show/videos/westminster-most-popular-section-test-video/
https://develop2.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/
https://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-most-popular-section-test-gallery/?photo_id=0

**Comment by toshan2014** [comment]
Time spent: 02:15

**Comment by spaulenoff** [comment]
Verified on Develop 2: https://develop2.akc.org/content/test/
https://develop2.akc.org/content/westminster-dog-show/
https://develop2.akc.org/content/westminster-dog-show/live-coverage/

**Comment by toshan2014** [comment]
Stage:
http://stage-ng.akc.org/content/westminster-dog-show/
http://stage-ng.akc.org/content/westminster-dog-show/live-coverage/

**Comment by spaulenoff** [comment]
@stevepessah Please Verify on Stage: http://stage-ng.akc.org/content/dog-training/basic-training/
http://stage-ng.akc.org/content/dog-training/

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by toshan2014** [comment]
pf:
https://develop2.akc.org/content/test/
https://develop2.akc.org/content/westminster-dog-show/
https://develop2.akc.org/content/westminster-dog-show/live-coverage/

**Comment by spaulenoff** [comment]
Verified on PF

**Comment by toshan2014** [comment]
verified on prod - @spaulenoff please double check

**Comment by spaulenoff** [comment]
Verified on Prod
