### ISSUE TITLE
Category/Subcategory Page: Remove "media" that is appended at the end of the OG Title and Twitter Title

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#121]
Examples:
http://www.akc.org/content/westminster-dog-show/
http://www.akc.org/content/breeding/
http://www.akc.org/content/dog-health-1/

**Comment by skt2** [comment]
Time Spent: Still working

**Comment by toshan2014** [comment]
Fixed as part of #120 - please QA

**Comment by toshan2014** [comment]
Time spent: 30 min

**Comment by spaulenoff** [comment]
Verifified as part of #120

**Comment by toshan2014** [comment]
Stage:
http://stage-ng.akc.org/content/westminster-dog-show/live-coverage/
http://stage-ng.akc.org/content/westminster-dog-show/

**Comment by spaulenoff** [comment]
verified on stage as part #120

**Comment by toshan2014** [comment]
pf:
develop2.akc.org/content/westminster-dog-show/live-coverage/
develop2.akc.org/content/westminster-dog-show/

**Comment by spaulenoff** [comment]
Verified on Pre-flight with #120

**Comment by toshan2014** [comment]
verified on prod - @spaulenoff please double check

**Comment by spaulenoff** [comment]
Verified on Prod
