### ISSUE TITLE
New Microsite Pages: Internal Links are point to pieces of content without the ending slash

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#122]
Category/Subcategory page example: For example currently the tiles on http://www.akc.org/content/breeding/ are point to: http://www.akc.org/content/breeding/articles/tax-tips-for-dog-breeders they should point to http://www.akc.org/content/breeding/articles/tax-tips-for-dog-breeders/ 

Content Example: Tiles on http://www.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/ are pointing to http://www.akc.org/content/westminster-dog-show/articles/masters-agility-and-obedience-results instead of http://www.akc.org/content/westminster-dog-show/articles/masters-agility-and-obedience-results/

**Comment by toshan2014** [comment]
Please QA:
https://develop2.akc.org/content/westminster-dog-show/
https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Comment by toshan2014** [comment]
Time spent: 30min

**Comment by spaulenoff** [comment]
@stevepessah @elieo This is working correctly when I QA'd. Please QA on dev2: http://develop2.akc.org/content/westminster-dog-show/ > http://develop2.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/
http://develop2.akc.org/content/westminster-dog-show/ > http://develop2.akc.org/content/westminster-dog-show/videos/westminster-most-popular-section-test-video/
http://develop2.akc.org/content/westminster-dog-show/ > http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-2/

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by toshan2014** [comment]
stage : 
http://stage-ng.akc.org/content/westminster-dog-show/

**Comment by spaulenoff** [comment]
@stevepessah Please QA on stage: http://stage-ng.akc.org/content/westminster-dog-show/
http://stage-ng.akc.org/content/westminster-dog-show/live-coverage/

Most popular in section:
http://stage-ng.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0
http://stage-ng.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/
http://stage-ng.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by toshan2014** [comment]
pf:
https://develop2.akc.org/content/westminster-dog-show/
https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Comment by spaulenoff** [comment]
Verified on Pre-Flight

**Comment by toshan2014** [comment]
verified on prod - @spaulenoff please double check

**Comment by spaulenoff** [comment]
Verified on Prod
