### ISSUE TITLE
Category Page: Remove Text Underline when hovering over View more Button for each section (Articles, Photo-Galleries, Videos)

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#123]
Need to Remove Text Underline when hovering over View more Button for each section (Articles, Photo-Galleries, Videos). 

Example: http://www.akc.org/content/westminster-dog-show/

![image](https://cloud.githubusercontent.com/assets/13648969/13888231/bbf798dc-ed16-11e5-90fb-9fc5ecfef25f.png)

**Comment by toshan2014** [comment]
Please QA : 
https://develop2.akc.org/content/westminster-dog-show/

**Comment by toshan2014** [comment]
Time spent: 1h

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev2 Desktop: https://develop2.akc.org/content/westminster-dog-show/
https://develop2.akc.org/content/westminster-dog-show/articles/

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by toshan2014** [comment]
Stage:
http://stage-ng.akc.org/content/westminster-dog-show/

**Comment by spaulenoff** [comment]
@stevepessah Please verify on stage http://stage-ng.akc.org/content/westminster-dog-show/

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by toshan2014** [comment]
pf:
https://develop2.akc.org/content/westminster-dog-show/
https://develop2.akc.org/content/westminster-dog-show/articles/

**Comment by spaulenoff** [comment]
Verified on Prefligt

**Comment by toshan2014** [comment]
prod http://www.akc.org/content/westminster-dog-show/

**Comment by spaulenoff** [comment]
Verified on Prod
