### ISSUE TITLE
Category/Subcategory page: Mobile - Have H1 Orange bar adjust to the length of the H1 tag

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#124]
Currently the H1 tag on mobile category pages are sometimes too wide. Example: http://www.akc.org/content/breeding/
![image](https://cloud.githubusercontent.com/assets/13648969/13888395/9b935652-ed17-11e5-8221-ccfa7d4f2e48.png)

Can we make the Orange bar adjust to the length of the H1 tag?

**Comment by skt2** [comment]
Time Spent: 2h

**Comment by spaulenoff** [comment]
Verified on Prod
