### ISSUE TITLE
Article Page: Change h2 Tag 

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#125]
Update h2 tag **WITHIN THE ARTICLE CONTENT** on article pages to following dimensions:
- margin: 20px 0 20px; 
- font-size: 1.7rem; 
- text-transform: none !important;

**Comment by elieo** [comment]
To clarify, we want the end result to look like this: 
![image](https://cloud.githubusercontent.com/assets/1423008/13890678/1e5dd714-ed23-11e5-9751-60a64fd937fa.png)

**Comment by toshan2014** [comment]
Please QA : https://develop2.akc.org/content/westminster-dog-show/articles/masters-agility-and-obedience-results/

Note: It does look odd that the H1 main title is smaller than the in-article H2s now

**Comment by toshan2014** [comment]
Time spent: 15min

**Comment by spaulenoff** [comment]
@stevepessah @elieo Please QA on Dev2: http://develop2.akc.org/content/test/articles/tax-tips-for-dog-breeders/

Toshan has a point that the H2 (1.7em) tag is now larger then the H1 (1.44em). Please confirm how you would like to proceed here

**Comment by stevepessah** [comment]
@elieo does look very odd having the h2 bigger than the h1. Your call though.

**Comment by elieo** [comment]
@stevepessah  you're leading this now. You make the call.

**Comment by spaulenoff** [comment]
@toshan2014 can you make the h2 tag 1.31em? We want to see how the h2 looks when it is smaller than the H1

**Comment by toshan2014** [comment]
Made CSS changes to margin and H2 size for better visual results: 
https://develop2.akc.org/content/test/articles/tax-tips-for-dog-breeders/

**Comment by spaulenoff** [comment]
@stevepessah Please QA and advise if this looks good to you

**Comment by toshan2014** [comment]
on stg : http://stage-ng.akc.org/content/westminster-dog-show/articles/tax-tips-for-dog-breeders/

**Comment by spaulenoff** [comment]
Verified on stage

**Comment by toshan2014** [comment]
pf:

http://develop2.akc.org/content/westminster-dog-show/articles/masters-agility-and-obedience-results/

**Comment by spaulenoff** [comment]
verified on pf

**Comment by toshan2014** [comment]
prod : http://www.akc.org/content/westminster-dog-show/articles/masters-agility-and-obedience-results/

**Comment by spaulenoff** [comment]
Verified on Prod
