### ISSUE TITLE
Article Pages: Desktop - Image Sizing isn't working in CMS 

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#126]
On Example page http://www.akc.org/content/breeding/articles/tax-tips-for-dog-breeders/ the photos are automatically becoming full screen, no matter the dimensions you choose in the cms

![image](https://cloud.githubusercontent.com/assets/13648969/13889098/27a9d154-ed1b-11e5-9e91-760e757cd302.png)

Sizes in CMS: 
![image](https://cloud.githubusercontent.com/assets/13648969/13889119/3da701e8-ed1b-11e5-82f3-3ee04361d3c1.png)

Only affecting newly uploaded pieces of content

**Comment by skt2** [comment]
Time Spent: 3h

**CMS Changes:**
CMS > Admin > Channel Admin > Channel Fields > Article > Article Content 
Instructions: Article text. While inserting an image recommended maximum width: 800px

**Comment by skt2** [comment]
Example: http://develop2.akc.org/content/westminster-dog-show/articles/masters-agility-and-obedience-results/

**Comment by spaulenoff** [comment]
Not Verified on Dev2. http://develop2.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/

The following image is being stretched vertically:
![image](https://cloud.githubusercontent.com/assets/13648969/13927402/f6875584-ef67-11e5-8c91-4e1162055667.png)

**Comment by spaulenoff** [comment]
@stevepessah IT looks good to me on Dev2 desktop and mobile. Please verify on this piece of test content i created: http://develop2.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/

**Comment by spaulenoff** [comment]
@stevepessah and @elieo  Please QA on Dev2: http://develop2.akc.org/content/test/articles/tax-tips-for-dog-breeders/
http://develop2.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/

It looks good to me and i checked mobile that it is working as well

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on stage: http://stage-ng.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/
http://stage-ng.akc.org/content/westminster-dog-show/articles/tax-tips-for-dog-breeders/

They look good to me

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by spaulenoff** [comment]
Verified on Prod
