### ISSUE TITLE
Article/Video/Photo-Gallery: Desktop - Change style of social Share button

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#127]
Change from box style as it currently is to flat style like this http://screencast.com/t/mrpNeq7avrpG  

http://www.akc.org/content/breeding/articles/tax-tips-for-dog-breeders/

**Comment by elieo** [comment]
Also, the share count should be vertically centered.

**Comment by skt2** [comment]
Time Spent: 4h

**Comment by skt2** [comment]
@spaulenoff After changing desktop style, this is how it looks on tablet so please let me know how we want to style it on tablet.

![screen shot 2016-03-22 at 9 56 26 am](https://cloud.githubusercontent.com/assets/16002526/13953888/9aac21b0-f014-11e5-9f1e-f586b39093e5.png)

**Comment by skt2** [comment]
@elieo what do you think?
1st
![screen shot 2016-03-22 at 10 21 12 am](https://cloud.githubusercontent.com/assets/16002526/13954671/2c5288cc-f018-11e5-9efc-dfc13b52569a.png)

2nd
![screen shot 2016-03-22 at 10 22 18 am](https://cloud.githubusercontent.com/assets/16002526/13954682/37752034-f018-11e5-8376-2925b3488881.png)

3rd
![screen shot 2016-03-22 at 10 22 56 am](https://cloud.githubusercontent.com/assets/16002526/13954692/405f4990-f018-11e5-8de5-d717c49b5090.png)

**Comment by elieo** [comment]
@skt2 3rd option looks good. But let's add some width to the article title.

**Comment by skt2** [comment]
Got it. Thanks! This is how its gonna be.
![screen shot 2016-03-22 at 10 31 01 am](https://cloud.githubusercontent.com/assets/16002526/13954963/440fef4e-f019-11e5-9549-497126846bae.png)

**Comment by spaulenoff** [comment]
@stevepessah and @elieo Please QA on Dev2: http://develop2.akc.org/content/test/articles/tax-tips-for-dog-breeders/
http://develop2.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/

It looks good to me and i checked tablet that it is working as well. The buttons are working correctly for me

**Comment by stevepessah** [comment]
@spaulenoff social share button style verified on dev2.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on stage: http://stage-ng.akc.org/content/westminster-dog-show/articles/test-article-different-image-sizes/
http://stage-ng.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0
http://stage-ng.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/
http://stage-ng.akc.org/content/westminster-dog-show/articles/tax-tips-for-dog-breeders/

I checked on desktop and tablet it looked good to me

**Comment by stevepessah** [comment]
Verified on stage on desktop/tablet.

**Comment by spaulenoff** [comment]
Verified on Prod
