### ISSUE TITLE
Article/Video/Photo-Gallery Pages: Mobile - Twitter share button is “{title}” in the tweet 

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#128]
Example: http://www.akc.org/content/breeding/articles/tax-tips-for-dog-breeders/

![image](https://cloud.githubusercontent.com/assets/13648969/13889295/2f635fb8-ed1c-11e5-86da-1423a75c35f6.png)

This is working properly on desktop:
![image](https://cloud.githubusercontent.com/assets/13648969/13891410/4a9c8092-ed27-11e5-841f-58af26285dd4.png)

**Comment by skt2** [comment]
Time Spent: 3h

**Comment by spaulenoff** [comment]
Verified on Prod
