### ISSUE TITLE
Change Sticky Social share button

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#13]
https://akcorg.atlassian.net/browse/AKC2-434

**Comment by spaulenoff** [comment]
Can we update anywhere on the site that has the sticky share button to match the style in the attached screenshot:
![pasted image at 2016_01_19 03_58 pm](https://cloud.githubusercontent.com/assets/13648969/13398914/898e8e10-dece-11e5-8eeb-7f4be50ab17f.png)
