### ISSUE TITLE
New CSS for Wrapper

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#130]
Build-out the namespaced css for the header and footer, so they can be included in ancillary sites.

Styles should be:
- namespaced, as to have minimal effect on the remainder of the calling page
- namespaced, as to protect the wrapper itself from inadvertently styling the header and footer in the calling page
- optionally include the akc.org normalization and screen stylesheets, but not require them

**Comment by kylejbertelsen** [comment]
Time tracking:
Estimate: 16 hours
2016-03-21: 04 hours
2016-03-22: 03 hours
2016-03-23: 04 hours
2016-03-24: 03 hours
2016-03-25: 01 hours
2016-03-28: 01 hours
2016-03-29: 02 hours
2016-03-30: 02 hours

**Comment by spaulenoff** [comment]
- @kylejbertelsen Just so the notes are all in one place. 
- Desktop Header: https://docs.google.com/document/d/11wME5l--pzDR1XKsiOhND22tfcpejdTYUKsR2uCR2KM/edit
- Desktop Footer: https://docs.google.com/document/d/1GFYQC5Xx-_1ZfNsxpFhiKcTspTKf0acQMmtLYAE34wg/edit
- Mobile Footer: ![mobile footer markup](https://cloud.githubusercontent.com/assets/13648969/14044710/f1035afe-f269-11e5-92aa-11dafc9859b0.png)
- Mobile Header: Working on this

**Comment by spaulenoff** [comment]
First Mobile header markup: 

![mobile header top level markup](https://cloud.githubusercontent.com/assets/13648969/14046282/ca5e8aba-f276-11e5-8d28-922d823f03b9.png)

Subnav Markup: 

![mobile header subnav mark up](https://cloud.githubusercontent.com/assets/13648969/14046373/75ae1b42-f277-11e5-86ee-b22a02e4c220.png)

Sub subnav markup: 

![mobile header sub subnav mark up](https://cloud.githubusercontent.com/assets/13648969/14046449/01c26188-f278-11e5-965a-90739b42ad1f.png)

**Comment by spaulenoff** [comment]
Feedback from Aspire (Please let me know if you can't open up any of these zips): 
[Header Footer QA.zip](https://github.com/akcdotorg/akc.org/files/191857/Header.Footer.QA.zip)
[HTC Nexus 9 Android v 6.0.zip](https://github.com/akcdotorg/akc.org/files/191858/HTC.Nexus.9.Android.v.6.0.zip)
[iPhone IOS v 8.3.zip](https://github.com/akcdotorg/akc.org/files/191860/iPhone.IOS.v.8.3.zip)
[Desktop Win 7 64-bit.zip](https://github.com/akcdotorg/akc.org/files/191859/Desktop.Win.7.64-bit.zip)

**Comment by kylejbertelsen** [comment]
Clarification for Aspire: the only page that should have contained this styling was the home page -- it's not applied anywhere else. That will be changing today to a URL where the wrapper is being consumed, as a client-site would.

A testable URL will soon follow in a comment from @skt2

**Comment by stevepessah** [comment]
Main requirement for this is that it matches the current header/footer.

**Comment by kylejbertelsen** [comment]
Closing this to start a new ticket from the current starting-point.
