### ISSUE TITLE
Update Featured Article Display for /news/ articles

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#133]
Look through codebase for any other instances where there's an img tag in place of the correct div with the background URL, as fixed in the blog/.listing.html today.

**Comment by toshan2014** [comment]
Please QA @spaulenoff

**Comment by spaulenoff** [comment]
Verified on Prod

**Comment by toshan2014** [comment]
Merged and pushed AKC3-133  to develop2

**Comment by toshan2014** [comment]
I don't think it's a good idea to blindly replace all img tags by background imgs. It can be risky and in some places they might be serving a purpose. I think it's better to identify an issue first then do the change. @kylejbertelsen agree?

**Comment by toshan2014** [comment]
Added changed to author listing. That was one other place where `class="article-img"` existed.

**Comment by spaulenoff** [comment]
@toshan2014 How do I QA this?

**Comment by toshan2014** [comment]
@spaulenoff If an article is "featured" it appears on the author's page as featured too:
https://develop2.akc.org/author/liz-donovan/

I don't know whether on the author's page, the featured article was hidden on purpose because I don't see any point of having it. If it needs to be hidden again, let me know.

**Comment by toshan2014** [comment]
stg : http://stage-ng.akc.org/author/liz-donovan/

**Comment by spaulenoff** [comment]
@toshan2014 still seeing featured article in weird format on http://stage-ng.akc.org/news/
![featured](https://cloud.githubusercontent.com/assets/13648969/14084856/ccfb5bc4-f4ea-11e5-9f8c-403ba94236d2.png)

**Comment by spaulenoff** [comment]
I was mistaken and this isnt verified on dev either

**Comment by toshan2014** [comment]
Please comment and move to stg verified after confusion about this ticket has been cleared up.

**Comment by toshan2014** [comment]
pf - featured article (with its bg img) showing on top as expected:
https://develop2.akc.org/author/liz-donovan/
https://develop2.akc.org/news/

**Comment by spaulenoff** [comment]
verified on pre-flight

**Comment by toshan2014** [comment]
verified on prod

**Comment by spaulenoff** [comment]
Verified on Prod
