### ISSUE TITLE
Start Google DFP discovery

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#134]

**Comment by kylejbertelsen** [comment]
Kickoff meeting 2016-04-06. Will re-evaluate after meeting.

**Comment by spaulenoff** [comment]
Ad Audit document https://docs.google.com/spreadsheets/d/1qzg2I9Y040IyGfEMbZZQEeVYMzd26BMdekmXGerxJZY/edit#gid=162269446

**Comment by kylejbertelsen** [comment]
@stevepessah -- I think it was you who mentioned that we have a free version of DFP for the moment -- if you could, please get me the login credentials and URL, so I can look over how the tags work.

**Comment by stevepessah** [comment]
@kylejbertelsen not I.. @elieo?

**Comment by kylejbertelsen** [comment]
Time tracking:

Kyle: 2016-04-07: 2 hours (tutorial videos, exploration of dfp site)

**Comment by elieo** [comment]
login: AKCram2@gmail.com
Password: Dixiejune24!

**Comment by spaulenoff** [comment]
@kylejbertelsen ^

**Comment by kylejbertelsen** [comment]
@elieo: URL?

**Comment by kylejbertelsen** [comment]
Okay, looks like it's going to be a bit of a pain in the butt, but in short, on an position-by-position basis, there will be javascripts to be copied from the DFP interface, and pasted into the page templates. Once we've determined what the positions are, and where they'll live, it could be done all at once.
