### ISSUE TITLE
Replace breed page UGC with new photo gallery module

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#135]
See also #163 

We're going to embed the new microsite photo gallery module onto the breed pages as a replacement for the UGC module. Below example is using the Czechoslovakian Vlcak.

A: Change H2 to "The Czechoslovakian Vlcak"
B: Add line of copy below H2 with padding-top: 10px. Line should say "Click here to view photos and videos from the Czechoslovakian Vlcak community" (should be editable in the CMS).
C: "Click here" should be hyperlinked to a new page, /dog-breeds/[breed]/pictures/ (example - http://www.akc.org/dog-breeds/czechoslovakian-vlcak/pictures/)

We plan to roll this out slowly so we need the ability to toggle this on/off.

The /pictures/ page should use the UGC/social aggregator module and built using the generic3 template (blank page with no sidebars). The breadcrumb should show as "Dog Breeds | Czechoslovakian Vlcak | Community" with the H1 being "The [breed] Community"

![screen shot 2016-03-30 at 12 28 16 pm](https://cloud.githubusercontent.com/assets/1063028/14149930/95617618-f674-11e5-8cc8-726de59c7efe.png)

**Comment by kylejbertelsen** [comment]
Note: 12 hour estimate is dependent on the gallery working precisely like the ones that are already a part of the Category Pages. If you want it to look/work like it currently does, I'll have to ask Toshan how long he thinks that would take.

**Comment by kylejbertelsen** [comment]
Clarification (on C above): 
1. replace UGC on breed page with Category-page-style gallery.
2. create a new page (/dog-breeds/$breedname/pictures/) which contains the pre-existing UGC.

Regarding the slow rollout, add a new (select/checkbox) field to the content type that toggles between using the Gallery or the UGC, defaulting to UGC.

Make sure there's a 'pictures' anchor link (< a name="pictures">< /a>) at the position of (A) on this page. See #163.

**Comment by toshan2014** [comment]
@spaulenoff Please confirm if we need all these fields: Photo     Slide Title     Slide Subtitle     Slide Content     Slide Date ( like in the Mayday photogallery ). I would think we just need Photo and Slide Title but please confirm.

**Comment by spaulenoff** [comment]
@toshan2014 Only Photo is needed. All other fields can be left out

**Comment by toshan2014** [comment]
@kylejbertelsen Please update config.master.php as follows:
`$env_config['structure_listing_subpages'] = array(
        'trigger_words' => array(
            'dog-breeds' => array('detail', 'care', 'pictures')
        )
    );`

**Comment by toshan2014** [comment]
@spaulenoff #B : "Click here to view photos and videos from the Czechoslovakian Vlcak community". This will contain html in one part ( "here") and dynamic data on another part- the breed title ("Czechoslovakian Vlcak" in this case). If this line is made editable in the CMS these data will have to be manually added - not a good idea in my opinion as it would be prone to errors - please confirm this choice.

**Comment by spaulenoff** [comment]
@toshan2014 This line no longer needs to be editable at this time. Please make so the Click Here is html and the rest of the line is dynamic based on the breed page

**Comment by toshan2014** [comment]
Please QA:

To create a new breed gallery:
Content > Edit > Breed > [Breed-Title] > Breed photogallery 

To toggle between UGC and gallery:
Content > Edit > Breed > [Breed-Title] > Show Breed Photogallery

**Comment by toshan2014** [comment]
Time spent: 9h

**Comment by spaulenoff** [comment]
@stevepessah I checked and I am seeing this as layed out above. please QA on Dev2:
http://develop2.akc.org/dog-breeds/beagle/
http://develop2.akc.org/dog-breeds/affenpinscher

**Comment by stevepessah** [comment]
@spaulenoff gallery looks good - is it possible to keep the URL as /dog-breeds/affenpinscher/ and only change the URL is the user engages with the gallery? Right now when you land on that page you hit /affenpinscher/?photo_id=0

**Comment by spaulenoff** [comment]
@toshan2014 Please confirm if you can make the change steve asked for in his comment

**Comment by toshan2014** [comment]
@spaulenoff - please check - http://develop2.akc.org/dog-breeds/affenpinscher/

Note: clear browser cache first

**Comment by toshan2014** [comment]
Time spent: +1.5h

**Comment by spaulenoff** [comment]
Verified on dev2

**Comment by toshan2014** [comment]
Stage: http://stage-ng.akc.org/dog-breeds/affenpinscher/

**Comment by toshan2014** [comment]
pf : http://develop2.akc.org/dog-breeds/beagle/

**Comment by skt2** [comment]
More information about moving or adding new UGC section: https://akcorg.atlassian.net/wiki/display/BEV/Load+UGC++on+a+new+section

**Comment by spaulenoff** [comment]
Verified on Prod

**Comment by skt2** [comment]
While using Photogallery and Video together, there is JavaScript conflict.
@toshan2014 please go ahead and add more details about it, either in ticket or as wiki page.

**Comment by toshan2014** [comment]
The conflict comes from JS file : "public_html/js/plugins.js"
If the slider gallery has to be added somewhere else, use the original JS meant for the slider which is: "public_html/js/slick.js"

**Comment by toshan2014** [comment]
Total time spent : 13h
