### ISSUE TITLE
Sitespeed: Research and Evaluate AMP Project

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#136]
Related to https://github.com/akcdotorg/akc.org/issues/76

https://www.ampproject.org/

**Comment by kylejbertelsen** [comment]
What are the benefits of this? What problems are we hoping to resolve by using this? Are there any competing solutions to the problems we're hoping to resolve, and how do those compare? 

These are the questions I should answer in this research.

**Comment by kylejbertelsen** [comment]
We'll need to find an alternative -- or a way to make this compatible with, for instance ce:image

**Comment by kylejbertelsen** [comment]
Incompatible with our needs. Closing.
