### ISSUE TITLE
Make photo required for articles/video/photo pages

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#137]
Ensure that the Thumbnail image field is required for articles/videos/photo gallery so that they don't get published without an image (which will display a large thumbnail without the image).

**Comment by spaulenoff** [comment]
@kylejbertelsen Who should I assign this to to work on and to add an estimate.

**Comment by skt2** [comment]
Time Spent: 1h

NOTE: Only CMS Changes. No Code changes so branch not created.

**CMS CHANGES**
CMS > Admin > Channel Admin > Channel Fields > Article/Media 
Edit thumbnail field > Is this a required field? to Yes

**Comment by spaulenoff** [comment]
Verified on dev2

**Comment by spaulenoff** [comment]
Verified on Production
