### ISSUE TITLE
Keep "Most Popular" as section title but filter in posts with most views instead of by date

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#138]
Related to #114 for Articles/Videos/Photo-Galleries

**Comment by spaulenoff** [comment]
@kylejbertelsen Can you please look over this ticket and confirm who this should be assigned to and an estimate?

**Comment by kylejbertelsen** [comment]
@skt2: please give me an estimate as to how long this will take. It remains to be seen whether the actual work will occur in this sprint -- but if we can, we should.

**Comment by skt2** [comment]
@kylejbertelsen Added. Approx. 3h

Time Spent: 6h

**Comment by skt2** [comment]
@kylejbertelsen This is taking longer then expected. Do you want me to continue exploring this? At this stage I am not sure how long it will take and even we will make it work or not.
Basically this is built-in EE feature which seems to be not working.
Database Table: exp_channel_titles
Reference Links:
https://docs.expressionengine.com/v2/add-ons/channel/entry_tracking.html
https://ellislab.com/forums/archive/viewthread/236863

**Comment by spaulenoff** [comment]
@elieo @stevepessah Please see Shailesh's comments above on why this ticket is taking longer than originally expected. Please advise on if you would like to keep this in the sprint or if you want to reevaluate this issue next week.

**Comment by toshan2014** [comment]
@spaulenoff Time spent fixing view-count : 6h

**Comment by toshan2014** [comment]
@kylejbertelsen  Please ensure we have the following values in 'config.master.php'  (/var/www/config-develop2/config.master.php): 
Note - $env_config['relaxed_track_views']         = 'y'; is a new variable

```
$env_config['dynamic_tracking_disabling']  = 'n';
$env_config['enable_entry_view_tracking']  = 'y';
    $env_config['relaxed_track_views']         = 'y';
```

**Comment by spaulenoff** [comment]
Seems to be working for me. Verified on dev2

**Comment by spaulenoff** [comment]
Verified on Prod
