### ISSUE TITLE
Assemble list of Pros & Cons of Expression Engine

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#140]

**Comment by kylejbertelsen** [comment]
Cons: 
- It's crap
- Can't trust even simple conditionals and variable setting/reading reliably
- It's very niche, and lacks community support
- Hard to find workers familiar with it

Pros:
- It's there, in-place, and much work has been done in it.

**Comment by stevepessah** [comment]
@kylejbertelsen let's keep this aside for now. There are other things we'll need you to help research into, such as https://github.com/akcdotorg/akc.org/issues/195

**Comment by kylejbertelsen** [comment]
@stevepessah: this ticket been just a notepad -- there hasn't been any research time poured into it, just jotting down observations as they come up.
