### ISSUE TITLE
Deep-linking to filtered Calendar views

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#146]
From Steve:

We’re looking into ways to drive more consumers to the Event Calendar (https://www.apps.akc.org/apps/event_calendar/index_mobi.cfm) but one of the limitations we’re encountering is that the URL doesn’t change when you select different event types, states, or dates. I was wondering how difficult it would be to update how this works so we can direct people to the correct portion of the calendar?

Notes: 

The resulting page has an iframe, in-which it's likely that we can use query-string parameters. We'll want to give Steve a way to assemble these parameters.

It's possible that there's an existing way to get to a permalink for a series of filters on the calendar. Ask ISD, or look at how it's done on AKCWinners.

The existing Event Calendar needs improvements to make it finding events more intuitive for consumers.
- Update URL structure to enable deep linking to specific event types, locations, and dates.
- Update search UI/UX
- Update calendar functionality
  - Calendar should always start on Sunday
  - Need to indicate the current date on the calendar
  - Add ability to toggle between calendar/list view
- Update event list
  - Update mobile functionality so when a date is selected from the calendar, we link to top of the list
  - Update map functionality to use Google Maps and input event location
  - Include CTAs to attend/register
  - Look into viability of including stock/webdam photo
- Include a link to glossary so consumers can start understanding the different terms we use
- Index event calendar on Google
- Color code different types of events/breed

Embed list of events on breed pages (widget)?

**Comment by stevepessah** [comment]
@kylejbertelsen for some more info, we'll want to send people to pages based on:
- Type of event
- Location of event (by state)
- Date range of events (ability to send people to all events taking place in May 2016 for example)

Let me know if you need any further details here.

**Comment by kylejbertelsen** [comment]
Note:

Example: Field Trials in Arizona, in June, 2016.

https://www.apps.akc.org/apps/event_calendar/index_mobi1.cfm?month=&year=&d
ay=&getEvents=Get+Events&mobile=Y&action=month&event_grouping=S&state=AZ

Options:

action:
action=month (show month calendar)
action=week (show week list)
action=day (show day list)

event_grouping:
CONF = AB and Group Conf.
OPNC = Open Show Conformation
BPUP = 4-6 Month Beginner Puppy 
S = Specialty
TRK = Tracking Events
LC = Lure Coursing TS/TR
CABT = Coursing Ability Test
OBED = Obedience Trials
FT = Field Trials
HT = Hunting Tests
HE = Herding Tests and Trials
CH = Coonhound Events
AG = Agility Trials
ED = Earthdog Tests
RLY = Rally Trials
FCAT = Fast Cat
MH = B Match

month, day, year: month, day and year desired, defaulting to current.

state: the postal code for a given state, defaulting to all

**Comment by kylejbertelsen** [comment]
We'll want to contact ISD about whether it's possible to send params to the page that loads the iframe, so the iframe can load with the submitted params.

**Comment by kylejbertelsen** [comment]
Wrote to Mickey Ledford, Jeff Utley on this on 2016-04-18

**Comment by stevepessah** [comment]
@kylejbertelsen if we bring this into the CMS we would need to support both versions of the calendar (desktop and mobile) in a full width page.

**Comment by kylejbertelsen** [comment]
All progress to-date is in branch AKC3-146, to be recreated in this next sprint.

**Comment by kylejbertelsen** [comment]
Let's pull this for now, until we know where this project is at on the ISD side. We just don't have the information we need in order to not flush this time down the toilet.

And, in fact, when we push ahead with this task, let's start a new ticket with the new requirements.
