### ISSUE TITLE
Add Button to SEO pages that links to Marketplace puppy search

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#148]
We want to add button that will link the SEO pages to the following URL on Marketplace:http://marketplace.akc.org/puppies 

These buttons need to be added on the following pages:
http://www.akc.org/dog-breeds/
http://www.akc.org/dog-breeds/best-dogs-for-apartments/
http://www.akc.org/dog-breeds/best-family-dogs/
http://www.akc.org/dog-breeds/best-guard-dogs/
http://www.akc.org/dog-breeds/best-dogs-for-kids/
http://www.akc.org/dog-breeds/hypoallergenic-dogs/
http://www.akc.org/dog-breeds/smartest-dogs/
http://www.akc.org/dog-breeds/hairless-dog-breeds/

![add button to seo pages](https://cloud.githubusercontent.com/assets/13648969/14084679/e98b6bae-f4e9-11e5-80e1-575fdd6dc68f.png)

**Comment by skt2** [comment]
Time Spent: 2h
Time Spent: 30m(7 Apr)
Time Spent: 30m(8 Apr)

@spaulenoff 
Similar template is used for Group, Size and Characteristic pages and according to the requirement we only want to show "Search For Puppies" button on "Characteristic page". 
however I am able to put condition for not to show buttons on "Group Pages" as the url is different for them but I didn't find any way to separate "Size Pages" and "Characteristic page" so showing button on  "Characteristic page" will by default show buttons on "Size Pages" as well.
Please advice how we want to proceed with this?

**Comment by spaulenoff** [comment]
@skt2 Confirmed to proceed

**Comment by spaulenoff** [comment]
@stevepessah This looked good to me but please QA on dev2 to confirm. On mobile and desktop:
http://develop2.akc.org/dog-breeds/
http://develop2.akc.org/dog-breeds/best-guard-dogs/
http://develop2.akc.org/dog-breeds/smartest-dogs/
http://develop2.akc.org/dog-breeds/hypoallergenic-dogs/
http://develop2.akc.org/dog-breeds/medium-sized-dogs/

**Comment by stevepessah** [comment]
@spaulenoff can we change the position of the button to the sidebar?

![pasted image at 2016_04_06 11_10 am](https://cloud.githubusercontent.com/assets/1063028/14324744/1857e7f8-fbf4-11e5-8211-8ad32e84c40c.png)

**Comment by spaulenoff** [comment]
@skt2 Can you please make this update?

**Comment by spaulenoff** [comment]
@stevepessah I am now seeing it like it shows on the mockup. However, On Mobile it now shows up at the bottom of the page, under the list of breeds. Should we move up the button on mobile?
http://develop2.akc.org/dog-breeds/best-dogs-for-apartments/

**Comment by stevepessah** [comment]
@spaulenoff mobile is fine to include it on the bottom, just needs to be moved up to be closer to the bottom tile.

**Comment by spaulenoff** [comment]
@skt2 Please make the update steve has mentioned. Can you also please move the button and sidebar down so that the top of the button, aligns with the top of the first tile on desktop?

**Comment by skt2** [comment]
![screen shot 2016-04-08 at 9 30 10 am](https://cloud.githubusercontent.com/assets/16002526/14385072/8c78f0cc-fd6c-11e5-97b5-d8bd14bdea17.png)

**Comment by spaulenoff** [comment]
@skt2 Looks good on desktop.

Can we remove the blank space highlighted below on the SEO page: EG. http://develop2.akc.org/dog-breeds/hypoallergenic-dogs/

![blankspace mobile](https://cloud.githubusercontent.com/assets/13648969/14385868/804ec93a-fd70-11e5-979b-d5962f847145.png)

**Comment by spaulenoff** [comment]
verified on prod
