### ISSUE TITLE
Mobile Footer tweaks

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#150]
#130 Subticket

Adjustments made to mobile footer, per feedback.
- Mobile Footer: ![mobile footer markup](https://cloud.githubusercontent.com/assets/13648969/14044710/f1035afe-f269-11e5-92aa-11dafc9859b0.png)

**Comment by spaulenoff** [comment]
@kylejbertelsen Updated notes:
![mobile footer updates 3 29](https://cloud.githubusercontent.com/assets/13648969/14116719/28fc961c-f5af-11e5-967e-596381efee5b.png)

**Comment by kylejbertelsen** [comment]
Altered color of Back-to-top

**Comment by spaulenoff** [comment]
@kylejbertelsen Colors are still different:

On Prod - #ff5f2d

On Develop - #bf692b

**Comment by kylejbertelsen** [comment]
Intentional. Limiting the color palette so there's fewer 'similar' colors.

**Comment by spaulenoff** [comment]
@aalattili Please add any notes you may have for the mobile footer updates

**Comment by spaulenoff** [comment]
@kylejbertelsen Footer notes from Aspire:
![home page dev - improper line appears on footer](https://cloud.githubusercontent.com/assets/13648969/14144416/947c13d2-f65d-11e5-9133-eb9a32765cf3.png)

@spaulenoff: can you explain the above? Would also like to know what device/browser the screen caps are from.

**Comment by AKCOsama** [comment]
Issues with iPad:
1. LHS Links are partially hidden                                                                                                                                          2. Caption Texts are overlapped                                                                                                         3. back to up hyperlink text appears improperly at buttom of footer                                                          4. Unneeded white space at buttom of the footer

see [Home Page dev - issues with footer at home page.png] snapshot:
![home page dev - issues with footer at home page](https://cloud.githubusercontent.com/assets/16208336/14144881/e4b4fa7e-f691-11e5-8255-2ac0885d2f24.PNG)
