### ISSUE TITLE
Desktop Footer Tweaks

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#151]
#130 Subticket

Tweaks to desktop-scaled footer, per feedback comments. Please add any feedback as comments below.

**Comment by spaulenoff** [comment]
@aalattili Please add any notes you may have for the desktop footer updates

**Comment by spaulenoff** [comment]
@kylejbertelsen Here are the footer notes in a zip:
[Footer issues.zip](https://github.com/akcdotorg/akc.org/files/195639/Footer.issues.zip)

**Comment by spaulenoff** [comment]
And if you need the notes in written form (on the footer testing results tab)
[Footer and Header Issues-Develop.xlsx](https://github.com/akcdotorg/akc.org/files/195645/Footer.and.Header.Issues-Develop.xlsx)

**Comment by AKCOsama** [comment]
1. 'Back up arrow div element' size develop = (100px X 74px) vs prod = (85.125px X 75.843px)                                     2. "Back To Top" hyperlink text appears improperly at buttom of footer                                                                                    3. 'Orange shorty container div element' size develop = (1441px X 74px) vs prod (1423px X 75.843px)  

see snapshots:

![back to top hyperlink text appears improperly](https://cloud.githubusercontent.com/assets/16208336/14146671/c3bc2872-f698-11e5-8763-20fb6fd65794.png)

![back up arrow div element size develop 100px x 74px vs prod 85 125px x 75 843px](https://cloud.githubusercontent.com/assets/16208336/14146694/d817392e-f698-11e5-8a68-a89acb122f0b.png)

![orange shorty container div element size develop 1441px x 74px vs prod 1423px x 75 843px](https://cloud.githubusercontent.com/assets/16208336/14146697/dfdbff46-f698-11e5-8e3e-8e5a4ec69837.png)

**Comment by spaulenoff** [comment]
Additional Aspire Feedback:
![copyright span element size develop 218 73px x 28px vs prod 269 98px x 34 29px](https://cloud.githubusercontent.com/assets/13648969/14176592/cd56cc52-f71f-11e5-918d-611e4618556f.png)
