### ISSUE TITLE
Desktop Header Tweaks

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#152]
#130 Subticket

Tweaks to desktop-scaled header, per feedback. Please add any feedback as comments below.

**Comment by spaulenoff** [comment]
@aalattili Please add your notes regarding desktop header regression testing

**Comment by spaulenoff** [comment]
@kylejbertelsen Also Here are the notes in a Zip:
[Header issues.zip](https://github.com/akcdotorg/akc.org/files/195637/Header.issues.zip)

**Comment by spaulenoff** [comment]
And if you need the notes in written form (on the header testing results tab)
[Footer and Header Issues-Develop.xlsx](https://github.com/akcdotorg/akc.org/files/195645/Footer.and.Header.Issues-Develop.xlsx)

**Comment by aalattili** [comment]
**Desktop issues (FF 45 & GC 49):**
1-  Gigya login pop up design is different than what's in prod GC & FF

2-  Search issues: Search links will be highlighted when hovering upon link (Search link is highlighted when hovering.jpg)
![search link is highlighted when hovering](https://cloud.githubusercontent.com/assets/12289479/14144668/f70f544a-f690-11e5-8086-055b3e6b57b9.jpg)

3-  Header is shifted to LHS (Header isnt centralized.jpg)
![header isnt centralized](https://cloud.githubusercontent.com/assets/12289479/14144711/28da6a3c-f691-11e5-8e21-dc3951247e66.jpg)

4-  Main nav issues:
    1.  Font size is smaller than what’s in prod
    2.  Main nav link doesn’t get highlighted when hovering upon sub link in main menu list
    3.  Improper spacing & margins
(Main nav issues.jpg) (Main nav issues-Improper spacing between columns.jpg)
![main nav issues](https://cloud.githubusercontent.com/assets/12289479/14144729/3f3bd702-f691-11e5-98c7-853d54a85bb5.jpg)
![main nav issues-improper spacing between columns](https://cloud.githubusercontent.com/assets/12289479/14144733/45e0e656-f691-11e5-9da8-93693496c229.jpg)

```
4.  links don’t get underlined when hovering the mouse upon the link (Main nav issues-Iink isnt underlined.jpg)
```

![main nav issues-iink isnt underlined](https://cloud.githubusercontent.com/assets/12289479/14144815/9a988104-f691-11e5-9296-b17bb109b40b.jpg)

```
5.  Main menu nav issues (Main nav hovering issues.avi):
    -   After hovering upon Main nav for the 1st time, menu will keep opening when moving the mouse anywhere under header
   -    Main nav menus will open even if search box is active/opened
```

(Note: i couldn't upload .avi file, you can find it in the attached zip folder)

```
6.  Browse all breeds drop lists (Main nav issues-Browse all breeds list issues.jpg):
   -    Font is light grey-color & size is smaller in develop compared to what's in prod
   -    Highlight/focusing in develop is brown-colored while orange-colored in prod
```

![main nav issues-browse all breeds list issues](https://cloud.githubusercontent.com/assets/12289479/14144844/b949b9ce-f691-11e5-9652-4b9961d0ea79.jpg)

5-  Logged in user-MY AKC menu nav issues:
    1.  User name is placed under the avatar instead of being aligned next to it form RHS (Logged in user-Username issues 1.jpg)
![logged in user-username issues1](https://cloud.githubusercontent.com/assets/12289479/14144860/d3f97642-f691-11e5-9359-525df0027488.jpg)

```
2.  Username will be highlighted when hovering upon it (Logged in user-Username issues 2.jpg)
```

![logged in user-username issues2](https://cloud.githubusercontent.com/assets/12289479/14144871/db727f18-f691-11e5-9439-5510a1a42299.jpg)

```
3.  Menu nav background color is different than what’s in prod
4.  Font color and size is different than what’s in prod
5.  Links don’t get underlined and change color when hovering upon them
6.  Arrows appear next to list title
7.  Improper spacing & margins
8.  Sign out link appears like button
```

(Logged in user-My AKC nav issues.jpg)
![logged in user-my akc nav issues](https://cloud.githubusercontent.com/assets/12289479/14144884/e7684f14-f691-11e5-84f6-804d32ad9460.jpg)

**Issues Applicable only on FF 45:**
1-  Search for something’ & ‘Search key words’ texts are almost hidden (FF-Text in search box is hidden.jpg)
![ff-text in search box is hidden](https://cloud.githubusercontent.com/assets/12289479/14144901/f6526b90-f691-11e5-9e38-df29bd1650e5.jpg)

**Issues Applicable only on GC 49:**
1-  ‘Search for something’ & ‘Search key words’ font style is different than what’s in prod (GC-Search box-Font style.jpg)
![gc-search box-font style](https://cloud.githubusercontent.com/assets/12289479/14144923/17119734-f692-11e5-9ead-30ce20a48e66.jpg)

**Comment by spaulenoff** [comment]
Additional Aspire Feedback:
![search and sign in links have different naming in develop](https://cloud.githubusercontent.com/assets/13648969/14176576/bb296cec-f71f-11e5-8fd7-e3c2efd72430.jpg)
