### ISSUE TITLE
Mobile Header Tweaks

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#153]
#130 Subticket

Mobile Header Tweaks, per feedback.

![mobile header top level markup](https://cloud.githubusercontent.com/assets/13648969/14046282/ca5e8aba-f276-11e5-8d28-922d823f03b9.png)

Subnav Markup: 

![mobile header subnav mark up](https://cloud.githubusercontent.com/assets/13648969/14046373/75ae1b42-f277-11e5-86ee-b22a02e4c220.png)

Sub subnav markup: 

![mobile header sub subnav mark up](https://cloud.githubusercontent.com/assets/13648969/14046449/01c26188-f278-11e5-965a-90739b42ad1f.png)

**Comment by spaulenoff** [comment]
@kylejbertelsen Second round of Feedback

Top Level Nav:
![mobile header top level nav 3 29](https://cloud.githubusercontent.com/assets/13648969/14119883/4f4d807e-f5be-11e5-97b4-8f6298cf6915.png)

Sub Nav:
![mobile header subnav fb3 29](https://cloud.githubusercontent.com/assets/13648969/14119888/566032da-f5be-11e5-9efd-6dc751b1854c.png)

Sub Sub Nav:
![mobile header sub subnav fb 3 29](https://cloud.githubusercontent.com/assets/13648969/14119894/5daf477e-f5be-11e5-8839-d13cd7955bd2.png)

**Comment by kylejbertelsen** [comment]
Updated.

**Comment by spaulenoff** [comment]
@aalattili Please add any notes you may have for the mobile header updates

**Comment by spaulenoff** [comment]
@kylejbertelsen Some notes from Aspire As well:
[Header issues.zip](https://github.com/akcdotorg/akc.org/files/195651/Header.issues.zip)

**Comment by aalattili** [comment]
1-  Sign in link is missing (Mobile-Missing sign in link.jpg)
![mobile-missing sign in link](https://cloud.githubusercontent.com/assets/12289479/14145796/7b66521c-f695-11e5-881d-5a22176fe2ae.jpg)

2-  Menu nav issues (Mobile-Menu nav issues.avi):
- Search- text is light grey-colored
  ![mobile-search-font color](https://cloud.githubusercontent.com/assets/12289479/14146499/160a5ab4-f698-11e5-8bb1-7af0ff9c01d1.jpg)
- Menu nav doesn’t show titles & sub links function improperly
  ![mobile-menu nav issues](https://cloud.githubusercontent.com/assets/12289479/14146497/12bfb19c-f698-11e5-8519-8e70a2927923.jpg)

(Note: can't upload .avi file, you can find it in the attached zip folder)

**Comment by kylejbertelsen** [comment]
Updated.

**Comment by spaulenoff** [comment]
Two more notes:
![open mobile header nav](https://cloud.githubusercontent.com/assets/13648969/14183654/549f94ae-f73f-11e5-90e6-4b8d4a03378a.png)

![closed mobile header](https://cloud.githubusercontent.com/assets/13648969/14183656/58f9e63a-f73f-11e5-8225-70a41953906d.png)
