### ISSUE TITLE
Right arrow is not centralized in /news/ and /akc-dog-lovers/ pages (Bottom Pagination)

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#154]
Right arrow is not centralized in /news/ and /akc-dog-lovers/ pages (Bottom Pagination)
http://www.akc.org/news/
http://www.akc.org/akc-dog-lovers/

![stage - right arrow](https://cloud.githubusercontent.com/assets/13648969/14149294/793f2be0-f671-11e5-91f1-f967669b64fa.jpg)

**Comment by toshan2014** [comment]
stg: http://stage-ng.akc.org/akc-dog-lovers/P8/

**Comment by toshan2014** [comment]
time spent : 20min

**Comment by toshan2014** [comment]
pf : http://stage-ng.akc.org/akc-dog-lovers/P8/

**Comment by toshan2014** [comment]
verified on prod - @spaulenoff please double check:
www.akc.org/akc-dog-lovers/

**Comment by spaulenoff** [comment]
Verified on Prod
