### ISSUE TITLE
Add Marketplace links on Find A Match Results Page

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#155]
We want to add marketplace search results links to the find a match results page: http://www.akc.org/find-a-match/results/

We want the design and functionality of the buttons to be the same as the buttons on the compare breeds results page: www.akc.org/find-a-match/compare-breeds/results/?breedcompare=79%7C193%7C96%7C167%7C251

Simple mockup of styling:
![find-a-matych results mockup marketplace](https://cloud.githubusercontent.com/assets/13648969/14178137/5711a74e-f727-11e5-8d50-067c482af000.jpg)

**Comment by toshan2014** [comment]
Please QA : http://develop2.akc.org/find-a-match/

**Comment by toshan2014** [comment]
Time: 30min

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev2. http://develop2.akc.org/find-a-match/results/

Looks good to me and functions properly
![dev2 new find a match marketplace links](https://cloud.githubusercontent.com/assets/13648969/14358967/6558c026-fcbd-11e5-96d8-d99c93500de4.png)

**Comment by stevepessah** [comment]
I'm not a big fan of the design.. what do you think?

**Comment by spaulenoff** [comment]
I think its fine as it is consistent with the design on the compare breeds app. If you want another design we can discuss and create a new ticket for the new design.

**Comment by spaulenoff** [comment]
Compare breeds results for comparison
![compare breeds results](https://cloud.githubusercontent.com/assets/13648969/14361758/7c8782a2-fcca-11e5-9f30-a279d6cf975b.png)

**Comment by stevepessah** [comment]
@spaulenoff true, ok. We'll have to re-look at that once we get a designer ;)

Verified on dev2.

**Comment by toshan2014** [comment]
stage : http://stage-ng.akc.org/find-a-match/results/

**Comment by toshan2014** [comment]
pf Please QA : http://develop2.akc.org/find-a-match/

**Comment by spaulenoff** [comment]
Verified on Prod
