### ISSUE TITLE
Add Marketplace Links to You vs Breed Page

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#156]
Can we add marketplace links and buttons to the you vs breed page similar to the mockup below:

http://www.akc.org/you-vs-breed/
![you vs breed find a puppy mockup marketplace](https://cloud.githubusercontent.com/assets/13648969/14178372/5185b828-f728-11e5-8801-049a6eaf6cd0.jpg)

Functionality of the button should be similar to the compare breeds results page and should obviously be dynamic based on the breed selected

Related to #155

**Comment by stevepessah** [comment]
Link needs to go to the /puppies page for the specific breed. Example for screenshot above would go to http://marketplace.akc.org/puppies/basset-hound

**Comment by toshan2014** [comment]
please qa: http://develop2.akc.org/you-vs-breed/

**Comment by toshan2014** [comment]
stg: http://stage-ng.akc.org/you-vs-breed/

**Comment by aalattili** [comment]
@spaulenoff
QA retesting passed on dev2 & stage across browsers (IE 11, GC 50 & FF 45) & devices (iPhone 6s plus & Samsung galaxy S6)

**Comment by toshan2014** [comment]
pf : http://stage-ng.akc.org/you-vs-breed/

**Comment by toshan2014** [comment]
Time spent: 3.5h ( this is not like other pages - the whole thing is handled with JS handlebars hence it took longer than estimate )

**Comment by toshan2014** [comment]
prod: http://www.akc.org/you-vs-breed/

**Comment by spaulenoff** [comment]
Not verified, don't see link when signed in
![image](https://cloud.githubusercontent.com/assets/13648969/15583528/2f7c588e-2344-11e6-9cea-a0125e059f5c.png)

**Comment by spaulenoff** [comment]
Now Verified on Prod
