### ISSUE TITLE
Remove Mobile Ads on Several Page Types

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#158]
We need to remove mobile ads on thew following page types (most pages with a left side rail on desktop).
Generic - http://www.akc.org/events/field-trials/pointing-breeds/gun-dog-championships/ (300x600 and 2 300x250s)
Generic2 -http://www.akc.org/downloadable-forms/ (300x600)
Browse All Breeds Page - http://www.akc.org/dog-breeds/ (300x600s and 300x250)
SEO Breed Pages - http://www.akc.org/dog-breeds/hypoallergenic-dogs/ (300x600 and 200x50)
Breed Feed - http://www.akc.org/dog-breeds/beauceron/ (bottom 300x250)
Event Category Overview - http://www.akc.org/events/ (300x600 and 300x250)
News Article - http://www.akc.org/news/macomb-kennel-club-vet-tech-scholarship/ (300x600 and 2 300x250)
AKC Dog Lovers - http://www.akc.org/akc-dog-lovers/golden-retrievers-playing-in-ocean/ (300x600 and 2 300x250)
Content Hubs - http://www.akc.org/content/westminster-dog-show/ (300x250)
Content Hub Article Pages - http://www.akc.org/content/dog-breeding/articles/ovulation-in-the-bitch/ (300x250)
Homepage - http://www.akc.org/ (320x50 at bottom of page)

https://docs.google.com/spreadsheets/d/1qzg2I9Y040IyGfEMbZZQEeVYMzd26BMdekmXGerxJZY/edit#gid=0

**Comment by kylejbertelsen** [comment]
Find examples of these, and discuss strategy with Kyle. We may want to delete the calls to the ads, or we may want to comment them out. If the former, lets add comments where the previous code was, ala 
`// removed 320x50 ad x19 on 2016-04-04`

**Comment by spaulenoff** [comment]
This is blocked by #160

**Comment by spaulenoff** [comment]
Temporary hold until Steve, Elie and Simon review

**Comment by spaulenoff** [comment]
Part of #134

**Comment by kylejbertelsen** [comment]
@spaulenoff @stevepessah @elieo -- please review by CoB today -- I'd like to make sure this gets assigned to a developer asap.

**Comment by spaulenoff** [comment]
Removing from #166 4/14 sprint and replacing with #170

**Comment by spaulenoff** [comment]
This will be resolved #173

**Comment by spaulenoff** [comment]
Closing as this will be resolved via #173
