### ISSUE TITLE
Project: Research ways to implement more ad units on mobile

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#159]
related to #158

**Comment by kylejbertelsen** [comment]
Suggestion: in the mobile top-nav, under the nav links.

**Comment by spaulenoff** [comment]
Blocked by #160

**Comment by spaulenoff** [comment]
Added recommendations on the following google doc on the 2 tab:
https://docs.google.com/spreadsheets/d/1qzg2I9Y040IyGfEMbZZQEeVYMzd26BMdekmXGerxJZY/edit#gid=29819941

**Comment by spaulenoff** [comment]
Related to #134
