### ISSUE TITLE
Research Front-End Lazy Loading for ads on Mobile

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#160]

**Comment by kylejbertelsen** [comment]
Ask questions.

**Comment by toshan2014** [comment]
@spaulenoff  Are we referring to a  way to implement ads with lazy loading on mobile **as opposed to how they are loading at the moment?**

**Comment by spaulenoff** [comment]
@toshan2014 Correct, We only want ads to load once the user scrolls down to that part of the page where the ads show

**Comment by elieo** [comment]
There are a couple open source solutions out there that I found: 
- https://github.com/krux/postscribe/ 
- https://github.com/madgex/lazy-ads
- http://jqueryad.web2ajax.fr/

**Comment by stevepessah** [comment]
@toshan2014 @spaulenoff @kylejbertelsen this should be done first before #158

**Comment by spaulenoff** [comment]
Blocking #158

**Comment by spaulenoff** [comment]
#158 is now blocked by this ticket

**Comment by spaulenoff** [comment]
Removing from 4/14 sprint
