### ISSUE TITLE
Research: Look into Minime removing timestamps from file name

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#161]
Related to #73

**Comment by kylejbertelsen** [comment]
Add link here to your minimee support-request as well. And add any notes you have so far.

**Comment by skt2** [comment]
https://devot-ee.com/add-ons/support/minimee/viewthread/15703

**Comment by skt2** [comment]
Please see reply on thread we have posted.

**Comment by kylejbertelsen** [comment]
@shailesh: when referring for information elsewhere, please summarize (in case that page goes away), and provide the link -- even if you've already provided the link elsewhere.

Example:

Please see reply on support thread we have posted. (https://devot-ee.com/add-ons/support/minimee/viewthread/15703)
The developer does not intend to provide this functionality for our version of EE. Possibly for the new/current version of EE.

**Comment by kylejbertelsen** [comment]
Time-tracking, Kyle: 
2016-04-06  -- 1 hour (researching, editing minimee plug-in)
2016-04-07 -- 1.5 hour (recreating minimee implementation from #73)

**Comment by kylejbertelsen** [comment]
Please ask Aspire to re-test. As of yesterday, the only places minimee was implemented was on /learn pages.

Testing: 
See smoketesting instructions: See https://akcorg.atlassian.net/wiki/display/BEV/smoketesting for instructions
When loading several kinds of pages, View Source, and find the js files listed between '' and ''
Open those files, and make sure they exist and have contents. Don't bother reading the actual contents -- they'll be fairly large, concatenated and minified -- what we're looking for is that they exist.

**Comment by spaulenoff** [comment]
@aalattili Please re-test stage per Kyle's instructions above.

**Comment by aalattili** [comment]
@spaulenoff , @kylejbertelsen  
This ticket was not tested since we are blocked by tunnel issues, all of the IP addresses listed in confluence are not accessable from our side.

**Comment by aalattili** [comment]
@spaulenoff , QA testing passed. js files exist and have content in all /learn pages on stage-ng.akc.org.

**Comment by spaulenoff** [comment]
Verified on Stage. @kylejbertelsen  please make sure this is pushed to develop2 as well

**Comment by kylejbertelsen** [comment]
Confirmed on pre-flight (stage)

**Comment by spaulenoff** [comment]
@aalattili Please retest on stage to confirm still working correctly

**Comment by AKCOsama** [comment]
@spaulenoff , QA testing passed. js files exists and have scripts in all learn pages on stage and working correctly
