### ISSUE TITLE
Breed Page In-Content Video

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#162]

**Comment by kylejbertelsen** [comment]
If this is the request Elie discussed earlier: set it up as a global variable (Template Manager), and they can be turned-on/off site wide right there.

**Comment by stevepessah** [comment]
@kylejbertelsen yes, here are the details:
- Ability to toggle on/off
- Mockup below (grey box between 'Learn More' and 'At-A-Glance')
  ![teads on breed pages](https://cloud.githubusercontent.com/assets/1063028/14218573/07af75c6-f823-11e5-9e4c-b2d1a719a555.png)

**Comment by spaulenoff** [comment]
@skt2 Please provide a time estimate

**Comment by skt2** [comment]
Time Spent: 3h(6th Apr)
Time Spent: 3h(8th Apr)

**Comment by skt2** [comment]
**CMS Changes**
CMS > Add-ons > Modules
Republic Variables > Install

CMS > Add-ons > Modules > Republic Variables
Add new Group if you want(I have added group name breed)
Add new variable:
Choose group: breed
Variable Name: rp-breed-pages-teads (started with rp, just to seprate from normal global variables)
Parse variable early: Yes (must set to yes)
Variable value: Yes/No (case-sensitive)

**Comment by spaulenoff** [comment]
@stevepessah This is working for me on dev2. Please QA. It will show up under the Learn More button like the mockup above
http://develop2.akc.org/dog-breeds/glen-of-imaal-terrier/
http://develop2.akc.org/dog-breeds/affenpinscher/

**Comment by spaulenoff** [comment]
@skt2 Now i am not seeing teads code on breed pages
Please check http://develop2.akc.org/dog-breeds/affenpinscher/

**Comment by spaulenoff** [comment]
I see the teads code in the source. Please push to stage so we can better test to see if the incontent is working correctly

**Comment by skt2** [comment]
It's working for me on: http://stage-ng.akc.org/dog-breeds/affenpinscher/

**Comment by skt2** [comment]
Added new add-ons: http://republiclabs.com/expressionengine/republic-variables

**Comment by skt2** [comment]
wiki: https://akcorg.atlassian.net/wiki/display/BEV/Teads

**Comment by spaulenoff** [comment]
Verified on Prod

**Comment by skt2** [comment]
How to turn On/Off variable:

Add-ons > Module > Republic Variable > Select > rp-breed-pages-teads
While Turning ON: 
Parse variable early: Yes
Variable value: Yes

While Turning OFF: 
Parse variable early: No
Variable value: No
