### ISSUE TITLE
/dog-breeds/[breedname]/pictures/ page

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#163]
This is related to #135 

We would like to include the following on this page:
- H1 copy (to be provided)
- New photo gallery module (separate from /dog-breeds/[breedname]/ gallery)
- UGC module below

**Comment by kylejbertelsen** [comment]
See toggle on #135. If set to UGC, redirect back to breed page at pictures anchor.

**Comment by toshan2014** [comment]
New page "/pictures" created. Example : http://develop2.akc.org/dog-breeds/affenpinscher/pictures/
This page has the following:
- Hero image
- Breadcrumb
- H1
- Photo Gallery
- UGC

Please QA : http://develop2.akc.org/dog-breeds/affenpinscher/pictures/

**Comment by toshan2014** [comment]
Time spent: 7h ( two things took longer than expected - 1. ads were not showing 2. this page is special as it lies underneath listing channel pages in Structure and it was initially impossible to create as there was no documentation of how to make such a page ) . Here's the doc I've created in case such new pages have to be built : https://akcorg.atlassian.net/wiki/display/BEV/Allow+the+creation+of+pages+underneath+listing+channel+pages+in+Structure

**Comment by spaulenoff** [comment]
@toshan2014 Some Notes:
When going to each slide, the URL change like so - http://develop2.akc.org/dog-breeds/affenpinscher/pictures/?photo_id=0, http://develop2.akc.org/dog-breeds/affenpinscher/pictures/?photo_id=1, http://develop2.akc.org/dog-breeds/affenpinscher/pictures/?photo_id=2.

This causes the title tag to disappear. can we make so ever slide as well as the ad and end car all have the same title tag and metadata as http://develop2.akc.org/dog-breeds/affenpinscher/pictures/
![image](https://cloud.githubusercontent.com/assets/13648969/14541138/73db92a6-0256-11e6-8c7b-c038c6a8de4f.png)

**Comment by toshan2014** [comment]
@spaulenoff please check again.

**Comment by spaulenoff** [comment]
@stevepessah I checked and I am seeing it outlined as above. Please Qa on dev2:
http://develop2.akc.org/dog-breeds/beagle/pictures
http://develop2.akc.org/dog-breeds/affenpinscher/pictures

**Comment by stevepessah** [comment]
@spaulenoff same note about the URL as in #135. Also:
- Can we change the H1 to "more photos of the AFFENPINSCHER"
- Add a header above the UGC for "the AFFENPINSCHER COMMUNITY"
- Update the breadcrumb to say "Pictures" instead of "Community"

**Comment by spaulenoff** [comment]
@toshan2014 Please make the changes outlined above and please confirm if first question is possible

**Comment by toshan2014** [comment]
@spaulenoff changes made - please check http://develop2.akc.org/dog-breeds/affenpinscher/pictures/

**Comment by toshan2014** [comment]
Time spent : +15min

**Comment by spaulenoff** [comment]
Verified on Dev2

**Comment by toshan2014** [comment]
Stage: http://stage-ng.akc.org/dog-breeds/affenpinscher/pictures/

**Comment by toshan2014** [comment]
pf : http://develop2.akc.org/dog-breeds/beagle/pictures/

**Comment by toshan2014** [comment]
Time spent : +1.5h (social aggregator fix)

**Comment by spaulenoff** [comment]
verified on prod
