### ISSUE TITLE
SEO page In-Content Video

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#164]
- Ability to toggle on/off for each specific page
- If page already has video, the in-content ad video should replace JW player video (should still be below text).
  ![e98b6bae-f4e9-11e5-80e1-575fdd6dc68f](https://cloud.githubusercontent.com/assets/1063028/14218596/35075b24-f823-11e5-8a66-8ebbe1a3780a.png)

**Comment by spaulenoff** [comment]
@skt2 Please provide a time estimate

**Comment by skt2** [comment]
Time Spent: 1h(4th Apr)
Time Spent: 5h(5th Apr)
Time Spent: 2h(7th Apr)
Time Spent: 2h(18th Apr)

**CMS Changes:**
CMS > Admin > Channel Field > SEO Pages > Create new Field
Field Type: Select Dropdown
Field Label: Use In-content Video Ad
Field Name: use_in_content_video_ad_seo_page
Populate the menu manually: 
Yes
No

**Comment by skt2** [comment]
Test Page: http://develop2.akc.org/dog-breeds/smartest-dogs/
Before you test this on any other breed page, please make sure SEO video field is empty.

**Comment by kylejbertelsen** [comment]
@skt2: I think you're misunderstanding this ticket, to wit:

> If page already has video, the in-content ad video should replace JW player video

To me, this means that the Teads video appears whether there's a JW player video or not -- that the ad _replaces_ the SEO video, when activated. @spaulenoff please confirm.

**Comment by spaulenoff** [comment]
@kylejbertelsen @skt2 I have spoke with Elie, and while it would be preferable to not remove the JW player videos, it is ok to have the incontent ad replace the JW player when incontent ads is set to yes. Please let me know if this needs any additional clarification

**Comment by skt2** [comment]
Replacing might be difficult and more time consuming since we already running in issues with this for styling and playing it consistent. I already spent double time on this and still while trying to fix style of in content video, it stops loading.

**Comment by kylejbertelsen** [comment]
We'll not replace it. If it's optional, we're not doing it.

**Comment by skt2** [comment]
Test link: http://develop2.akc.org/dog-breeds/hypoallergenic-dogs/

**Comment by spaulenoff** [comment]
I am seeing the code in the source code and intermittently seeing the ad appear. Please push to stage so we can see if that fixes the issue.

**Comment by skt2** [comment]
Working for me on: http://stage-ng.akc.org/dog-breeds/smartest-dogs/

**Comment by spaulenoff** [comment]
Its working on pages with videos, however, I am not seeing the incontent video play when there is no video http://stage-ng.akc.org/dog-breeds/hypoallergenic-dogs/

**Comment by skt2** [comment]
Example video: http://www.akc.org/news/ace-winner-inspires-creation-of-monument-to-honor-k-9-officers/

**Comment by skt2** [comment]
@spaulenoff if you can get support information for **teads** from @elieo then it would be great.

**Comment by skt2** [comment]
404: Teads 
https://rtd.tubemogul.com/upi/pid/42ypLGPB?redir=https%3A%2F%2Fsync.teads.tv%2Fum%3Feid%3D9%26uid%3D%24%7BTM_USER_ID%7D

REQUEST HEADER:
Host: rtd.tubemogul.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: image/png,image/_;q=0.8,_/*;q=0.5
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://sync.teads.tv/iframe?pid=46412&userId=4445c66b-a22d-45a6-a777-7fd77ba4aa22&1460482884350
Cookie: _tmid=-2600606693701112748
Connection: keep-alive

RESPONSE HEADER:
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 1283
Content-Type: text/html;charset=ISO-8859-1
P3P: CP="NOI DSP COR LAW PSAo PSDo IVAo IVDo OUR BUS UNI DEM"
Pragma: no-cache
Server: Jetty(7.0.1.v20091125)
access-control-allow-origin: *

redir:https://sync.teads.tv/um?eid=9&uid=${TM_USER_ID}

**Comment by skt2** [comment]
There are some support articles here but not much helpful: http://support.teads.tv/customer/en/portal/topics/569396-format---infeed/articles

**Comment by skt2** [comment]
Support email: http://support.teads.tv/customer/en/portal/emails/new - I have sent email for our problem.

**Comment by skt2** [comment]
wiki: https://akcorg.atlassian.net/wiki/display/BEV/Teads

**Comment by skt2** [comment]
Reply from teads support, which is very interesting:

I believe the issue on the page where the ad is not displaying is caused by the paragraph on the page being above the fold. Our unit needs to be below the fold in order to be activated. On the second page where the ad is working, there is video content as well, which pushes the paragraph below the fold, allowing our ad to serve. Does that make sense?

**Comment by elieo** [comment]
@skt2  @stevepessah @spaulenoff 

I suggest that we put the teads ad in middle of the content as shown below. @stevepessah  please let me know if you are okay with this. 

![image](https://cloud.githubusercontent.com/assets/1423008/14589028/5eabffa4-04a6-11e6-95e4-4437a91f8fb7.png)

**Comment by stevepessah** [comment]
@elieo that's fine for an ad spot placement but the Teads placement needs to be above the fold in order for it to work.

**Comment by elieo** [comment]
@stevepessah to clarify, the Teads ad unit needs to be *_BELOW *_the fold.  

I know this is confusing but Teads is different than our regular display ad units, in that it is a “user initiated ad”. (ie after the user scrolls, and ad unit displays). 

If you are okay with the Teads placement in my mockup, from a UX / Product perspective,  I recommend we move forward with it.

**Comment by spaulenoff** [comment]
@skt2 Please make this update on Stage ASAP. Once this is approved we will move stage to preflight.

**Comment by skt2** [comment]
For now it is playing after 2nd breed, the reason behind, this listing is in loop and somehow one of the expression engine functionality loop count doesn't seem to be working as expect so it is hard to specify condition after 3rd. I'll keep looking into this meanwhile.
Tested here: http://stage-ng.akc.org/dog-breeds/hypoallergenic-dogs/

**Comment by spaulenoff** [comment]
Verified on Stage.

**Comment by skt2** [comment]
Final replay from Teads support when I asked if there is way around to load ads before page fold:
"You are welcome. On that page there is really not a way around since the paragraph does not go below the fold. Part of our ad offering is that our units deliver to that location, so there is not too much we can do on our end. Let me know if you have any other questions."

**Comment by spaulenoff** [comment]
Verified on Prod
