### ISSUE TITLE
Event Calendar updates

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#165]
The existing Event Calendar needs improvements to make it finding events more intuitive for consumers.
- Update URL structure to enable deep linking to specific event types, locations, and dates.
- Update search UI/UX
- Update calendar functionality
  - Calendar should always start on Sunday
  - Need to indicate the current date on the calendar
  - Add ability to toggle between calendar/list view
- Update event list
  - Update mobile functionality so when a date is selected from the calendar, we link to top of the list
  - Update map functionality to use Google Maps and input event location
  - Include CTAs to attend/register
  - Look into viability of including stock/webdam photo
- Include a link to glossary so consumers can start understanding the different terms we use
- Index event calendar on Google
- Color code different types of events/breed

Embed list of events on breed pages (widget)?

**Comment by kylejbertelsen** [comment]
Pretty sure this would be a request for ISD. Let's discuss. I'm not opposed to us getting our feet wet with apps.akc.org by taking this over.
(In the future, should we go with our own custom-built Drupal, this would be a pretty easy lift to bring in and customize at-will)
