### ISSUE TITLE
Make Delegates Portal Login Page responsive on Mobile

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#167]
Currently the following page isn't responsive on mobile: http://www.akc.org/delegate/delegates-portal/

Prod
![image](https://cloud.githubusercontent.com/assets/13648969/14330050/9c4a1956-fc0c-11e5-97f9-6b8e5f52b95e.png)

Dev2
![image](https://cloud.githubusercontent.com/assets/13648969/14330096/e31b7276-fc0c-11e5-98af-7a8006c06fe3.png)

Can we make this responsive responsive. Related to #11

**Comment by toshan2014** [comment]
@kylejbertelsen 
My understanding : Make Delegates Portal page coherent with other pages on mobile
Estimate : 3h

**Comment by skt2** [comment]
@spaulenoff: is there any markup for this or simply make it like this:
![screen shot 2016-05-05 at 4 25 05 pm](https://cloud.githubusercontent.com/assets/16002526/15056118/1c4ed8fc-12de-11e6-8537-5c018435217f.png)

**Comment by spaulenoff** [comment]
Simply make it like mockup above

**Comment by skt2** [comment]
Time spent: 2h 30m

**Comment by aalattili** [comment]
@spaulenoff 
QA testing passed on dev2 & stage, tested on iPhone 6s & Samsung S6

**Comment by spaulenoff** [comment]
Verified on Prod
