### ISSUE TITLE
/Register page optimization

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#17]
https://akcorg.atlassian.net/browse/AKC2-536

**Comment by spaulenoff** [comment]
Attached redesign has been approved by Jasey Day, Keith Fraser, Linda Duncklee, and Elie Orgel.
Goal is getting the key info and interactions higher up on the page, to reduce bounce rate and improve conversion into registration flow.
![image](https://cloud.githubusercontent.com/assets/13648969/13399017/29865448-decf-11e5-84fb-1bbdd633bca9.png)

![image](https://cloud.githubusercontent.com/assets/13648969/13399023/2f7d4320-decf-11e5-90c5-389ef385ca15.png)

**Comment by spaulenoff** [comment]
Beth Herbert: Simon Paulenoff What sprint is this a possible candidate for? 
cc Elie Orgel

**Comment by elieo** [comment]
@stevepessah  @spaulenoff We need mobile mockups.

**Comment by stevepessah** [comment]
@spaulenoff can you reach out to Beth for mobile mockups? Would be good to get them by EOW or early next week.

**Comment by stevepessah** [comment]
@elieo Beth is no longer working for us so this will need to wait until UX designer comes in.

**Comment by stevepessah** [comment]
Moved to JIRA
