### ISSUE TITLE
Article Page on microsite

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#170]
## Sample URLs:
- http://www.akc.org/content/dog-breeding/articles/tax-tips-for-dog-breeders/
- http://www.akc.org/content/entertainment/articles/9-photos-of-german-shepherds-to-brighten-your-day/
- http://www.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/
## Desktop
1. Remove top hero image and place it under the title of the article (this means we only have to create one image size rather than 3 - thumbnail, hero, social).
   - (Edi: SP) If OG image is not defined, use default OG image that is found on the rest of the site.
   - (edit: kb) No longer uses the category hero -- banner image now required in CMS, per sip
2. Add grey background behind ad unit at the top of the page that houses either a 970x66 or 970x250 ad unit (ad tag: x03)
   - If it's a 970x250, it should push the content lower
   -  (edit: kb -- Removed: If there is no ad, remove the whole grey area)
   - (edit: kb) uses same grey as jotform below, to limit the color palette. (#f5f5f5)
3. Add grey background behind the content on the right sidebar 
   - There should be 5px padding
   - (edit: kb) uses same grey as jotform below, to limit the color palette. (#f5f5f5)
4. Remove email capture module from the right sidebar for the whole template
   - 300x600 ad unit in the right rail should move with the user as they scroll down the page (makes the ad 100% viewable)
   - Should stop moving once the bottom of the ad hits the "Most Popular" section
## Mobile
1. 320x100 or 320x50 ad unit at the top (position: x10)
2. Hero image moved below article title
3. 300x250 ad unit in the article body (should show after the second `<p>` tag) (position: x35)
## General updates
- Dimensions needed for image need to be adjusted in CMS
## Screenshots

![article page update2](https://cloud.githubusercontent.com/assets/1063028/14362838/577dd20e-fccf-11e5-95b0-a9881ba66cae.png)
![article-page_layout_with_top_ad_-_regular_hero_image_-_moblile_-1](https://cloud.githubusercontent.com/assets/1063028/14363266/5d93b68e-fcd1-11e5-8567-ac12df8566d4.png)
![article-page_layout_with_top_ad_-_regular_hero_image_-_moblile_-2](https://cloud.githubusercontent.com/assets/1063028/14363269/6269ffb0-fcd1-11e5-962a-6bdf91fa278c.png)

**Comment by spaulenoff** [comment]
This is a high priority request that came from Elie, @kylejbertelsen Can you please review and add a time . We can discuss later today with @elieo, and @stevepessah

**Comment by spaulenoff** [comment]
@kylejbertelsen Please see the additional information you requested
1. Ad Calls - Desktop: Banner ad  (x03 728x90), Sidebar ads - x35(300x250), x37 (300x600)
   Mobile: Banner Ad - x10 (320x50), In content 300x250 - x35 (300x250)
2. This will only affect Article pages in the content hub
3. Sample URLs - http://www.akc.org/content/dog-breeding/articles/tax-tips-for-dog-breeders/, http://www.akc.org/content/entertainment/articles/9-photos-of-german-shepherds-to-brighten-your-day/, http://www.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/
4. Hero Image Size - 819x545 (needs to be responsive on mobile similar to how image within the content are reponsive on mobile)

**Comment by kylejbertelsen** [comment]
I fail to see how this is urgent enough to warrant breaking the cycle of our sprint, but in a moment of weakness I agreed to it, so I'll follow-through. However, this habit has to be broken: Next time, without a compelling business or technical reason, this would wait until the following sprint.

I don't want to rant, but this has the appearance of being a very ad-hoc change. Let's put together an actual plan. An actual road map. And then figure out how to best reach the goals we have. The days of changing things for the sake of change have to end sooner than later. Anything that can be justified can certainly be done, but we can't keep doing this without reasons.

**Comment by kylejbertelsen** [comment]
@spaulenoff: Regarding OptinMonster (#4 in screenshot), should that be removed throughout, or only for the /content article pages?

**Comment by spaulenoff** [comment]
I believe that should be removed on /content article, photo-gallery and video pages. @stevepessah and/or @elieo can you please confirm if there is anywhere else that the OptinMonster be removed?

**Comment by kylejbertelsen** [comment]
@spaulenoff Another complication: when there is no 'banner image' for an article, it defaults to the category hero. Either we have to make the banner image required, or we'll have to change the category hero. Decide quickly.

**Comment by spaulenoff** [comment]
@kylejbertelsen Banner image will be required

**Comment by kylejbertelsen** [comment]
CMS alterations:
Channel Fields > Article > Banner Image: change description to 'Large image for an article. Recommended Image Size 819x545' (not required)

**Comment by kylejbertelsen** [comment]
Time tracking:
2016-04-08: kjb: 3 hours
2016-04-11: kjb: 4 hours
2016-04-12: kjb: 4 hours
2016-04-13: kjb: 3 hours
2016-04-14: kjb: 1.5 hours

**Comment by spaulenoff** [comment]
@kylejbertelsen Please see notes for Desktop. Notes in bold/italicized. Will add notes for mobile after. http://develop2.akc.org/content/dog-breeding/articles/tax-tips-for-dog-breeders/
1. Remove top hero image and place it under the title of the article (this means we only have to create one image size rather than 3 - thumbnail, hero, social). 
- **_(Sip Notes) Please remove hero image altogether and have H1 title and Author directly above the content. Images should only be added within the WYGWAM._**
1. Add grey background behind ad unit at the top of the page that houses either a 970x66 or 970x250 ad unit (ad tag: x03)
- **_(SP Note) This is good_**
1. Add grey background behind the content on the right sidebar 
- **_(SP Note) This is Good_**
1. Remove email capture module from the right sidebar for the whole template
   - 300x600 ad unit in the right rail should move with the user as they scroll down the page (makes the ad 100% viewable) **(SP Note) Only 300x600 should follow you down page, not whole sidebar. Also the way it is now, the user can never see the bottom of the 300x600 unit. 300x600 unit should only follow you once the user scrolls to were the 300x600 is in the middle of the page.**
   - Should stop moving once the bottom of the ad hits the "Most Popular" section **_(SP Note) This is good but please remove grey area after ad unit stop following user_**

**Comment by spaulenoff** [comment]
## Mobile
1. 320x100 or 320x50 ad unit at the top (position: x10)
- **_(SP Note) This is Good_**
1. Hero image moved below article title
- **_(SP Note) This is Good_**
1. 300x250 ad unit in the article body (should show after the second `<p>` tag) (position: x35)
- _**(SP Note) This is Good**_

**Comment by spaulenoff** [comment]
# Tablet Notes
1. Can we remove the right ads sidebar on tablet?

# Desktop Notes
1. Can we please remove the hero image as we spoke about, as there may be pieces of content uploaded in the future that don't have hero images. Currently, articles without hero images show the default category hero in it's place.
2. Can we fix the issue where the ads overlap initially? 
   ![ads overlapping](https://cloud.githubusercontent.com/assets/13648969/14463319/8dd56e76-0098-11e6-99f7-3465aefb3220.png)

**Comment by kylejbertelsen** [comment]
Re (https://github.com/akcdotorg/akc.org/issues/170#issuecomment-208931429) 
Tablet #1 -- done. Hides when screen width between 625px and 970px
Desktop #1 -- no longer required, remains optional. Does not output unless defined.
Desktop #2 -- I think I have that nailed-down.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev2 on Mobile and Desktop. I went through first round of QA and on tablet. 
http://develop2.akc.org/content/dog-breeding/articles/tax-tips-for-dog-breeders/
http://develop2.akc.org/content/dog-breeding/articles/tips-for-success-with-fresh-chilled-semen-breedings/

**Comment by stevepessah** [comment]
## Desktop
- Ad needs to always be visible on the user's screen. There should not be able lag when the user scrolls, the ad should always be in view (goal here is to increase ad viewability).
- When you scroll to the top, the ad should not jump back to original placement (see previous comment)
- Ad needs to reach the bottom of the grey sidebar per initial comment (Should stop moving once the bottom of the ad hits the "Most Popular" section)

## Mobile
- Not seeing hero image on http://develop2.akc.org/content/dog-breeding/articles/tips-for-success-with-fresh-chilled-semen-breedings/

**Comment by spaulenoff** [comment]
@kylejbertelsen Please see Steve's comments above

**Comment by spaulenoff** [comment]
@kylejbertelsen Notes below:

## Desktop
- Ad needs to always be visible on the user's screen. There should not be able lag when the user scrolls, the ad should always be in view (goal here is to increase ad viewability). **Fixed**
- When you scroll to the top, the ad should not jump back to original placement (see previous comment) **Fixed**
- Ad needs to reach the bottom of the grey sidebar per initial comment (Should stop moving once the bottom of the ad hits the "Most Popular" section) **Still not seeing it reach the bottom of the gray side ad bar**

## Mobile
- Not seeing hero image on http://develop2.akc.org/content/dog-breeding/articles/tips-for-success-with-fresh-chilled-semen-breedings/ **Fixed**

New issue found on Mobile category/subcategory page, Ticket added #189

**Comment by kylejbertelsen** [comment]
Slider now reaching bottom of column.

**Comment by spaulenoff** [comment]
@stevepessah Please check as i am now seeing the above issues resolved:
http://develop2.akc.org/content/dog-breeding/articles/john-buddie-on-his-highs-lows-and-the-legacy-of-tartanside-collies/
http://develop2.akc.org/content/dog-breeding/articles/tax-tips-for-dog-breeders/
http://develop2.akc.org/content/dog-breeding/articles/tips-for-success-with-fresh-chilled-semen-breedings/

**Comment by spaulenoff** [comment]
@kylejbertelsen Few Notes:

QA'd on:
http://stage-ng.akc.org/content/dog-breeding/articles/ovulation-in-the-bitch/
http://stage-ng.akc.org/content/dog-breeding/articles/tax-tips-for-dog-breeders/
http://stage-ng.akc.org/content/dog-breeding/articles/john-buddie-on-his-highs-lows-and-the-legacy-of-tartanside-collies/
http://stage-ng.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Desktop:**  (tested on windows 7 Chrome)
- 300x600 (x37) is not following user down page (working correctly on develop2)

**Mobile (iPhone 6):** (Tested on iOS 9 Safari)
- 300x250 (x35) ad is not placed correctly (it is currently on the bottom of the page between end of article and most popular in section. Should be after second `<p>` tag)
- Seeing "iOS Bounce" (didn't see on develop2)

**Tablet (iPad Mini):** (Tested on iOS 9 Safari)
- In portrait mode, not able to drag down to reveal footer
- Seeing "iOS Bounce" in portrait and landscape mode (didn't see on develop2)

**Comment by spaulenoff** [comment]
All of the above now seem to be fixed. Verified on Stage. Can you just please update the CMS field with the new recommended hero image info (778px X 585px). All add in "if left blank, article content will be moved up to take its place" or something like that. 

-- DONE, kjb

**Comment by elieo** [comment]
@stevepessah  @pps2010 

I just checked in on this, and I noticed that the top ad on mobile seems to be getting cut off on the bottom. ( I check my iphone and mobile version on inspect elements) 

# currently looks like this

![image](https://cloud.githubusercontent.com/assets/1423008/14588188/03da9596-0491-11e6-8fba-20fe985d7a50.png)

![image](https://cloud.githubusercontent.com/assets/1423008/14588202/715fe026-0491-11e6-89d8-d97709b39806.png)

# It should look like this:

![image](https://cloud.githubusercontent.com/assets/1423008/14588179/dc6fb31a-0490-11e6-990f-8fb5dc79cc40.png)

**Comment by spaulenoff** [comment]
@kylejbertelsen Please make this one update Elie outlined above.

**Comment by spaulenoff** [comment]
@kylejbertelsen Looks good except for one note on Mobile - seeing extra 300x250 on the bottom of the page under the most popular in section. Can we please remove on mobile? Looks to be x20

http://stage-ng.akc.org/content/dog-breeding/articles/ovulation-in-the-bitch/
http://stage-ng.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Comment by kylejbertelsen** [comment]
@spaulenoff: extraneous ad removed, confirmed on stage-ng.

**Comment by spaulenoff** [comment]
Verified on Preflight

**Comment by spaulenoff** [comment]
Verified on Prod
