### ISSUE TITLE
Implement new Author pages

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#171]
We'd like to create new Author pages for our writers on AKC.org
## Requirements
- Add schema.org to the page (http://www.seoskeptic.com/structured-data-for-author-pages-and-linked-snippets/)
- Articles from the /content/ and /news/ sections should be pulled into the Recent Posts section
- The Author's name in all content pages (articles, videos, and photo gallery pages) should link to their respective Author page
- Author description should be a wygwam so we can include links
- If there is no job title for author, remove that field (job title is right below name)
- If the author does not have a link for their social media (FB, Twitter, Google+) then remove the button
## Desktop and Mobile wireframes

![author pages](https://cloud.githubusercontent.com/assets/1063028/14442848/f0b8a8e4-0009-11e6-8be9-cdb034d965ab.jpg)
![author pages 2](https://cloud.githubusercontent.com/assets/1063028/14442871/12f1ce7c-000a-11e6-9ffa-311be8e0e009.jpg)

**Comment by toshan2014** [comment]
@stevepessah 
Will that wireframe content be replacing the existing Author pages:
ex http://www.akc.org/author/Phil%20Guidry/

**Comment by stevepessah** [comment]
@toshan2014 yes this will replace the existing page.

**Comment by spaulenoff** [comment]
Mooved to Jira
