### ISSUE TITLE
Rearrange mobile ad layout

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#173]
Will create subtickets for each page type. This will only be for mobile layouts. Related to #158, #159 and #160 

These changes will **_ONLY_** be made to **_MOBILE_** page layouts

Google Doc:https://docs.google.com/spreadsheets/d/1qzg2I9Y040IyGfEMbZZQEeVYMzd26BMdekmXGerxJZY/edit#gid=721441786

**Comment by spaulenoff** [comment]
**Sub-Tickets:**
1. #174 Homepage
2. #175 Breed Page
3. #176 Breed Detail Page
4. #177 Breed Care Page
5. #178 Browse all Breeds Pages
6. #179 Breed SEO Pages
7. #180 Events Category Overview
8. #181 Generic 1 Pages
9. #182 Generic 2 Pages
10. #183 Content Hub Video Pages
11. #184 /News/ and /Akc-dog-lovers/ article pages
12. #185 Compare Breeds Results Page
13. #186 You vs Breed Page
14. #187 Find A Match Pages

**Comment by spaulenoff** [comment]
Total Estimated time for this ticket is around 20 hours after adding up estimates from subtickets

**Comment by elieo** [comment]
@stevepessah  @spaulenoff  

We need to figure out if we want to do this now, or when we move to DFP.  @spaulenoff  let's reach out to Yourbow and figure out the ads tags we will need for this.

**Comment by toshan2014** [comment]
@spaulenoff @elieo 

**ISSUE: An ad can only be called once per page**

The same ad cannot be used in two different positions on the same template.
Example (referring to #174 Homepage):  When i use say x11 for desktop and mobile in two different positions, it would only display in one position - Whichever position is higher in the html ( meaning once it gets called, it does not get called a second time ). 

One possible solution would be:
Use other ads of the same sizes **if available** (ex. use x35 instead of x11 for mobile in  #174).

**Comment by spaulenoff** [comment]
@toshan2014 I am ok with this solution

**Comment by toshan2014** [comment]
@spaulenoff 

The suggested solution will work for #174 - I will only be able to let you know if there will be alternative ads for the other tickets as I work through them.

Also please note that time-wise it will be a bit more time costly with the new solution.

**Comment by kylejbertelsen** [comment]
Make sure that any ad documentation is updated whenever you change which positions go on which pages.

**Comment by toshan2014** [comment]
@spaulenoff 

please confirm which type of ad is preferred under the hero/unhero  image. Either with margin or without. See screenshots:

<img width="404" alt="ad-margin" src="https://cloud.githubusercontent.com/assets/6847220/14749893/e7a5606a-0876-11e6-855e-0bf009b9da8a.PNG">
<img width="385" alt="ad-no-margin" src="https://cloud.githubusercontent.com/assets/6847220/14749896/e9683116-0876-11e6-93b1-6acf89aae5d0.PNG">

**Comment by spaulenoff** [comment]
@elieo @stevepessah Please confirm which option you would rather use. I personally like without the margin

**Comment by stevepessah** [comment]
@spaulenoff let's do the second option without margin.

**Comment by spaulenoff** [comment]
@toshan2014 see above

**Comment by toshan2014** [comment]
Please QA
Time spent ( all sub-tickets ) : 18h

**Comment by toshan2014** [comment]
All sub-tickets in pre-flight

**Comment by toshan2014** [comment]
Time spent : +9h ( due to issues with some ads not showing up for no apparent reason on stage )
Total: 27h
