### ISSUE TITLE
Mobile Homepage Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#174]
# Subticket of #173

http://www.akc.org/

Changes:
1. Add 300x250 (x11) between featured Breeds and Featured Stories
2. Remove 320x50 (x10) at very bottom of page

**Ads that will be on the page after change**: x11, x01 (Both run on mobile and desktop)

Mockup:
![homepage new mobile ads](https://cloud.githubusercontent.com/assets/13648969/14494147/4cbb7d44-0157-11e6-99f8-f1f5d8e88e78.png)

**Comment by toshan2014** [comment]
Please QA : http://develop2.akc.org/

Mobile Ad units on page: x01,x35

Time: 1.5h

**Comment by spaulenoff** [comment]
Looks good just one note:
![mobile homepage ads edit1](https://cloud.githubusercontent.com/assets/13648969/14716903/0e52ff0c-07bd-11e6-8bf5-efb8ea60a3a7.png)

**Comment by toshan2014** [comment]
please check again

**Comment by AKCOsama** [comment]
@toshan2014 @spaulenoff what is the range of screen sizes to be applicable on mobile?

**Comment by toshan2014** [comment]
@AKCOsama @spaulenoff I've noticed that the range that Mayday used and the one that was on the site initially are different. The one from Mayday is more uptodate as it caters for the Iphone 6Plus. I've made the range uniform (using Mayday's range) on the site (max-width 767px) but let's discuss it further in the scrum. 

@AKCOsama do you see any issues with the new range?

**Comment by AKCOsama** [comment]
@toshan2014 , Ads don't show up on mobiles/tablets which have screen resolution grater than or equal  962 x 601px, so that because the max-width is 767px?

**Comment by toshan2014** [comment]
@AKCOsama - as from 768px it's changes tablet mode

**Comment by toshan2014** [comment]
@spaulenoff please QA on stage:  http://stage-ng.akc.org/

**Comment by toshan2014** [comment]
pf : http://stage-ng.akc.org/

**Comment by toshan2014** [comment]
prod: http://www.akc.org/

**Comment by spaulenoff** [comment]
Verified on Prod
