### ISSUE TITLE
Mobile Breed Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#175]
Subticket of #173

http://www.akc.org/dog-breeds/labrador-retriever/

Changes: 

Move bottom 300x250 (x12) from bottom of page to inbetween the at a glance section and the breed standard section

**Ads that will be on the page after change**: x10, x12, x01 (runs on both mobile and desktop), x11 (runs on both mobile and desktop)

Mockup: http://elieorgel.com/wp-content/uploads/2016/04/Breed-page-mobile.png

**Comment by toshan2014** [comment]
Please QA : http://develop2.akc.org/dog-breeds/beauceron/

Time : 1.5h

**Comment by spaulenoff** [comment]
@toshan2014 I am seeing the ad in emulation but not on the actual device. Can you please check browserstack?
http://develop2.akc.org/dog-breeds/beauceron/
http://develop2.akc.org/dog-breeds/collie/

**Comment by toshan2014** [comment]
#175
@spaulenoff I can see it on emulator, my mobile and browserstack. Please check again, could have been cache on the site, which I just cleared again. 

<img width="403" alt="mobile-ad-detail" src="https://cloud.githubusercontent.com/assets/6847220/14722777/2e4bb5c4-07c2-11e6-9e62-30d4c5da12de.PNG">

**Comment by spaulenoff** [comment]
seeing it now

**Comment by aalattili** [comment]
@spaulenoff, 
Testing was applied on iPhone 6 plus
1-    Empty Ad box between ‘at glance’ section & ‘the breed standard’ (empty Ad box.PNG)
![empty ad box](https://cloud.githubusercontent.com/assets/12289479/14783683/ebc07e2a-0af9-11e6-968a-a56902759b29.PNG)

2-  Landscape, Ad at top page gets smaller and not centralized (Ad gets smaller in Landscape.PNG)
![ad gets smaller in landscape](https://cloud.githubusercontent.com/assets/12289479/14783700/04395cb0-0afa-11e6-9ab7-72633cccb8a5.PNG)

3-  Ad in ‘Care’ section is not centralized in Ad box (Ad is not centralized.PNG)
![ad is not centralized](https://cloud.githubusercontent.com/assets/12289479/14783649/c4d5444e-0af9-11e6-8317-c66724e42182.PNG)

**Comment by toshan2014** [comment]
stage: http://stage-ng.akc.org/dog-breeds/beauceron/

**Comment by aalattili** [comment]
QA retest failed on both dev2 & stage-ng.
- The Ad box under “at a Glance” section is still empty
- Ads still not centralized

**Comment by spaulenoff** [comment]
@toshan2014 Please resolve above. It seems the first issue is only occurring on iphone 6plus (and 6s plus)

**Comment by toshan2014** [comment]
@spaulenoff Are you OK using a 300x50 ad instead. There might be a limit to the amount of 300x250 ads which could explain it not showing at all times. Not 100% sure though. We can inquire with the ad agency to know the exact cause

**Comment by spaulenoff** [comment]
Use the 300x50 for now and we can discuss this more later

**Comment by toshan2014** [comment]
x09 seems to be working better -
pf:
http://stage-ng.akc.org/dog-breeds/collie/

**Comment by spaulenoff** [comment]
Verified. Please add a note as to why we changed ads here

**Comment by toshan2014** [comment]
x12 (300x250) replaced by x09 (300x50) as x12 was not displaying for no apparent reason. I can only suspect a limit to the amount of ads of a specific size per page given we are already using three 300x250 on that page. 
This however need to be verified with ad supplier.

**Comment by toshan2014** [comment]
Time spent: +1.5h ( due to above issues )
Total : 3h

**Comment by toshan2014** [comment]
prod: http://www.akc.org/dog-breeds/labrador-retriever/

**Comment by spaulenoff** [comment]
Verified on Prod
