### ISSUE TITLE
Mobile Breed Detail Page Ad Redsign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#176]
Subticket of #173

http://www.akc.org/dog-breeds/welsh-springer-spaniel/detail/

Changes:
Add 300x250 (x01) in between top orange section and history section

**Ads on page after change**: x01 and x09

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/Breed-Detial-Page-Mobile.png

**Comment by toshan2014** [comment]
Please QA: http://develop2.akc.org/dog-breeds/welsh-springer-spaniel/detail/

Mobile ad units: x01 and x09

Time spent: 20min

**Comment by toshan2014** [comment]
stage: http://stage-ng.akc.org/dog-breeds/welsh-springer-spaniel/detail/

**Comment by toshan2014** [comment]
pf: http://stage-ng.akc.org/dog-breeds/welsh-springer-spaniel/detail/

**Comment by toshan2014** [comment]
prod: http://www.akc.org/dog-breeds/welsh-springer-spaniel/detail/

**Comment by spaulenoff** [comment]
Verified on Prod
