### ISSUE TITLE
Mobile Breed Care Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#177]
Subticket of #173

http://www.akc.org/dog-breeds/pointer/care/

Changes:
Add 300x250 (x01) between top orange section and second purple section

**Ads on page after change**: x01 and x09

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/Breed-Care-Page-Mobile.png

**Comment by toshan2014** [comment]
Please QA : http://develop2.akc.org/dog-breeds/pointer/care/

**Comment by toshan2014** [comment]
Time spent: 1h

**Comment by toshan2014** [comment]
stage: http://stage-ng.akc.org/dog-breeds/pointer/care/

**Comment by toshan2014** [comment]
pf : http://stage-ng.akc.org/dog-breeds/pointer/care/

**Comment by toshan2014** [comment]
prod: http://www.akc.org/dog-breeds/pointer/care/

**Comment by spaulenoff** [comment]
Verified on Prod
