### ISSUE TITLE
Mobile Browse All Breeds Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#178]
Subticket of #173

http://www.akc.org/dog-breeds/

Changes: 
1. Add 320x50 (x10) at top of the page between unhero and hero title
2. Add 300x250 (x01) inbetween first and second tile
3. Remove ads at bottom of page (x01 and x05)

**Ads on page after change**: x01 (runs on mobile and desktop) and x10

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/Main-SEO-Breed-Page-Mobile.png

**Comment by toshan2014** [comment]
Please QA : 
http://develop2.akc.org/dog-breeds/
http://develop2.akc.org/dog-breeds/?letter=B

Mobile ad units: x10, x35

Time spent: 2.5h

**Comment by AKCOsama** [comment]
@toshan2014 @spaulenoff : 
There is no ad located inbetween first and second tile. See missed ad.png snapshot:
![missed ad](https://cloud.githubusercontent.com/assets/16208336/14819277/0615ee24-0bca-11e6-8328-bff835d29ef2.png)

**Comment by spaulenoff** [comment]
@toshan2014 Please look into this

**Comment by toshan2014** [comment]
@spaulenoff please check

**Comment by toshan2014** [comment]
please check http://develop2.akc.org/dog-breeds/

**Comment by aalattili** [comment]
QA retesting passed on dev2

**Comment by toshan2014** [comment]
pf: http://stage-ng.akc.org/dog-breeds/

**Comment by toshan2014** [comment]
prod: http://www.akc.org/dog-breeds/

**Comment by spaulenoff** [comment]
Verifed on Prod
