### ISSUE TITLE
Mobile SEO Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#179]
Subticket of #173

http://www.akc.org/dog-breeds/best-dogs-for-apartments/

Changes: 
1. Add 320x50 (x10) at top of the page between unhero and hero title
2. Add 300x250 (x01) inbetween first and second tile
3. Remove ads at bottom of page (x01 and x05)

**Ads on page after change**: x01 (runs on mobile and desktop) and x10

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/SEO-Breed-Page-Mobile.png

**Comment by toshan2014** [comment]
Please QA: http://develop2.akc.org/dog-breeds/best-dogs-for-apartments/
Mobile ad units: x10, x35
Time spent: 30min

**Comment by spaulenoff** [comment]
@toshan2014 Close but can you please center the top banner on mobile SEO Pages?
http://develop2.akc.org/dog-breeds/smartest-dogs/
http://develop2.akc.org/dog-breeds/best-dogs-for-kids/

![center mobile banner seo pages](https://cloud.githubusercontent.com/assets/13648969/14743945/5a35365a-0872-11e6-8e82-913f3e40305f.png)

**Comment by aalattili** [comment]
@spaulenoff, Ad isn't centralized & doesn't have boarders
![ad doesn t have boarders](https://cloud.githubusercontent.com/assets/12289479/14783783/a9f2caf6-0afa-11e6-9af9-b3a4bc5a090a.PNG)

**Comment by toshan2014** [comment]
please check : http://develop2.akc.org/dog-breeds/best-dogs-for-apartments/

**Comment by AKCOsama** [comment]
@spaulenoff @toshan2014 :
Top ad (between unhero and hero title) is not centralized and has no boarder only in 'Browse All Breeds' page. See ad not centralized.png snapshot:
![ad not centralized](https://cloud.githubusercontent.com/assets/16208336/14819143/63dce9dc-0bc9-11e6-9612-c740be2c6893.png)

**Comment by toshan2014** [comment]
@spaulenoff please check

**Comment by spaulenoff** [comment]
not verified, i am now not seeing the 300x250 working correctly after the first tile. Could you maybe use another 300x250 ad tag?

**Comment by toshan2014** [comment]
@spaulenoff  Replaced x35 by x11 - that seems to be working well. Please verify:
http://develop2.akc.org/dog-breeds/best-dogs-for-apartments/

**Comment by spaulenoff** [comment]
This is now working correctly but now #178 is not working correctly. There seems to be a conflict between these pages

**Comment by toshan2014** [comment]
please check : http://develop2.akc.org/dog-breeds/best-dogs-for-apartments/

**Comment by toshan2014** [comment]
pf : http://stage-ng.akc.org/dog-breeds/best-dogs-for-apartments/

**Comment by toshan2014** [comment]
prod: http://www.akc.org/dog-breeds/best-dogs-for-apartments/

**Comment by spaulenoff** [comment]
Verifed on Prod
