### ISSUE TITLE
Mobile Event Category Overview Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#180]
Subticket of #173

http://www.akc.org/events/

Changes:
1. Add 320x50 (x10) at top of page between hero/unhero and hero title
2. Remove ads at bottom of page (x01 and x05)

**Ads on page after change**: x10

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/Events-Mobile.png

**Comment by toshan2014** [comment]
Please QA : http://develop2.akc.org/events/

Time spent: 25min

**Comment by toshan2014** [comment]
stg: http://stage-ng.akc.org/events/

**Comment by toshan2014** [comment]
pf : http://stage-ng.akc.org/events/

**Comment by toshan2014** [comment]
prod: http://www.akc.org/events/

**Comment by spaulenoff** [comment]
Verifeid on Prod
