### ISSUE TITLE
Mobile Generic 1 Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#181]
Subticket of #173

http://www.akc.org/public-education/
http://www.akc.org/public-education/canine-ambassador-program/about-canine-ambassador-program/

Changes:
1. Add 320x50 (x10) between hero/unhero and top h1 Title tag
2. Add 300x250 (x01) after first paragraph
3. Remove ads at bottom of the page (x01, x05, x11)

**Ads on page after change**: x10 and x01 (run on mobile and desktop)

Mockup:
![generic 1 new mobile ad design](https://cloud.githubusercontent.com/assets/13648969/14495603/2d41f4aa-015e-11e6-9cb2-028f61f01979.png)

**Comment by toshan2014** [comment]
Please QA : 
http://develop2.akc.org/public-education/canine-ambassador-program/about-canine-ambassador-program/
http://develop2.akc.org/public-education/

Time spent : 1.5h

**Comment by toshan2014** [comment]
stg:
http://stage-ng.akc.org/public-education/canine-ambassador-program/about-canine-ambassador-program/
http://stage-ng.akc.org/public-education/

**Comment by toshan2014** [comment]
pf:
http://stage-ng.akc.org/public-education/canine-ambassador-program/about-canine-ambassador-program/
http://stage-ng.akc.org/public-education/

**Comment by toshan2014** [comment]
prod:
http://www.akc.org/public-education/canine-ambassador-program/about-canine-ambassador-program/
http://www.akc.org/public-education/

**Comment by spaulenoff** [comment]
Verified on Prod
