### ISSUE TITLE
Mobile Generic 2 Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#182]
Subticket of #173

http://www.akc.org/downloadable-forms/
http://www.akc.org/events/nohs/nohs-finals/

Changes:
1. Add 320x50 (x10) between hero/unhero and content
2. Add 300x250 (x01) after first paragraph
3. Remove 300x600 (x05) at bottom of page

**Ads on page after change**: x10 and x01 (run on mobile and desktop)

Mockup:
![screenshot-www akc org 2016-04-13 10-03-10](https://cloud.githubusercontent.com/assets/13648969/14495898/5cb30d9a-015f-11e6-8f21-482a70b3b276.png)

**Comment by toshan2014** [comment]
Please QA:
http://develop2.akc.org/downloadable-forms/
http://develop2.akc.org/events/nohs/nohs-finals/

Time spent : 1.5h

**Comment by toshan2014** [comment]
stg:
http://stage-ng.akc.org/downloadable-forms/
http://stage-ng.akc.org/events/nohs/nohs-finals/

**Comment by spaulenoff** [comment]
@toshan2014 Not verified seeing 300x600 (x05) at the bottom of the page. This should have been removed

**Comment by toshan2014** [comment]
please check again on stg

**Comment by toshan2014** [comment]
pf:
http://stage-ng.akc.org/downloadable-forms/
http://stage-ng.akc.org/events/nohs/nohs-finals/

**Comment by toshan2014** [comment]
prod:
http://www.akc.org/public-education/
http://www.akc.org/events/nohs/nohs-finals/

**Comment by spaulenoff** [comment]
Verified on Prod
