### ISSUE TITLE
Mobile /News/ article and/Akc-dog-lovers/ article Dog Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#184]
Subticket of #173

http://www.akc.org/news/ace-winner-inspires-creation-of-monument-to-honor-k-9-officers/
http://www.akc.org/akc-dog-lovers/12-spring-essentials/

Changes:
Remove ads at bottom of page (x01, x05, x12)

**Ads on page after change**: x03, x11 , x09

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/mobile-news.png

**Comment by toshan2014** [comment]
Please QA : 
http://develop2.akc.org/news/ace-winner-inspires-creation-of-monument-to-honor-k-9-officers/
http://develop2.akc.org/akc-dog-lovers/12-spring-essentials/

Time spent: 15min

**Comment by toshan2014** [comment]
stg:
http://stage-ng.akc.org/akc-dog-lovers/12-spring-essentials/
http://stage-ng.akc.org/news/ace-winner-inspires-creation-of-monument-to-honor-k-9-officers/

**Comment by toshan2014** [comment]
pf:
 http://stage-ng.akc.org/akc-dog-lovers/12-spring-essentials/
http://stage-ng.akc.org/news/ace-winner-inspires-creation-of-monument-to-honor-k-9-officers/

**Comment by toshan2014** [comment]
prod:
http://www.akc.org/news/ace-winner-inspires-creation-of-monument-to-honor-k-9-officers/
http://www.akc.org/akc-dog-lovers/12-spring-essentials/

**Comment by spaulenoff** [comment]
Verified on Prod
