### ISSUE TITLE
Mobile Compare Breeds Results Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#185]
Subticket of #173

http://www.akc.org/find-a-match/compare-breeds/results/?breedcompare=125%7C166%7C37%7C177

Changes:
Add 320x50 (x10) between unhero and compare H1 tag (same format as compare breeds selection page: http://www.akc.org/find-a-match/compare-breeds/)

**Ads on page after change**: x10

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/compare_breeds_result_mobile_ads_1024.png

**Comment by toshan2014** [comment]
Please QA : http://develop2.akc.org/find-a-match/compare-breeds/results/?breedcompare=125%7C166%7C37%7C177

Time spent: 20min

**Comment by toshan2014** [comment]
pf:
http://stage-ng.akc.org/find-a-match/compare-breeds/results/?breedcompare=125%7C166%7C37%7C177

**Comment by toshan2014** [comment]
Time spent : +2.5h ( due to this not working on stg. Alternative calling method applied )
Total: 3h

**Comment by toshan2014** [comment]
prod  :  http://www.akc.org/find-a-match/compare-breeds/results/?breedcompare=125%7C166%7C37%7C177

**Comment by spaulenoff** [comment]
Verified on Prod
