### ISSUE TITLE
Mobile You Vs Breed Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#186]
Subticket of #173

http://www.akc.org/you-vs-breed/

Change:
Add 320x50 (x10) between orange box at top and the login to compare H1 tag

**Ads on page after change**: x10

Mockup:
![you vs breed mobile ads](https://cloud.githubusercontent.com/assets/13648969/14496741/2c018b1a-0162-11e6-85ed-181ad3c3389c.png)

**Comment by toshan2014** [comment]
Please QA : http://develop2.akc.org/you-vs-breed/
Time spent: 15min

**Comment by toshan2014** [comment]
stg:
http://stage-ng.akc.org/you-vs-breed/

**Comment by toshan2014** [comment]
pf:
http://stage-ng.akc.org/you-vs-breed/

**Comment by toshan2014** [comment]
prod: http://www.akc.org/you-vs-breed/

**Comment by spaulenoff** [comment]
Verified on Prod
