### ISSUE TITLE
Mobile Find a Match Pages Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#187]
Subticket of #173

http://www.akc.org/find-a-match/#slide1
http://www.akc.org/find-a-match/#slide2
http://www.akc.org/find-a-match/#slide3
http://www.akc.org/find-a-match/#slide4
http://www.akc.org/find-a-match/#slide5
http://www.akc.org/find-a-match/#slide6
http://www.akc.org/find-a-match/results/

Change:
Add 320x50 (x10) between the top "find a match"  and the line right above the slide

**Ads on page after change**: x10

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/find_a_match_mobile_ads_720.png

**Comment by toshan2014** [comment]
Please QA:
http://develop2.akc.org/find-a-match/

Time spent: 30min

**Comment by toshan2014** [comment]
pf : http://stage-ng.akc.org/find-a-match/

**Comment by toshan2014** [comment]
prod:
http://www.akc.org/find-a-match/

**Comment by spaulenoff** [comment]
Verified on Prod
