### ISSUE TITLE
JIRA wishlist

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#190]
Syntax Highlighter: https://marketplace.atlassian.com/plugins/jira.plugin.syntaxhighlighter.macro.syntaxplugin/versions#b175

To-Do List Custom Field:
https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.todolist/versions#b180

Some kind of notes plug-in would be good.

Anything that could collapse/hide comments on-click.

**Comment by stevepessah** [comment]
Shared with Seth, closing.
