### ISSUE TITLE
Implement new store landing page

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#191]
URL - www.akc.org/akc-store/

Design - https://drive.google.com/folderview?id=0BwbZVJbtZRI5TXVPeVU3NGViakk&usp=sharing

**Comment by spaulenoff** [comment]
Kyle will assign when ready

**Comment by spaulenoff** [comment]
@stevepessah Will provide today (4/25)

**Comment by stevepessah** [comment]
https://drive.google.com/folderview?id=0BwbZVJbtZRI5TXVPeVU3NGViakk&usp=sharing

@kylejbertelsen just making a note here that the top nav is missing on the mockup, but we should keep the same nav on this page.

**Comment by spaulenoff** [comment]
Related to #210

**Comment by kylejbertelsen** [comment]
@spaulenoff: Couple of things, please find out ASAP:
1. the included image is only 1280px wide -- is there a larger version available from whomever did this design? As big as possible would be good.
2. In the left and right columns, there are the icons: do each of those go to a specific link (if so, what are they), or should the left and right columns be linked as a whole to somewhere? If so, where?

**Comment by spaulenoff** [comment]
@stevepessah Please advise per Kyle's comments above

**Comment by stevepessah** [comment]
@kylejbertelsen 
1. the included image is only 1280px wide -- is there a larger version available from whomever did this design? As big as possible would be good.

**Yes, we are getting a new image also as Alexandra wanted a different one. Still getting this approved along with a couple other changes..**
1. In the left and right columns, there are the icons: do each of those go to a specific link (if so, what are they), or should the left and right columns be linked as a whole to somewhere? If so, where?

**Is it possible to make each icon/copy hyperlinked to a specific page? If so, let's do that and I can add the links directly into the CMS.**

**Comment by AKCOsama** [comment]
QA passed, Secondary Menu setted to 'No' and act as link instead of dropdown menu.

**Comment by stevepessah** [comment]
@kylejbertelsen see final approved mockup below. The nav should go on top of the grey area. Text in grey area should match AKC.org style.

[Store Landing Page2.pdf](https://github.com/akcdotorg/akc.org/files/246928/Store.Landing.Page2.pdf)

Image for landing page below (width is 2,122 px so it should be good to go - let me know if you need larger image):
![thinkstockphotos-483149369](https://cloud.githubusercontent.com/assets/1063028/14984427/9f96f9c6-1110-11e6-8150-be94ef238825.jpg)

**Comment by kylejbertelsen** [comment]
@stevepessah: if you can provide the URLs for each of the links here, I can fill 'em in. Otherwise, they'll have the href="#" until you fill 'em in later

**Comment by stevepessah** [comment]
@kylejbertelsen yes just keep them as placeholders now while I work with Elihn on the links. Can we make it so that we can add additional links below if we want or should we include that in a different request?

**Comment by kylejbertelsen** [comment]
Different request.

**Comment by stevepessah** [comment]
@spaulenoff can you add the above to a different ticket?

**Comment by kylejbertelsen** [comment]
Will require c&p of entry from dev2 to stage, stage to prod.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev2

**Comment by stevepessah** [comment]
@kylejbertelsen looks good, couple fixes:
- the grey bar should be full width and right up against the top white nav
- the content in the columns don't look like they're centered correctly
- mobile is not correct also, see [mockup](https://drive.google.com/file/d/0B44uj-KiCIEEWkJSeVItdzZsTm8/view?usp=sharing)

**Comment by kylejbertelsen** [comment]
Ah! I don't recall having seen the mobile mockup. My bad.

**Comment by spaulenoff** [comment]
Per Steve's comment above regarding additional links. #234

**Comment by AKCOsama** [comment]
@stevepessah @spaulenoff store is redirect to /akc-store on dev2 and doesn't on stg

**Comment by spaulenoff** [comment]
@stevepessah Please QA once again on dev2

**Comment by kylejbertelsen** [comment]
Time tracking:
2016-05-03: kjb - 4 hours
2016-05-04: kjb - 2 hours, mobile

**Comment by stevepessah** [comment]
@kylejbertelsen desktop looks good. On the mobile side can we add that same grey bar at top?

**Comment by stevepessah** [comment]
@spaulenoff can you also update the nav now so it doesn't have both of those tabs?

**Comment by spaulenoff** [comment]
Updated

**Comment by stevepessah** [comment]
@kylejbertelsen I'm actually still seeing the content in the columns not centered.

**Comment by kylejbertelsen** [comment]
Centering repaired, grey-bar at top abandoned per Steve.

**Comment by kylejbertelsen** [comment]
@stevepessah : we should probably have the URLs all filled-in before we release this page tomorrow. On the plus side, we've got the css in, so we could activate the page later in the day, if necessary.

**Comment by stevepessah** [comment]
@kylejbertelsen Elihn will be sending @spaulenoff the URLs directly in a couple mins.

**Comment by spaulenoff** [comment]
**Toys & Treats**
https://shop.akc.org/collections/woofipedia-packs 
backup link 
https://shop.woofipedia.com/collections/woofipedia-packs 

**Breed Specific Merchandise** 
https://shop.akc.org/collections/dog-breed-products 
backup link
https://shop.woofipedia.com/collections/dog-breed-products 

**Training & Books**
https://shop.akc.org/collections/dog-training-products 
backup link
https://shop.woofipedia.com/collections/dog-training-products 

**Puppy Products**
https://shop.akc.org/collections/puppy-products 
backup links
https://shop.woofipedia.com/collections/puppy-products 

**Gift Items**
https://shop.akc.org/collections/dog-breed-products 
backup link
https://shop.woofipedia.com/collections/dog-breed-products

**Comment by spaulenoff** [comment]
AKC Services
-   AKC Certified Pedigrees (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=PED&cde_product=PEDX04) 
-   DNA Testing (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=DNA) 
-   AKC Reunite Microchips (https://www.akcreunite.org/products/?utm_source=akc%20website&utm_medium=link&utm_campaign=microchips) 

AKC Reports
-   Breeder Reports (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=BRDR) 
-   Competitor Reports (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=COMP) 

AKC Products & Rule Book
-   Specialty Products (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=AKCSPC) 
-   Rules, Regulations & Sport Guidelines (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=RREGSGDS) 
-   AKC Title Patches (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=AKCPATCH) 

AKC Training Products 
-   AKC GoodDog! Helpline (https://www.apps.akc.org/apps/helpline/index.cfm) 
-   Books, DVDs and Training Guides (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=BOOK,VIDEOS) 
-   Canine Good Citizen Merchandise (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=CGC,STAR) 
-   Materials for CGC Evaluators (https://www.apps.akc.org//apps/store/index.cfm?view=category&cde_category=TMATRL)

**Comment by spaulenoff** [comment]
Added ticket #240 to fix mobile Layout
