### ISSUE TITLE
Research plan for Learning Management System, for Leslie

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#194]
for Leslie Fetzer:

Bridge by Instructure produces guided forms for Judging Operations, where the data is processed (how?) and shared with Legal.

Resources:

Articulate Storyline is a tool Leslie uses to produce the UX for questionnaires
Microsoft Form is a tool which does things similar to what we want
Tom Patterson has Bridge API information, and Jeff Utley has also done some preliminary research.

**Comment by spaulenoff** [comment]
Moved to Jira
