### ISSUE TITLE
Update <div id> in a few places to support Marketo Real Time Personalization

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#195]
We'd like to implement Marketo's Real Time Personalization so we can serve personalized content to users. In order to do this, we need to update the `<div>` to be unique so Marketo knows to put X content in Y spot.

I have outlined the spots we'd like to implement this in with a proposed `<div id>`.

**NOTE: We cannot use `<div class>` to do this. It must be `<div id>`.
## In Zone Campaign

(https://docs.marketo.com/display/public/DOCS/Create+a+New+RTP+In+Zone+Campaign)

**Home page**
- Top right teal box at the top of the page `<div id="top-right-teal">`
- Bottom right box at the top of the page `<div id="bottom-right-ad">`
- We will want to put this on the slideshow also, so we need to make sure the slideshow has `<div id=homepage-slideshow>` (@spaulenoff can you make a note in the slideshow ticket?)( @stevepessah  You mean #107?)
  edit kb: added id='homepage-slideshow' to this, and in ticket #107 

**Breed page**
- You vs. breed purple box towards top of page `<div id="breed-versus">`

For the below, we need to implement this using their [Rich Media Recommendation Engine](https://docs.marketo.com/display/public/DOCS/Enabling+the+Rich+Media+Recommendation+Engine)

**/content pages**
(e.g http://www.akc.org/content/dog-breeding/articles/tax-tips-for-dog-breeders/)
- Content recommendations below articles (the div id should equal the spot the content is)

**edit, kb:** These ones are contained by divs, so I have them as id="most-popular-(1-6)", as-requested.

**/learn pages**
(e.g. http://www.akc.org/learn/dog-health/top-100-girl-dog-names/)
- Related stories (the div id should equal the spot the content is)

**edit, kb:** The body is set in snip-learn-detail.snip, and the id is applied to the container for the loop:  id="learn-posts". If Marketo allows for using the id on an < article> item, we can apply it to those, instead.

**Category landing pages**
(e.g. http://www.akc.org/dog-owners/)
- News & Updates (the div id should equal the spot the content is)

**edit, kb:** the existing item named here is a < nav> item, not a < div>, so I added < div id="side-nav">< /div> just prior to < nav class="side-nav">. If Marketo doesn't require a < div> we can set the < nav. to id="side-nav" instead. Your call.

**Comment by stevepessah** [comment]
@kylejbertelsen could you give me a rough time estimate on this?

**Comment by stevepessah** [comment]
@kylejbertelsen below is the Marketo Real Time Personalization snippet. We currently have it running on production in the google tag manager, but not on stage. Can we add the below on stage? It should be the first script in the header (between the `<head></head>` tags).

```
<!-- RTP tag --> 
<script type='text/javascript'>
(function(c,h,a,f,i,e){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
 c[a].a=i;c[a].e=e;var g=h.createElement("script");g.async=true;g.type="text/javascript";
 g.src=f+'?aid='+i;var b=h.getElementsByTagName("script")[0];b.parentNode.insertBefore(g,b);
 })(window,document,"rtp","//sjrtp5-cdn.marketo.com/rtp-api/v1/rtp.js","americankennel");

rtp('send','view');
rtp('get', 'campaign',true);
</script>
<!-- End of RTP tag -->

```

[Documentation link](https://docs.marketo.com/display/public/DOCS/Deploy+the+RTP+JavaScript) if needed

**Comment by kylejbertelsen** [comment]
@stevepessah : in the description above, there is the phrase '(the div id should equal the spot the content is)' -- could you explain that?

Also "For the below, we need to implement this using their Rich Media Recommendation Engine" -- if I'm reading that correctly, all we need is the snippet from your comment of 04/19 @4:19PM, and the remainder falls to whomever is administering our Marketo integration. Is that correct?

**Comment by stevepessah** [comment]
@kylejbertelsen so the content is displayed in two rows of 3, so let's name them

1 2 3
4 5 6

So the div could be < div id="most-popular-1"> and so on.

Yes, that's correct.

**Comment by kylejbertelsen** [comment]
See my **edit, kb:** notes in the above comments for notes.

**Comment by kylejbertelsen** [comment]
Time-tracking:
2016-04-25 - kjb - 3 hours (research and implementation)

**Comment by spaulenoff** [comment]
@stevepessah Please verifiy on dev2

**Comment by stevepessah** [comment]
Elihn to verify this on 4/26.

**Comment by spaulenoff** [comment]
This is verified on Dev2

**Comment by spaulenoff** [comment]
@stevepessah @elieo Please QA on stage

**Comment by spaulenoff** [comment]
@stevepessah @elieo Please QA on Stage again (this time its preflight)

**Comment by stevepessah** [comment]
@spaulenoff verified on preflight.

**Comment by spaulenoff** [comment]
@stevepessah @elieo Can either of you or Elihn confirm they are seeing this on production now?
