### ISSUE TITLE
Add OAS Queries to Ad units on Content Hub

### ISSUE THREAD

**Issue by elieo** [akcdotorg/akc.org#197]
**Backgruond**
As we are going to be moving the content from the /learn section to the /content section. We need to add OAS queries to each one of the ad units so we can block off certain sections to advertisers. 

**Desired outcome**
We are looking to be able to block off ads based on any of the following:
- Content type (article, video, photogallery) 
- Category
- Sub Category 

**Recommendation**
i suggest that we create a field in the category page, so we can set the OAS query on a category / sub category level.

**Comment by elieo** [comment]
You can add multiple tag to an AOS query using the following> (& sign breaks up the keywords) 

OAS_query = 'events&conformation-dog-shows&getting-started-showing';

**Comment by kylejbertelsen** [comment]
Notes: 
Current OAS setup is in templates/snippets/default_site/snip-OAS-setup.snip
Category pages will be required.
In snip-OAS-setup, you'll need to load a category page to get the field Elie wants. ex: templates/default_site/embeds.group/.content-headers.html~213 ({exp:channel:entries channel="category_hero") 
You'll want to talk to Elie about a fallback position -- what if a page isn't one of the /content pages, or if there is no category page for the article.

**Comment by elieo** [comment]
We are doing this right now only for the content section, so we don't need to worry about this for anything else. 

Every piece of content will have a category so a fall back is not necessary. 

I would also like to add the article name in the OAS query. SO for each ad we would have the following OAS queries:

Page type, Category , Sub category, Article name 

Thanks

**Comment by skt2** [comment]
Thanks @elieo. Changes are on dev2, Please have look once you get chance. http://develop2.akc.org/content/westminster-dog-show/

**Comment by elieo** [comment]
@skt2  look like we are missing the sub category in the OAS query. 

![image](https://cloud.githubusercontent.com/assets/1423008/14785253/dea5c4e8-0ac7-11e6-9acd-5128abf6c6b7.png)

**Comment by skt2** [comment]
@elieo on article pages, I have generated OAS Query based on URL.

**Comment by skt2** [comment]
@elieo Added sub-category in the OAS Query, Please have a look.
Tested here: http://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Comment by elieo** [comment]
@skt2  this looks good.

**Comment by spaulenoff** [comment]
Verified on Prod

**Comment by skt2** [comment]
Total Time Spent: 4h
