### ISSUE TITLE
Implement new top banner for Sign Up, Login, Search

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#198]
Mockup below includes the following requirements:
- New top grey banner that needs to go on all AKC.org pages (including apps, so this will need to be coordinated).
- A Sign Up and Log In button, which should open the appropriate Gigya screen.
- A Search button next to Log In, which should include the current search functionality (search bar displays when clicked). The triangle that points to the Search button will need to be removed though.
- A new Shop tab

![new top nav](https://cloud.githubusercontent.com/assets/1063028/14654818/795075da-064d-11e6-8fee-3d0373c61206.png)

**Comment by spaulenoff** [comment]
Assign to Shailesh once description is added

**Comment by skt2** [comment]
Time Spent: 7h(20th Apr)
Time Spent: 1h(21st Apr)
Time Spent: 1h(22nd Apr)

@kylejbertelsen: do we want this in a way so that is available in common header wrapper as well or just for akc.org site?

**Comment by skt2** [comment]
@stevepessah: can you please confirm that this changes are only for desktop, we don't want to show top nav on mobile?

**Comment by skt2** [comment]
@stevepessah @spaulenoff: do we want to implement this on /learn page as well? It's different header and might take more time so if want to get rid of /learn in near future then better not to waste time in this.

**Comment by skt2** [comment]
New top grey banner that needs to go on all AKC.org pages (including apps, so this will need to be coordinated). -- Can you please explain "including apps"?

**Comment by stevepessah** [comment]
@skt2 this is something that needs to be coordinated with ISD that @spaulenoff can manage.

We're also phasing out the current /learn section so we don't need to place it on there.

**Comment by spaulenoff** [comment]
Just sent email to ISD. included @skt2 @stevepessah and @kylejbertelsen

**Comment by spaulenoff** [comment]
@skt2 Seeing all things except for the shop tab in the navigation. @stevepessah Can you please provide the URL that the Shop Tab should link to? or will this just be added via the CMS?

**Comment by stevepessah** [comment]
@spaulenoff the link will be added to the CMS once we have the proper URL. We should still be able to add the tab there with a link placeholder.

**Comment by spaulenoff** [comment]
@skt2 Please make sure Mobile doesn't change from what is currently on production. Otherwise, desktop functionality looks good.

**Comment by spaulenoff** [comment]
the URL will be akc.org/akc-store/

**Comment by aalattili** [comment]
@spaulenoff,
In Mobile web, sign in banner in develop2 is different than what's in prod site. (Mobile web-Sign in banner.png).
Tested on iPhone 6 plus & Samsung Tablet.

![mobile web-sign in banner](https://cloud.githubusercontent.com/assets/12289479/14782801/232227a2-0af4-11e6-8274-f63b546eb5f0.png)

**Comment by spaulenoff** [comment]
@skt2 Please make the change @aalattili outlined above

**Comment by aalattili** [comment]
QA passed in develop2.

**Comment by aalattili** [comment]
Stage-ng, Mobile web. 
1- Sign in banner is displaying as what's in desktop browsers
2- background isn't white
![stage-sign in banner](https://cloud.githubusercontent.com/assets/12289479/14817365/89a6e58c-0bbf-11e6-93fe-1ecbc4228ec2.PNG)

**Comment by skt2** [comment]
@aalattili on which device you tested this?

**Comment by aalattili** [comment]
@skt2 on both iPhone 6 plus & Samsung tablet

**Comment by skt2** [comment]
@aalattili I pushed fixed for this. you can test on dev2 and stage.

**Comment by aalattili** [comment]
@skt2, QA retesting passed on both dev2 & stage

**Comment by spaulenoff** [comment]
Verified on Prod
