### ISSUE TITLE
Kids Corner Games

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#2]
We need to make it so David Woo, Davis Alexis and team can upload and embed games on their kids corner pages. I have attached the scope of work [^Product Scope Document-Kids Corner Games.pdf]  as well as the game files themselves.

Please let me know if you can't open anything, and I will forward it to you via email.

[coloringbook_3(mass parameter beta).zip](https://github.com/akcdotorg/akc.org/files/147309/coloringbook_3.mass.parameter.beta.zip)
[Rally-word-search-game.zip](https://github.com/akcdotorg/akc.org/files/147310/Rally-word-search-game.zip)
[Product Scope Document-Kids Corner Games.pdf](https://github.com/akcdotorg/akc.org/files/147311/Product.Scope.Document-Kids.Corner.Games.pdf)

**Other Notes**

Kyle Recommendation: **OBSOLETE**
~~(1) akc.org side: Add a content-type which can take an URL and embed that URL into an iframe~~
~~(2) kids-corner side: request a new subdomain (max 2 servers, I'd think), onto which David can upload his micro-apps and provide a URL to be embedded into (1) above.~~
~~Reasoning: we don't allow our own developers to push things directly into production. If these micro-apps can be uploaded into a separate sandbox, we don't break our procedures and rules, and they can have the level of control they're looking for.~~

Note: no subdomain. We'll have these files uploaded to the CDN, presumably as 'Assets'
They'll need to upload them unzipped.

Simon Paulenoff to connect with ~~Mike Kleinberg~~ _Kyle_ about getting ~~a subdomain specifically for games~~ _workflow_ for David Woo to upload the games to.
Will embed games from this subdomain to new page type in CMS

**Comment by stevepessah** [comment]
@spaulenoff this is a critical one for the 4/28 push. If there are any issues with the timeline once we review, we need to discuss with Brandi/Davis.

**Comment by spaulenoff** [comment]
**Response from Davis and David:**
Game modules are hosted in my dropbox public folder. AKC’s server should host these files.
https://www.dropbox.com/sh/sine2woga1lzf6c/AAAdwz_jWEqk0H5WYwy5Z22Ta?dl=0

Currently, the games are within an iframe that is forced to appear in the full screen and the highest layer. The iframe method works ok on desktop, but it crops the game screen on the iphone and iPad. The simulator won’t show the cropping issue.

Link of games:
http://www.akc.org/kids-corner/kids-games/coloring-pages/herding-coloring-pages/shetland-sheepdog/

**Comment by kylejbertelsen** [comment]
Response to David and Davis' response: no. It'll be hosted on our CDN. I've got a process that you can use to get the files there, though. Incoming.

**Comment by kylejbertelsen** [comment]
Ready for feedback from Davis and David.

Instructions:
1. Go to Add-Ons > Modules > Assets > File Manager
2. Locate 'kids-corner' on left, control-click, select 'New subfolder'
3. Give subfolder a useful name (Use only letters, numbers and dashes in name. Capitalization counts, so be aware of your capitalization.) 
   For the rest of this example, we'll use 'coloring-book'
4. Locate and select 'coloring-book'. This makes 'coloring-book' your currently-active directory for uploads.
5. Read through the index.html you'll be uploading. Make sure that all resources used in that file are present. If they belong in subfolders, do not move them.
6. For each file in the base directory that you're uploading, click the 'Upload files' button, select your file, and upload.
7. For each subfolder in your directory, control-click and select 'New subfolder' to create that subfolder, and upload each file individually to that subdirectory. If there are subdirectories of your subdirectory, add those individually as well. For this example, I'm using 'coloringbook_3(mass parameter beta).zip', and am replicating that directory structure, and uploading each file in the same destination directory structure. It is important in this process that you follow the naming schemes of your upload, or the resulting upload may not work as expected.
8. Time to create your page. Content > Publish > Kids Corner to start a new entry.
9. Enter your title (and alter your URL title, if desired).
10. If you'd like some introductory text and/or following text, you may use the 'Before Embed' and 'After Embed' fields. Both are WYSIWYG fields, giving them the same capabilities as any Article.
11. For the 'Index Page' field, click 'Add File', and browse to the index.html file from step 5 above.
12. Save.
13. Open in browser. Make adjustments to iframe width and height to suit the content.
14. Adjust the 'iframe Width' and 'iframe Height' fields in the CMS to match your width and height from step 13 above.
15. Save and done.

sample output: http://develop2.akc.org/kids-corner/coloring-book/

**Comment by kylejbertelsen** [comment]
Time tracking:
2016-04-20 - kjb - 3 hours
2016-04-21 - kjb - 3 hours
2016-04-22 - kjb - 1 hour

**Comment by spaulenoff** [comment]
Awaiting feedback from David and Davis

**Comment by spaulenoff** [comment]
Talked to Davis and Brandy. They want to move forward with this in this push, and revisit with David after it is pushed.

**Comment by kylejbertelsen** [comment]
On stage: http://stage-ng.akc.org/kids-corner/coloring-book/
