### ISSUE TITLE
Content Hub Articles title tags not working

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#201]
Some new articles do not have working title tags and SEO:
http://www.akc.org/content/entertainment/articles/7-fun-things-to-do-with-your-dog-in-atlanta/
http://www.akc.org/content/entertainment/articles/7-fun-things-to-do-with-your-dog-in-dallas/
http://www.akc.org/content/entertainment/articles/7-fun-things-to-do-with-your-dog-in-chicago/

It is working correctly here: 
http://www.akc.org/content/dog-breeding/articles/akc-offers-easy-options-to-register-puppies/
http://www.akc.org/content/dog-breeding/articles/tax-tips-for-dog-breeders/

**Comment by spaulenoff** [comment]
Also when Viewed source on the articles that aren't working correctly, the category part of the URL is in square brackets:
![image](https://cloud.githubusercontent.com/assets/13648969/14714875/baee29b6-07b4-11e6-8f17-20fcaf96dc9e.png)

When working correctly, the content title is in brackets: 
![image](https://cloud.githubusercontent.com/assets/13648969/14714909/df8c7124-07b4-11e6-96f6-d23e2d9ac752.png)

**Comment by kylejbertelsen** [comment]
time-tracking:
2016-04-22 -- kjb -- 2 hours

**Comment by kylejbertelsen** [comment]
Notes: 
- there was a minor logic error, which caused this error when a title started with a digit, which is now fixed.
- it probably would have been harder to find this error, but there was also an editorial error, which this highlighted: there are several 'category_pages' taxonomy terms which have not had a Category Page piece of content created.

**Comment by elieo** [comment]
@kylejbertelsen  can you please clarify what you mean; "it probably would have been harder to find this error, but there was also an editorial error, which this highlighted: there are several 'category_pages' taxonomy terms which have not had a Category Page piece of content created."

**Comment by spaulenoff** [comment]
@kylejbertelsen @elieo veriffied that this is now working correctly on dev2
http://develop2.akc.org/content/entertainment/articles/7-testing-new-title-tag/

**Comment by spaulenoff** [comment]
Verified on Prod
