### ISSUE TITLE
Featured Story Templates - Capitalize the month

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#202]
The month is not currently capitalized in featured story templates. Can we fix it so it will be: http://www.akc.org/news/obedience-dog-co-therapist/

**Comment by skt2** [comment]
Time Spent: 30m(22 Apr)

Tested here: http://develop2.akc.org/news/worlds-unofficial-oldest-dog-dies-at-30/

**Comment by skt2** [comment]
Tested Here: http://stage-ng.akc.org/news/worlds-unofficial-oldest-dog-dies-at-30/

**Comment by skt2** [comment]
Pre-flight: Tested Here: http://stage-ng.akc.org/news/worlds-unofficial-oldest-dog-dies-at-30/

**Comment by spaulenoff** [comment]
Verified on Prod
