### ISSUE TITLE
Add OAS Queries to Ad units on the whole site

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#204]
Related to #197 
Need to be able to query units by URL and directory. 

The Goal is to be able to control what ads appear on each page type via the ad server.

**Comment by skt2** [comment]
Longest possible url segments: http://www.akc.org/dog-owners/canine-partners/spotlight/wanna-be-english-setter-earns-agility-championship-at-english-setter-trial/

**Comment by skt2** [comment]
Tested Here: http://develop2.akc.org/dog-owners/canine-partners/spotlight/make-your-life-easier-teach-your-dog-some-self-control/

**Comment by elieo** [comment]
@skt2  this looks good to me, but I'm going to check with YourBow that this is good.

**Comment by elieo** [comment]
@skt2  I checked with Yourbow and we want to change 

OAS_sitepage = 'health.akc.org'; // OAS Site page

should change to be: 

OAS_sitepage = 'web.akc.org'; // OAS Site page

The OAS site page is another way on top of queries to block off sections of the site, but the health.akc.org section is already used so we want to remove that.

**Comment by elieo** [comment]
We also want to remove the keyword "squeezed", apparently that was used to describe ads that are being resized on this page http://www.akc.org/learn/. 

Also, sorry to be annoying. Would it be possible to add the AKC vocabulary in the OAS query ? 

For example http://develop2.akc.org/dog-owners/canine-partners/spotlight/make-your-life-easier-teach-your-dog-some-self-control/ 

OAS_query = 'dog-owners&canine-partners&spotlight&make-your-life-easier-teach-your-dog-some-self-control&**[AKC-Vocabulary-1]**&**[AKC-Vocabulary-2]**';

**Comment by spaulenoff** [comment]
@skt2 Please make changes per Elie's notes if possible. Or add comment if not possible within this ticket

**Comment by skt2** [comment]
@elieo Adding [AKC-Vocabulary-1]&[AKC-Vocabulary-2] other then /content pages might take long so not sure that will make in this sprint but I will keep looking into this. other points are fine.

**Comment by skt2** [comment]
We also want to remove the keyword "squeezed".
OAS_sitepage = 'web.akc.org'; // OAS Site page
This changes are pushed to dev2.

**Comment by spaulenoff** [comment]
Added ticket #208 regarding Elie's point for AKC Vocabulary in the OAS Query

**Comment by spaulenoff** [comment]
Verified on Prod

**Comment by skt2** [comment]
Total Time Spent: 2h
