### ISSUE TITLE
Create Categories based on AKC Vocabulary 

### ISSUE THREAD

**Issue by elieo** [akcdotorg/akc.org#205]
We would like the ability to create content categories in this section akc.org/content/ based on articles that are tagged with AKC vocabulary. 

This category should be able to pull in content from one tag or multiple tags.

**Comment by stevepessah** [comment]
@elieo do we want this to be involved in a larger discussion around content tagging?

**Comment by kylejbertelsen** [comment]
We definitely want a broader discussion about this. What is the current Category Pages taxonomy _not_ doing that you want to be able to do?

Blocked by Kyle until we get a clear picture of that.

**Comment by spaulenoff** [comment]
@elieo Please advise on the above comments

**Comment by stevepessah** [comment]
We would like the ability to create new content categories in this /content section that will pull specific article, video and slideshows. The content the categories should be based on the keywords in AKC vocabulary.

For example, "category A" we can specify to pull content tagged with "puppy" and "category A" would pull content that is tagged in AKC Vocabulary as "puppy".

**Comment by stevepessah** [comment]
@elieo need more info here. Some of the questions we have are below. Let's find some time to discuss.
- Where should categories live?
  - Maybe in /content?
- What kind of page type should they be?
- How should users navigate to these categories?
- How do we determine which vocab words get added as categories in the frontend?
- If we have more than one vocabulary term, which vocab work would we use to create the URL?

**Comment by stevepessah** [comment]
Moved to JIRA
