### ISSUE TITLE
Mobile Breed Page Learn More Button

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#207]
We need to resolve the issue on mobile breed pages where the learn more button is being overlapped by the individual arrow buttons.:

![image](https://cloud.githubusercontent.com/assets/13648969/14822174/95de8108-0b9b-11e6-9a39-51a164bf19a5.png)

http://www.akc.org/dog-breeds/staffordshire-bull-terrier/
http://www.akc.org/dog-breeds/american-staffordshire-terrier

**Comment by toshan2014** [comment]
@kylejbertelsen
My understanding : Prevent overlap of button and arrow
Estimate : 1.5h

**Comment by skt2** [comment]
Time Spent: 1h

**Comment by AKCOsama** [comment]
@spaulenoff I don't see the "Learn More" Button, Should it be removed to resolve overlapping issue?

see snapshots:
![learn more button landscape](https://cloud.githubusercontent.com/assets/16208336/14984894/b84c0082-114d-11e6-8a84-3656dc27f430.PNG)
![learn more button portrait](https://cloud.githubusercontent.com/assets/16208336/14984895/b8506780-114d-11e6-82b8-25f10d1aa6a8.PNG)

**Comment by spaulenoff** [comment]
yes confirmed

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by spaulenoff** [comment]
Verified on Prod
