### ISSUE TITLE
Add AKC Vocabulary to OAS Query

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#208]
Related to #204 and #197 

Would it be possible to add the AKC vocabulary in the OAS query ?

For example http://develop2.akc.org/dog-owners/canine-partners/spotlight/make-your-life-easier-teach-your-dog-some-self-control/

OAS_query = 'dog-owners&canine-partners&spotlight&make-your-life-easier-teach-your-dog-some-self-control&[AKC-Vocabulary-1]&[AKC-Vocabulary-2]';

**Comment by kylejbertelsen** [comment]
What is desired here? What is the goal? Is this related to the request in #205? We need to nail-down those questions before adding this.

**Comment by spaulenoff** [comment]
@elieo Please advise per Kyle's questions above

**Comment by elieo** [comment]
@kylejbertelsen 

I want to get the AKC Vocabulary keywords into the OAS query.  The reason is because I will eventually want to target campaigns based on keywords that are not defined in the category / sub category. (as an example, content that would fall into the puppy timeline) 

The date from here:
![image](https://cloud.githubusercontent.com/assets/1423008/14872462/848d91da-0cba-11e6-9412-e416a2d52fa1.png)

Should go here: 
![image](https://cloud.githubusercontent.com/assets/1423008/14872473/a1b881ac-0cba-11e6-81e4-504ca735fb5d.png)

**Comment by spaulenoff** [comment]
Can we also add the following OAS Query for the homepage?  OAS_query = 'homepage';

**Comment by skt2** [comment]
@spaulenoff are you sure we want to add OAS_query on homepage? by adding OAS_query will add entire script.

**Comment by kylejbertelsen** [comment]
@skt2: could you explain that? How does that add an entire other script?

**Comment by skt2** [comment]
We are using snippet to add OAS_query, to add OAS_query to home page, I need include {snip-OAS-setup} in home page layout and it will add entire snippet code({snip-OAS-setup}) on home page which include OAS_ad calls. like:
`OAS_url = 'http://oascentral.akc.org/RealMedia/ads/';
    OAS_sitepage = 'web.akc.org'; // OAS Site page
    OAS_query = 'dog-breeds&afghan-hound';
    OAS_target = '_blank';
    //end of configuration
    OAS_version = 10;
    OAS_rn = '001234567890'; OAS_rns = '1234567890';
    OAS_rn = new String (Math.random()); OAS_rns = OAS_rn.substring (2, 11);
    function OAS_NORMAL(pos) {
        document.write('<A HREF="' + OAS_url + 'click_nx.ads/' + OAS_sitepage + '/1' + OAS_rns + '@' + OAS_listpos + '!' + pos + '?' + OAS_query + '" TARGET=' + OAS_target + '>');
        document.write('<IMG SRC="' + OAS_url + 'adstream_nx.ads/' + OAS_sitepage + '/1' + OAS_rns + '@' + OAS_listpos + '!' + pos + '?' + OAS_query + '" BORDER=0></A>');`

**Comment by skt2** [comment]
so just confirming that we are okay with this. @kylejbertelsen

**Comment by skt2** [comment]
Tested on:
http://develop2.akc.org/ -- Home page
http://develop2.akc.org/news/bloodhound-finds-senior-citizen/ -- News
http://develop2.akc.org/content/entertainment/articles/dog-in-video-keeps-disappearing/ -- Article

**Comment by spaulenoff** [comment]
Not verified on dev2 please check again

**Comment by skt2** [comment]
This is what I am seeing in here: http://develop2.akc.org/news/bloodhound-finds-senior-citizen/ -- News
![screen shot 2016-05-06 at 2 44 26 pm](https://cloud.githubusercontent.com/assets/16002526/15083058/2935c43e-1399-11e6-879d-a3f09eeb25ee.png)

**Comment by skt2** [comment]
1. view-source:http://develop2.akc.org/dog-breeds/affenpinscher/ 
2. view-source:http://develop2.akc.org/dog-owners/canine-partners/spotlight/make-your-life-easier-teach-your-dog-some-self-control/
3. view-source:http://develop2.akc.org/content/entertainment/articles/dog-in-video-keeps-disappearing/
4. view-source:http://develop2.akc.org/news/bloodhound-finds-senior-citizen/
5. view-source:http://develop2.akc.org/content/dog-care/photo-galleries/common-dangerous-foods-for-your-dog/?photo_id=0
   @spaulenoff 
   -- Tested on these pages.
   -- Look for other pages as well that you know off
   -- How to test: got to page and do view source and look for oas_query and see if vocabulary attached at the end of oas_query

**Comment by skt2** [comment]
**CMS Changes:**
Snippets Update: snip-OAS-setup

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on dev2 & stage

**Comment by skt2** [comment]
@spaulenoff tested on couple pages where AKC vocabulary already set. 
view-source:http://www.akc.org/content/entertainment/articles/dog-in-video-keeps-disappearing/
view-source:http://www.akc.org/news/bloodhound-finds-senior-citizen/

**Comment by spaulenoff** [comment]
Verified on Prod

**Comment by skt2** [comment]
Time Spent: 4h
