### ISSUE TITLE
Get dev.akcwinners.com stable and in testing

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#209]
We need for everything to work on that dev site, and for Antoinelle and David to sign-off on it.

After this forthcoming sprint, we'll want Winners to become a part of our normal workload.

**Comment by kylejbertelsen** [comment]
Waiting on information (Percona credentials) from Tim Pursell (for the dev.akcwinners.com server)

**Comment by spaulenoff** [comment]
in jira
