### ISSUE TITLE
Implement Facebook Developer API's to track in the Facebook Developer Analytics Portal

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#21]
https://akcorg.atlassian.net/browse/AKC2-228

**Comment by spaulenoff** [comment]
We want to implement below API's for Facebook Developers portal in order track these metrics in the Facebook Analytics Portal
https://developers.facebook.com/docs/graph-api/reference/v2.4/insights#domain_content
https://www.facebook.com/analytics/530726673730940/?__aref_src=devsite&__aref_id=app_dashboard

**Comment by spaulenoff** [comment]
From Simon Paulenoff 1/4/16 12:31pm: Kyle J Bertelsen the goal for this ticket is to be able to see the facebook analytics and metrics across akc.org

**Comment by spaulenoff** [comment]
From Kyle Bertelson 1/5/16 12:47pm: This will be incredibly hard to QA properly: I assume that viewing these analytics will occur on Facebook itself – and that enabling analytics will have minimal or no effect on develop or stage. I suggest that we determine what the desired effect will look like in our markup, and use expected outcomes in that as a metric (ha!) for success on this.
