### ISSUE TITLE
Remove Mandatory Header Fields in Header Nav Template in CMS

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#210]
We want to make the header fields Not Required in cms for Header Nav Templates. 

![image](https://cloud.githubusercontent.com/assets/13648969/14895892/1231240a-0d49-11e6-83f1-d6fb092ea142.png)

If header fields are not filled out and left blank, we want to make it so the header nov does not open and you can just click the header nav button to go to the link. If links are filled out, please keep the functionality the same.

**Comment by spaulenoff** [comment]
This will help with #191 

Time Spent: 3h 30m

**Comment by skt2** [comment]
NOTE: There is snippet update: snip-header
**CMS Changes**
CMS > Admin > Channel Fields > Header Navigation
Edit Column 1, Column 2, Column 3, Column 4 and Uncheck required field checkbox in grid

CMS > Admin > Channel Fields > Header Navigation > Create New Field
Field Type: Select Dropdown
Field Label: Secondary Menu
Field Name: is_secondary_menu
Populate the menu manually:
Yes
No

**Comment by skt2** [comment]
How to test: @spaulenoff 
Go to CMS > Edit > Header Navigation 
Choose the entry you want to edit(on dev2 I have created new Menu called STORE)
Scroll bottom of the edit page
Secondary Menu: Set to No(By default it will be Yes) -- By Setting it to No, It will only act as link instead of dropdown menu.

**Comment by skt2** [comment]
@spaulenoff: restore the right arrow icon on mobile even if there is no secondary menu as we spoke.

**Comment by AKCOsama** [comment]
QA passed on dev2 and stage, the header fields are Not Required in CMS

**Comment by spaulenoff** [comment]
Verified on Prod
