### ISSUE TITLE
Desktop Breed Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#213]
Subticket of #211

http://www.akc.org/dog-breeds/labrador-retriever/

Changes: Remove 728x90 (x13) ad call at the bottom of the page

Ads on Page after Update - x01, x03 and x11

**Comment by toshan2014** [comment]
dev2 :  http://develop2.akc.org/dog-breeds/labrador-retriever/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/dog-breeds/labrador-retriever/

**Comment by aalattili** [comment]
@spaulenoff 
Develop2: Ads (x01, x03 and x11) are verified
![develop2-breed page ads](https://cloud.githubusercontent.com/assets/12289479/14983794/01f72eec-1148-11e6-819b-a49e79b3f240.jpg)

Stage: 
- Ads (x01and x11) are verified
- Ad (x03) not verified:
  1. Displays as (729x90) instead of (728x90)
     ![stage-breed page ads](https://cloud.githubusercontent.com/assets/12289479/14983807/199bcbf2-1148-11e6-98a4-47fe65d95361.jpg)

**Comment by spaulenoff** [comment]
@toshan2014 Please update per Alaa's comments above

**Comment by toshan2014** [comment]
@spaulenoff
This is due to some images supplied by the ad server having inconsistencies in size. Some are perfectly cut 728x90, others are not. See attached screenshot in #212 for example. Best to keep this this way rather than resize on our end.

**Comment by spaulenoff** [comment]
OK Verified on Stage

**Comment by toshan2014** [comment]
Time spent: 40min

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf: http://stage-ng.akc.org/dog-breeds/labrador-retriever/

**Comment by toshan2014** [comment]
prod http://www.akc.org/dog-breeds/labrador-retriever/

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by spaulenoff** [comment]
Verified on Prod
