### ISSUE TITLE
Desktop Breed Care Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#215]
Subticket of #211

http://www.akc.org/dog-breeds/french-bulldog/care/

Changes:
Add 728x90 (x13) at the top of the page

http://elieorgel.com/wp-content/uploads/2016/04/breed-care-page.png

Ads on Page after Update - x03 and x13

**Comment by toshan2014** [comment]
dev2: http://develop2.akc.org/dog-breeds/french-bulldog/care/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/dog-breeds/french-bulldog/care/

**Comment by aalattili** [comment]
@spaulenoff 
Ads (x03 and x13) are verified on both Stage & Develop2

**Comment by toshan2014** [comment]
Time spent: 40min

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf:
http://stage-ng.akc.org/dog-breeds/labrador-retriever/care/

**Comment by toshan2014** [comment]
prod: 
http://www.akc.org/dog-breeds/french-bulldog/care/

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by spaulenoff** [comment]
Verified on Prod
