### ISSUE TITLE
Desktop Breed Picture Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#216]
Subticket of #211

http://www.akc.org/dog-breeds/parson-russell-terrier/pictures/

Changes add 728x90 (x03) to page between breadcrumb and H1 tag

http://elieorgel.com/wp-content/uploads/2016/04/breed-pictures-page.png

Ads on Page after Update - x03

**Comment by toshan2014** [comment]
dev2 : http://develop2.akc.org/dog-breeds/beagle/pictures/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/dog-breeds/beagle/pictures/

**Comment by aalattili** [comment]
@spaulenoff 
Ad (x03) is verified on both stage & develop2

**Comment by toshan2014** [comment]
Time spent: 40min

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf: 
http://stage-ng.akc.org/dog-breeds/beagle/pictures/

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by toshan2014** [comment]
prod : http://www.akc.org/dog-breeds/parson-russell-terrier/pictures/

**Comment by spaulenoff** [comment]
Verified on Prod
