### ISSUE TITLE
Desktop Browse All Breed Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#217]
Subticket of #211

http://www.akc.org/dog-breeds/

Changes: Move up 300x600 (x05) to between 300x250 (x01) and news and updates

http://elieorgel.com/wp-content/uploads/2016/04/bog-breeds-sub-page.png

Ads on Page after Update - x01, x03 and x05

**Comment by toshan2014** [comment]
dev2 http://develop2.akc.org/dog-breeds/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/dog-breeds/

**Comment by aalattili** [comment]
@spaulenoff 
Ads are verified on both stage & develop2

**Comment by toshan2014** [comment]
Time spent: 40min

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf: 
http://stage-ng.akc.org/dog-breeds/

**Comment by toshan2014** [comment]
prod: http://www.akc.org/dog-breeds/

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by spaulenoff** [comment]
Verified on Prod
