### ISSUE TITLE
Desktop Generic 1 Page Ad Redesign 

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#220]
Subticket of #211

http://www.akc.org/public-education/

Changes: 
add 728x90 (x03) between hero/unhero and breadcrumb
Remove bottom 300x250 (x11)

http://elieorgel.com/wp-content/uploads/2016/04/Generic-1.png

Ads on Page after Update - x01, x03 and x05

**Comment by toshan2014** [comment]
dev2: http://develop2.akc.org/public-education/

**Comment by toshan2014** [comment]
stg:

http://stage-ng.akc.org/public-education/

**Comment by AKCOsama** [comment]
@toshan2014 @spaulenoff : There is no enough space between 728x90 (x03) and 300x250 (x11)
Caused:
when refresh page couples time.
Applicable: 
applicable only on stage environment 

see snapshot:
![generic ads](https://cloud.githubusercontent.com/assets/16208336/14986315/fec99e24-1153-11e6-8304-5e2b1ca05126.png)

**Comment by toshan2014** [comment]
Time spent: 40min

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf : 
http://stage-ng.akc.org/public-education/

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by toshan2014** [comment]
prod http://www.akc.org/public-education/

**Comment by spaulenoff** [comment]
Verified on Prod
