### ISSUE TITLE
Desktop Content Hub Category/Subcateogry Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#221]
Subticket of #211

http://www.akc.org/content/entertainment/
http://www.akc.org/content/entertainment/trending/

Changes: Widen the side nav and add 300x250 (x36) above the side nav

http://elieorgel.com/wp-content/uploads/2016/04/content-category-page.png

Ads on Page after Update - x36

**Comment by toshan2014** [comment]
x35 added instead of x36 which is not of appropriate size.

dev2:
http://develop2.akc.org/content/entertainment/
http://develop2.akc.org/content/entertainment/trending/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/content/entertainment/trending/
http://stage-ng.akc.org/content/entertainment/

**Comment by toshan2014** [comment]
Time spent: 2.5h

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf:
http://stage-ng.akc.org/content/dog-breeding/
http://stage-ng.akc.org/content/dog-breeding/best-practices/

**Comment by toshan2014** [comment]
Total time spent: 4h ( extra fixes were required for tablet )

**Comment by toshan2014** [comment]
prod: 
http://www.akc.org/content/entertainment/trending/
http://www.akc.org/content/entertainment/

**Comment by AKCOsama** [comment]
@spaulenoff , verified on prod

**Comment by spaulenoff** [comment]
Verified on Prod
