### ISSUE TITLE
You Vs Breed Page Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#223]
Subticket of #211

http://www.akc.org/you-vs-breed/

Changes: 
Add 728x90 above orange box
Move "you Vs. Breed H1 to Orange box
Add 728x90 (x13) Below Breadcrumb 

http://elieorgel.com/wp-content/uploads/2016/04/Your-Vs-breed-2ads-b.png

Ads on Page after Update - x03 and x13

**Comment by toshan2014** [comment]
dev2:
http://develop2.akc.org/you-vs-breed/

**Comment by AKCOsama** [comment]
@spaulenoff @toshan2014 QA passed on develop2 and stage-ng

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/you-vs-breed/

**Comment by toshan2014** [comment]
Time spent: 40min

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf: http://stage-ng.akc.org/you-vs-breed/

**Comment by toshan2014** [comment]
prod: 
http://www.akc.org/you-vs-breed/

**Comment by AKCOsama** [comment]
QA passed and Verified on prod as well

**Comment by spaulenoff** [comment]
Verified on Prod
