### ISSUE TITLE
Desktop Find a Match App Ad Redesign

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#224]
Subticket of #211

http://www.akc.org/find-a-match/#slide1
http://www.akc.org/find-a-match/#slide2
http://www.akc.org/find-a-match/#slide3
http://www.akc.org/find-a-match/#slide4
http://www.akc.org/find-a-match/#slide5
http://www.akc.org/find-a-match/#slide6
http://www.akc.org/find-a-match/results/

Change:
Add 728x90 (x03) between header nav and breadcrumb

Mockup:
http://elieorgel.com/wp-content/uploads/2016/04/Find-a-Match.png

Ads on Page after Update - x03

**Comment by toshan2014** [comment]
dev2: 
http://develop2.akc.org/find-a-match/

**Comment by toshan2014** [comment]
Are we removing the H1 title "find a MATCH" from that page? I don't see it in the mockup. @spaulenoff

**Comment by aalattili** [comment]
@spaulenoff 
Verified on both develop2 & stage starting from step 1 to results page

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/find-a-match/

**Comment by toshan2014** [comment]
Time spent: 40min

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf: http://stage-ng.akc.org/find-a-match/results/
http://stage-ng.akc.org/find-a-match/

**Comment by toshan2014** [comment]
prod : 
http://www.akc.org/find-a-match/

**Comment by AKCOsama** [comment]
@spaulenoff , verified on prod:
http://www.akc.org/find-a-match/#slide1
http://www.akc.org/find-a-match/#slide2
http://www.akc.org/find-a-match/#slide3
http://www.akc.org/find-a-match/#slide4
http://www.akc.org/find-a-match/#slide5
http://www.akc.org/find-a-match/#slide6
http://www.akc.org/find-a-match/results/

**Comment by spaulenoff** [comment]
Verified on Prod
