### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#225]
- Look into enabling browser caching.
- Have QA team find any images that are not in the CDN (and not being cached by the CDN).
- Determine if we have the right interval for CE cache and Varnish.

**Comment by kylejbertelsen** [comment]
Regarding CDN, I think I'd like to look into ways to move our js and css into CDN automatically upon update.

**Comment by stevepessah** [comment]
Being tackled by tech and Reliam team, closing.
