### ISSUE TITLE
Fix Desktop Ad Placements for /Learn/ Articles

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#226]
Subticket of #211 

We need to fix the / Learn/ Articles so that x01, x05, and x11 serve how they should be serving. They were serving correctly a few days ago. 

https://web.archive.org/web/20160408235307/http://www.akc.org/learn/dog-health/choosing-the-right-edible-chew-for-your-dog/
https://web.archive.org/web/20160405215814/http://www.akc.org/learn/akc-training/akc-training-good-dog/

**Comment by toshan2014** [comment]
This looks like someone made a change directly on the CMS. It's fine on the production branch - therefore develop2 and stage are fine. I've restored the CMS change. Should be fine on production too now. Please check.

Also I don't see an existing call for x05 on the learn section. Please clarify if we need it somewhere.

http://www.akc.org/learn/dog-health/cephalexin-for-dogs/

**Comment by spaulenoff** [comment]
@toshan2014 I still am only seeing x11 show up on desktop. I am not seeing x05 or x01 anywhere

**Comment by spaulenoff** [comment]
Also, I am seeing another issue on Develop2: 
http://develop2.akc.org/learn/akc-training/akc-training-good-dog/
http://develop2.akc.org/learn/dog-health/cephalexin-for-dogs/

![image](https://cloud.githubusercontent.com/assets/13648969/14983356/bc58e980-110a-11e6-9a67-19938c4c720d.png)

**Comment by toshan2014** [comment]
Please check:
http://develop2.akc.org/learn/dog-health/akc-program-gives-breeders-the-opportunity-to-keep-learning/
http://develop2.akc.org/learn/dog-health/

**Comment by spaulenoff** [comment]
@toshan2014 Verified that i am seeing both ads now, howeverm please check the rest of the template as the middlelink and articleformat has been messed up somehow
http://develop2.akc.org/learn/dog-health/akc-program-gives-breeders-the-opportunity-to-keep-learning/
![image](https://cloud.githubusercontent.com/assets/13648969/14991604/2894d292-1130-11e6-8034-2173d438b6e6.png)

**Comment by toshan2014** [comment]
@spaulenoff that's browser cache. please refresh

Please note that users on prod don't face this "clear cache" issue as the site cache and asset version is updated with every release

**Comment by spaulenoff** [comment]
Verified on dev2 @toshan2014

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/learn/family-dog/what-does-it-mean-to-be-a-family-dog/

**Comment by toshan2014** [comment]
Time spent: 1.5h

**Comment by AKCOsama** [comment]
@toshan2014 @spaulenoff Varified on dev2 and stg

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by toshan2014** [comment]
pf: http://stage-ng.akc.org/learn/family-dog/what-does-it-mean-to-be-a-family-dog/

**Comment by toshan2014** [comment]
prod http://stage-ng.akc.org/learn/family-dog/what-does-it-mean-to-be-a-family-dog/

**Comment by AKCOsama** [comment]
QA passed and verified on production

**Comment by spaulenoff** [comment]
Verified on Prod
