### ISSUE TITLE
Explore removal of Structure plugin

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#227]
Evidence seems to point towards Structure as being a big part of our performance problems with EE.

**Comment by kylejbertelsen** [comment]
Time tracking:
2016-04-29 - kjb - 2 hours

**Comment by aalattili** [comment]
@spaulenoff how to test this ticket?

**Comment by spaulenoff** [comment]
@aalattili No need to test this ticket right now
