### ISSUE TITLE
300x600 on articles pages is getting resized

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#229]
http://www.akc.org/content/dog-breeding/articles/ovulation-in-the-bitch/

The 300x600 unit (x37) is being resized on article pages, we need it so the ad does not resize

On the example, the ad is resized to 284x568

**Comment by spaulenoff** [comment]
The 728x90 also seems to be resizing itself http://www.akc.org/content/entertainment/articles/untrainable-basset-hound-competes-in-agility/
![image](https://cloud.githubusercontent.com/assets/13648969/14985629/4fc56ec2-1116-11e6-898f-f0bbec0d07cd.png)

**Comment by kylejbertelsen** [comment]
Time tracking:
2016-05-02: kjb: 1 hour

**Comment by AKCOsama** [comment]
@spaulenoff Verified on dev2 and stg, ad does not resize.

Note: 300x600 ad scrolled down along with other page's content when scrolling page down
see screencast:
https://onedrive.live.com/redir?resid=57D3F61CBD8EDBE9!960&authkey=!AE4AUoFRj9Om4lg&ithint=video%2cmp4

**Comment by aalattili** [comment]
@spaulenoff , verified on preflight

**Comment by spaulenoff** [comment]
Verified on Prod
