### ISSUE TITLE
Add Donate Now Button to Government Relations Page

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#230]
Can we please add the Donate now button on Government Relations Page: http://www.akc.org/government-relations/

![image](https://cloud.githubusercontent.com/assets/13648969/14966570/2e8d82ac-1081-11e6-9d56-277a89e8f6eb.png)

It needs to link to http://www.akc.org/government-relations/donations/

**Comment by spaulenoff** [comment]
Please note this is currently live being served through Optimizely. We want to make it so this is no longer an optimizely experiment

**Comment by skt2** [comment]
@spaulenoff: Please note this is currently live being served through Optimizely. We want to make it so this is no longer an optimizely experiment -- Can you please explain this?

**Comment by skt2** [comment]
According to @spaulenoff we want to add field(Event category overview channel) in CMS where user can add title and link, if this is filled(not empty) then need to show it as button in front side.

**Comment by spaulenoff** [comment]
Confirmed

**Comment by skt2** [comment]
Time Spent: 2h
*_CMS Changes: *_
CMS > Admin > Channel Admin > Channel Fields > Event Category Overview > Add new
Type: Grid
Label: External Link Button
Name: external_link_button
Field1: 
Label: Title
Name: title
Field2:
Label: Link
Name: link
Field3:
Label: Target
Name: target
Instruction: Use: _blank to open in new window/tab

**Comment by skt2** [comment]
Tested: http://develop2.akc.org/government-relations/

**Comment by aalattili** [comment]
@spaulenoff 

develop2: Events page, ‘Improper txt is displaying’ in button (All Events page-Improper txt in btn.jpg)
![all events page-improper txt in btn](https://cloud.githubusercontent.com/assets/12289479/15146435/0078fb5a-16c4-11e6-8ab8-01dc98f69d3a.jpg)

QA retesting passed on dev2 & stage (http://develop2.akc.org/government-relations/ & http://stage-ng.akc.org/government-relations/)

**Comment by spaulenoff** [comment]
Verified on Prod
