### ISSUE TITLE
Facebook Video embeds Resizing Issue

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#232]
Facebook Video embeds are not working properly on Mobile http://www.akc.org/content/entertainment/articles/untrainable-basset-hound-competes-in-agility/
http://www.akc.org/content/entertainment/articles/his-owner-has-been-away-for-7-months/
http://stage-ng.akc.org/facebook-video/
http://stage-ng.akc.org/content/entertainment/articles/testing-mobile-facebook-video/

Right now, the videos are not clickable on mobile. We need to make it so they work properly and run on mobile

**Comment by spaulenoff** [comment]
I can confirm that YouTube Videos are working correctly on mobile: http://www.akc.org/content/entertainment/articles/youll-laugh-out-loud-when-you-see-how-this-puppy-uses-his-water-bowl/
http://www.akc.org/content/entertainment/articles/great-dane-cant-figure-out-how-to-act/

**Comment by spaulenoff** [comment]
Some research on the issue: https://www.facebook.com/help/community/question/?id=10201533483311527
https://developers.facebook.com/docs/plugins/embedded-video-player

**Comment by spaulenoff** [comment]
@skt2 Please add the solution and what the original issue was

**Comment by skt2** [comment]
Time Spent: 1h

We did change style for facebook comment widget on the media pages and set min-width on that, same style was affecting facebook video so I fixed the style(by defining specific selector) without loosing style for facebook comment page.

**Comment by aalattili** [comment]
@spaulenoff 
Verified on preflight. 
Tested on Samsung S6 and iPhone 6s plus

**Comment by spaulenoff** [comment]
Verified on Prod
