### ISSUE TITLE
Gigya script edits, per Jeff Utley

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#233]

**Comment by toshan2014** [comment]
Malformed redirectURL in script below  fixed on stage - awaiting news from Jeff
`<script>
                function loginHandler(res){
                    gigya.setSSOToken({redirectURL: "http://http://stage-ng.akc.org/"});
                };
                gigya.socialize.addEventHandlers({
                        onLogin: 'loginHandler'
                     }
                );
        </script>`

**Comment by AKCOsama** [comment]
is there a need to test this ticket right now, or migrate to next sprint?

**Comment by toshan2014** [comment]
It seems loginHandler function  is not executing when logging in on stage-ng. Will contact Gigya regarding this. Referencing old ticket :  https://gigya.my.salesforce.com/5004000000tR9mEAAS

**Comment by toshan2014** [comment]
`	<script src="https://cdns.gigya.com/js/gigya.js?apiKey={exp:akc_member:getGigyaApiKey}">
		{
			'bypassCookiePolicy':'always',
			'enableSSOToken': true
		}
	</script>
	<script>
		function loginHandler(res){
		    gigya.setSSOToken({redirectURL: "{site_url}"});
		};
		gigya.socialize.addEventHandlers({
		        onLogin: loginHandler
		     }
		);
	</script>`

**Comment by toshan2014** [comment]
Replace
`<script src="https://cdns.gigya.com/js/gigya.js?apiKey={exp:akc_member:getGigyaApiKey}">
        {bypassCookiePolicy:'always'}
    </script>`
By
`<script src="https://cdns.gigya.com/js/gigya.js?apiKey={exp:akc_member:getGigyaApiKey}">
        {
            'bypassCookiePolicy':'always',
            'enableSSOToken': true
        }
    </script>
    <script>
        function loginHandler(res){
            gigya.setSSOToken({redirectURL: "{site_url}"});
        };
        gigya.socialize.addEventHandlers({
                onLogin: loginHandler
             }
        );
    </script>`
In
templates/snippets/default_site/snip-scripts.snip
templates/snippets/default_site/snip-scripts-microblog.snip

**Comment by spaulenoff** [comment]
Verified in prod by dev team and ISD
