### ISSUE TITLE
Ability to add additional links to /akc-store/

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#234]
Related to #191 

Can we make it so that we can add additional links to /akc-store/ through CMS

**Comment by kylejbertelsen** [comment]
You already can, as it's a WYSIWYG (Wygwam) field in the CMS.

If there's anything to be done here, I think it'd be gathering additional icons you'd like to use some day, and making sure they end up in our assets. Each should be available in both white and orange.

And I recommend that you balance the left and right columns somewhat.
