### ISSUE TITLE
Sprint Log 05-12-2016

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#235]
**Planned for Sprint:**
#167
#242
#208
#240
#239
#209
#231
#230
#243
#244
#248 (added to fix broken OAS query on /learn/ articles

**Needs Attention:**

**In Progress:**

**On Develop2:**

**Verified on Develop2:**

**On Stage:**

**Verified on Stage:**

**On Preflight:**

**Verified on Preflight:**

**On Production:**

**Pushed to Production through 5/10 Hotfix:**
#243
#244

**Removed:**
#241 (Removed due information that is missing currently)
#237 (Removed due information that still needs to be collected)

**Rejected:**

**Comment by spaulenoff** [comment]
Sprint Recaps can be found here: https://docs.google.com/document/d/1LvXTil8UCwOQjzz7iPmTvuFnBeA7vfbJ_RNhrVCiWIg/edit#
