### ISSUE TITLE
Sprint Sign-Off 05-12-2016

### ISSUE THREAD

**Issue by kylejbertelsen** [akcdotorg/akc.org#236]
1. Templates to test. Test a **_different_** page than the example I provide (except for homepage, You Vs Breed, Compare Breeds, Find a Match, News/Akc Dog Lovers Hubs, and AKC Shop). 
2. Please test on Stage-NG
3. Please check on multiple devices if you have the time. 
4. In your comment, please add the page URL you checked for each page template. 

Please let me know if any of you have any additional Ideas for this process.

**AKC Homepage, Header Nav and Footer Nav:** http://www.akc.org/

**Browse All Breeds Page:** http://www.akc.org/dog-breeds/

**SEO Pages:** http://www.akc.org/dog-breeds/best-family-dogs/

**Breed Pages:** http://www.akc.org/dog-breeds/bulldog/

**Breed Detail Page:** http://www.akc.org/dog-breeds/bullmastiff/detail/

**Breed Care Page:** http://www.akc.org/dog-breeds/chinese-shar-pei/care/

**Generic 1:** http://www.akc.org/public-education/

**Generic 2:** http://www.akc.org/events/aenc/

**Events Category Overview**: http://www.akc.org/events/

**News Article:** http://www.akc.org/news/judges-for-2017-westminster-kennel-club-show/

**News Hub:** http://www.akc.org/news/

**AKC Dog Lovers Article:** http://www.akc.org/akc-dog-lovers/loving-vet-tech-warms-our-hearts-again/

**AKC Dog Lovers Hub:** http://www.akc.org/akc-dog-lovers/

**Learn Hub:** http://www.akc.org/learn/

**Learn Article:** http://www.akc.org/learn/dog-health/4-tips-to-help-keep-your-dog-safe-from-fleas-and-ticks/

**Content Hub Category:** http://www.akc.org/content/entertainment/

**Content Hub Sub-Category:** http://www.akc.org/content/entertainment/things-to-do-with-your-dog/

**Content Hub Article:** http://www.akc.org/content/dog-breeding/articles/ovulation-in-the-bitch/

**Content Hub Video:** http://www.akc.org/content/dog-breeding/videos/why-eye-tests-are-important-for-breeding-programs/

**Content Hub Photo-Gallery:** http://www.akc.org/content/health/photo-galleries/common-dangerous-foods-for-your-dog/

**You VS Breed:** http://www.akc.org/you-vs-breed/

**Find a Match:** http://www.akc.org/find-a-match/

**Compare Breeds:** http://www.akc.org/find-a-match/compare-breeds/

**AKC Shop:** http://www.akc.org/akc-store/

**Comment by spaulenoff** [comment]
Kyle to assist

**Comment by toshan2014** [comment]
verified 248, 242 on pf

**Comment by skt2** [comment]
verified #167 #230 #240 and #208 on pre-flight.

**Comment by toshan2014** [comment]
@kylejbertelsen @spaulenoff 

Regarding the process - One thing that would help is to move the unique URLs (homepage, shop, find a match etc) on top of the list

**Comment by skt2** [comment]
Issues:
#252 - http://stage-ng.akc.org/dog-breeds/affenpinscher/ - on tablet

Tested URLs:
http://stage-ng.akc.org/dog-breeds/affenpinscher/
http://stage-ng.akc.org/dog-breeds/affenpinscher/detail/
http://stage-ng.akc.org/dog-breeds/affenpinscher/care/
http://stage-ng.akc.org/dog-breeds/smartest-dogs/
http://stage-ng.akc.org/public-education/resources/
http://stage-ng.akc.org/events/agility/invitational/
http://stage-ng.akc.org/events/conformation-dog-shows/
http://stage-ng.akc.org/news/bulldog-helicopter-copilot/
http://stage-ng.akc.org/akc-dog-lovers/queens-second-favorite-dog-breed/
http://stage-ng.akc.org/learn/family-dog/what-does-it-mean-to-be-a-family-dog/
http://stage-ng.akc.org/content/dog-care/
http://stage-ng.akc.org/content/dog-care/articles/how-to-find-the-perfect-puppy/
http://stage-ng.akc.org/content/dog-care/photo-galleries/common-dangerous-foods-for-your-dog/
http://stage-ng.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/

**Comment by toshan2014** [comment]
Tested on stage:

Unique URLS
http://stage-ng.akc.org/
http://stage-ng.akc.org/you-vs-breed/
http://stage-ng.akc.org/find-a-match/compare-breeds/
http://stage-ng.akc.org/find-a-match/
http://stage-ng.akc.org/find-a-match/results/
http://stage-ng.akc.org/news/
http://stage-ng.akc.org/akc-dog-lovers/
http://stage-ng.akc.org/akc-store/
http://stage-ng.akc.org/dog-breeds/
http://stage-ng.akc.org/dog-breeds/?letter=B
http://stage-ng.akc.org/events/

Learn Microblog
http://stage-ng.akc.org/learn/
http://stage-ng.akc.org/learn/page/P10/
http://stage-ng.akc.org/learn/dog-health/
http://stage-ng.akc.org/learn/dog-health/page/P10/
http://stage-ng.akc.org/learn/family-dog/healthy-happy/
http://stage-ng.akc.org/learn/family-dog/healthy-happy/page/P10/
http://stage-ng.akc.org/learn/family-dog/glucosamine-for-dogs/

Blog Entry Details
http://stage-ng.akc.org/akc-dog-lovers/queens-second-favorite-dog-breed/
http://stage-ng.akc.org/news/support-npdd-2016/

Compare Breeds Results
http://stage-ng.akc.org/find-a-match/compare-breeds/results/?breedcompare=166%7C187

SEO page
http://stage-ng.akc.org/dog-breeds/largest-dog-breeds/

Breed Page
http://stage-ng.akc.org/dog-breeds/neapolitan-mastiff/
http://stage-ng.akc.org/dog-breeds/neapolitan-mastiff/detail/
http://stage-ng.akc.org/dog-breeds/neapolitan-mastiff/care/

Generic 1
http://stage-ng.akc.org/dog-owners/

Generic 2
http://stage-ng.akc.org/events/tracking/

Content Hub:
http://stage-ng.akc.org/content/dog-shows/articles/westminster-group-results-day-2/
http://stage-ng.akc.org/content/dog-breeding/videos/canine-health-testing/
http://stage-ng.akc.org/content/dog-training/photo-galleries/teach-your-dog-to-give-you-a-high-five/
http://stage-ng.akc.org/content/dog-training/
http://stage-ng.akc.org/content/entertainment/did-you-know/

Sprint-unrelated issues found: #250, #251, #253, #254, #255

**Comment by spaulenoff** [comment]
**AKC Homepage, Header Nav and Footer Nav:** http://stage-ng.akc.org/

**Browse All Breeds Page:** http://stage-ng.akc.org/dog-breeds/

**SEO Pages:** http://stage-ng.akc.org/dog-breeds/best-dogs-for-apartments/

**Breed Pages:** http://stage-ng.akc.org/dog-breeds/wire-fox-terrier/

**Breed Detail Page:** http://stage-ng.akc.org/dog-breeds/wire-fox-terrier/detail/

**Breed Care Page:** http://stage-ng.akc.org/dog-breeds/wire-fox-terrier/care/

**Generic 1:** http://stage-ng.akc.org/dog-owners/training/akc-therapy-dog-program/

**Generic 2:** http://stage-ng.akc.org/downloadable-forms/

**Events Category Overview**: http://stage-ng.akc.org/events/agility/

**News Article:** http://stage-ng.akc.org/news/akc-pet-disaster-relief-rolls-out-mobile-help-for-bergen-county-pets/

**News Hub:** http://www.akc.org/news/

**AKC Dog Lovers Article:** http://stage-ng.akc.org/akc-dog-lovers/loving-vet-tech-warms-our-hearts-again/

**AKC Dog Lovers Hub:** http://www.akc.org/akc-dog-lovers/

**Learn Hub:** http://stage-ng.akc.org/learn/

**Learn Article:** http://stage-ng.akc.org/learn/dog-health/how-to-remove-tick-from-dog/

**Content Hub Category:** http://stage-ng.akc.org/content/dog-breeding/

**Content Hub Sub-Category:** http://stage-ng.akc.org/content/entertainment/things-to-do-with-your-dog/

**Content Hub Article:** http://stage-ng.akc.org/content/dog-shows/articles/meet-canaan-dog-magnum/

**Content Hub Video:** http://stage-ng.akc.org/content/dog-breeding/videos/canine-health-testing/

**Content Hub Photo-Gallery:** http://stage-ng.akc.org/content/dog-care/photo-galleries/common-dangerous-foods-for-your-dog/?photo_id=5

**You VS Breed:** http://stage-ng.akc.org/you-vs-breed/

**Find a Match:** http://stage-ng.akc.org/find-a-match/

**Compare Breeds:** http://stage-ng.akc.org/find-a-match/compare-breeds/

**AKC Shop:** http://stage-ng.akc.org/akc-store/

Found same issues called out above
