### ISSUE TITLE
Prepare WOOFipedia content migration

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#237]
We need to move content from WOOFipedia to the /content section.

Not all content will be moved but Elie will determine which content will move over. Since we are moving 100 articles I believe it will be much more efficient to do a content import. There must be a way to import the content in bulk.

Elie to provide CSV for every field type for every article (start with example of 15 articles).

**Comment by kylejbertelsen** [comment]
@elieo: the sooner I can get a true sample from you, the sooner I can get this moving forward. I know we have a meeting later today, so I'm not expecting this today, but tomorrow (Tues., 05/10) would be good.
