### ISSUE TITLE
Prepare AKC.org Content Migration

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#238]
- We need to move content from the /learn section to the /content section.
- We need to move content from WOOFipedia to the /content section.

Not all content will be moved but Elie will determine which content will move over. Since we are moving ~1,000 articles I believe it will be much more efficient to do a content import.  There must be a way to import the content in bulk.

Elie to provide CSV for every field type for every article (start with example of 15 articles).

**Comment by spaulenoff** [comment]
Moved to Jira
