### ISSUE TITLE
FB API Alert

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#239]
Elie found this alert in FB Admin. We are not sure what the issue is but we need to investigate.

Your Webhooks subscription for callback URL (https://updates.gigya.com/updates/facebook/3_Lj3tvb7hiyZc-gMQzdPPjDtkzed-My4IbPS_nnWd_dGSIk93QMKAyhZaIDmhQsll) has not been accepting updates for the past 7 days. We have disabled this subscription at this time. To reactivate the subscription, make a POST request with the same parameters, and it will be reactivated. 
https://developers.facebook.com/docs/graph-api/reference/app/subscriptions#publish

**Comment by toshan2014** [comment]
@stevepessah @elieo 
I'd like to see how the other webhooks are setup within the Facebook account, can I have the login info?
Also when is this alert message dated?

**Comment by spaulenoff** [comment]
@stevepessah Please advise per Toshan's question above

**Comment by spaulenoff** [comment]
I provided Toshan with admin access to look into this

**Comment by aalattili** [comment]
@spaulenoff , we need more details on how to test this ticket

**Comment by toshan2014** [comment]
I have contacted Gigya on 05/10/2016 regarding this issue - 
Case ID: #90532

> Hi team,
> 
> We have received the alert message below from Facebook on 04/29/2016. Could you please shed some light on this:
> 
> Your Webhooks subscription for callback URL https://updates.gigya.com/updates/facebook/3_Lj3tvb7hiyZc-gMQzdPPjDtkzed-My4IbPS_nnWd_dGSIk93QMKAyhZaIDmhQsll has not been accepting updates for the past 7 days. We have disabled this subscription at this time. To reactivate the subscription, make a POST request with the same parameters, and it will be reactivated.
> 
> Many thanks
> Toshan

**Comment by toshan2014** [comment]
Reply from Gigya:

> > Hello Toshan,
> 
> We are currently aware of a service issue regarding Facebook Social Sync, and our engineers are working on resolving the issue. Facebook is also investigating the issue on their end.
> 
> You can reactivate the Facebook Webhooks by simply by clicking the "save" button on the Provider Configuration page in Gigya's console.
> 
> Best Regards,
> 
> Shirley
> Client Services Engineer
> Gigya, Inc.

**Comment by toshan2014** [comment]
Response:

> Hi Shirley
> 
> Could you please provide us with some info as to what services this issue might be affecting? And if you can suggest any tests we can run on our side to see the problem.
> 
> Also I don't see a 'Save' button. There's a 'Saves Settings' but that's greyed out. See attachment.
> 
> Please advise,
> Thank you
> Toshan

**Comment by toshan2014** [comment]
Reply from Gigya:

> Hello Toshan,
> 
> Social Sync is the service which synchronizes profile updates made off-site on Facebook.com to the corresponding Gigya profile.
> 1. Who does this outage affect?
>    This outage may affect anyone with a Facebook app configured in the Gigya Console, however, not all sites have been impacted.
> 2. Does this outage affect Facebook login as well, or just Social Sync?
>    The outage only affects Social Sync. Facebook login is not affected. In addition, any time a user logs into your site/app via Facebook, Gigya synchronizes their entire profile regardless of Social Sync.
> 3. Will I need to do anything on my end in order to fix this issue?
>    Opening the Gigya Console and navigating to Site Settings > Providers Configurations > Save Settings will re-activate Facebook webhooks for your site.
> 4. What will happen to profile updates that were made during the outage period?
>    Facebook profile updates made during the outage will not be synced by Gigya, however, users’ profiles will be synced the next time they login to your site via Facebook.
> 
> It appears you do not the access to save the settings. I went ahead and saved it for you and you can verify by logging into the Facebook app and checking the Webhooks page.
> 
> Best Regards,
> 
> Shirley
> Client Services Engineer
> Gigya, Inc.

**Comment by toshan2014** [comment]
According to Gigya, only thing we can do on our end is the following in the console:  'Site Settings > Providers Configurations > Save Settings'. And they already have done so for us.

No changes required from our side at this stage.

Note: I've checked the Webhooks section on the fb app as per Shirley's note above and I do see the Gigya subscription.

**Comment by toshan2014** [comment]
Time spent: 2h

**Comment by spaulenoff** [comment]
@toshan2014 Any update here?

**Comment by toshan2014** [comment]
Contacted Gigya for update:

> Hi Shirley
> 
> Do we have any updates on this?
> 
> Thanks
> 
> Toshan

**Comment by toshan2014** [comment]
Gigya Update: Facebook Social Sync Service Issue - Resolved

**Comment by toshan2014** [comment]
From Gigya

> Dear Valued Gigya Customer,
> 
> We wanted to inform you that the issue with Facebook Social Sync has been resolved. Though Facebook has not determined the root cause of the issue, we have added additional levels of logging and system debugging to help us identify and resolve such issues in the future.
> 
> We have also re-activated Facebook Social Sync for all accounts. To verify that it’s active for your sites, log into your Facebook for Developers account > Webhooks section, and verify that there is an entry containing a Gigya URL.
> 
> Feel free to use the Support Portal if you have any questions or concerns.

**Comment by toshan2014** [comment]
Webhook verified on FB ( as mentioned above )
