### ISSUE TITLE
Update AKC Store Mobile Landing Page

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#240]
Related to #191 

http://www.akc.org/akc-store/

Needs to be able to include "Treats, Toys, & Accessories" in the right Orange Button on mobile

![image](https://cloud.githubusercontent.com/assets/13648969/15053897/d911cc8a-12d2-11e6-9c2f-e1bca1a071cc.png)

**Comment by skt2** [comment]
@kylejbertelsen is there anything else I need to do other then updating DB to see it locally?

**Comment by skt2** [comment]
@spaulenoff, @kylejbertelsen: We might need to change the layout a little as "Treats, Toys & Accessories" is not adjustable on mobile with mockup. Here is suggested one:
![screen shot 2016-05-06 at 12 45 36 pm](https://cloud.githubusercontent.com/assets/16002526/15079800/b9515a3a-1388-11e6-940b-ce72dcae1d57.png)

**Comment by skt2** [comment]
This is how it looks with current layout:
![screen shot 2016-05-06 at 12 49 35 pm](https://cloud.githubusercontent.com/assets/16002526/15079873/15916b1e-1389-11e6-9595-a976a67591af.png)

**Comment by skt2** [comment]
This is how it can be adjusted if we still want to go as per mockup:
![screen shot 2016-05-06 at 1 39 32 pm](https://cloud.githubusercontent.com/assets/16002526/15081276/321cbc5a-1390-11e6-8f5a-8ad89cfdf193.png)

**Comment by spaulenoff** [comment]
@stevepessah Please advise on how you would like to move forward here:

Mockup one:
![image](https://cloud.githubusercontent.com/assets/13648969/15081339/866ceee2-1390-11e6-8929-8195a61b53ee.png)

Mockup Two:
![image](https://cloud.githubusercontent.com/assets/13648969/15081349/8e611830-1390-11e6-9b64-15d181f2aac3.png)

**Comment by skt2** [comment]
Mockup 3: @stevepessah 
![screen shot 2016-05-06 at 1 48 46 pm](https://cloud.githubusercontent.com/assets/16002526/15081534/6a6ccb80-1391-11e6-9648-65bb282d013b.png)

**Comment by spaulenoff** [comment]
@skt2 Should look like this but with text being vertically aligned
![screen shot 2016-05-06 at 2 15 49 pm](https://cloud.githubusercontent.com/assets/13648969/15082426/a42b197c-1395-11e6-9b54-a9da1abf43b3.png)

**Comment by skt2** [comment]
@spaulenoff: final confirmation?
![screen shot 2016-05-06 at 3 40 36 pm](https://cloud.githubusercontent.com/assets/16002526/15084371/f882f75a-13a0-11e6-8148-e125c73fd255.png)

**Comment by spaulenoff** [comment]
mockup looks good

**Comment by skt2** [comment]
**CMS Changes:**
Update the akc-store content

**Comment by spaulenoff** [comment]
@stevepessah Please verify on dev2. I checked and it looks good to me

**Comment by spaulenoff** [comment]
Verified on dev 2 per Steve

**Comment by aalattili** [comment]
@spaulenoff 
Testing was applied on Samsung S6 & iPhone 6s
QA retesting passed on dev2 & stage, akc-store displays as in the latest mokup

One minor issue was found:
Shop main page-In landscape, ‘Toys, Treats & Accessories’ txt is not centralized in box (Shop-Treats, Toys & Accessories txt isn't centralized.jpg) 
![shop-treats toys accessories txt isn t centralized](https://cloud.githubusercontent.com/assets/12289479/15146208/ce3287ca-16c2-11e6-9c79-eb39e4b87975.jpg)

**Comment by skt2** [comment]
found issue on table portrait:
![tablet-issue](https://cloud.githubusercontent.com/assets/16002526/15149162/7ab7a480-1696-11e6-9497-e70aa1104934.png)

Possible Fix:
![tablet-fix](https://cloud.githubusercontent.com/assets/16002526/15149173/87ddddd2-1696-11e6-9cd3-f7f405e6d217.png)

@spaulenoff Let me know if want to apply this.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on dev2 on tablet. I've checked it and i am seeing the buttons you have asked for

**Comment by spaulenoff** [comment]
Verified on dev2. Please push to stage and production now that we are in preflight

**Comment by skt2** [comment]
Time spent: 4h 
Spent more time than estimation as there was new change request for tablet.

**Comment by spaulenoff** [comment]
Verified on Prod
