### ISSUE TITLE
shop.akc.org links are being redirected to www.akc.org links when used in the cms

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#242]
http://www.akc.org/akc-store/

For example **Toys & Treats** should link to https://shop.akc.org/collections/woofipedia-packs but instead its linking to http://www.akc.org/collections/woofipedia-packs/

**Comment by toshan2014** [comment]
dev2 http://develop2.akc.org/akc-store/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/akc-store/

**Comment by toshan2014** [comment]
Time spent: 1h

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on dev2 & stage

**Comment by toshan2014** [comment]
pf: http://stage-ng.akc.org/akc-store/

**Comment by toshan2014** [comment]
prod http://www.akc.org/akc-store/

**Comment by spaulenoff** [comment]
Verified on prod
