### ISSUE TITLE
Conditional List Pos

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#243]
Need to add conditional to listpos so that only desktop ads are served on desktop and only mobile ads are served on mobile

**Comment by toshan2014** [comment]
Condition added and all pages which call "OAS_listpos" variable have been modified to separate mobile to desktop ads as codewise any ad can be for both mobile and desktop. Meaning for ex: 
`{exp:stash:set name="adscalled"}x20,x35{/exp:stash:set}` 
has been changed to 
`{exp:stash:set name="adscalled_mob"}x20{/exp:stash:set}
{exp:stash:set name="adscalled_desk"}x35{/exp:stash:set}`

To verify the "OAS_listpos" being generated, i've added a console.log - see screenshot for ex.

DESKTOP
<img width="825" alt="oas_listpos" src="https://cloud.githubusercontent.com/assets/6847220/15109736/c8ae9c58-1591-11e6-8d69-73cee7659e1a.PNG">

MOBILE
<img width="901" alt="oas_listpos_mob" src="https://cloud.githubusercontent.com/assets/6847220/15109828/4353e18e-1592-11e6-9358-5086ff92e2d5.PNG">

**Comment by spaulenoff** [comment]
Sent to Yourbow to check over

**Comment by spaulenoff** [comment]
Response from Yourbow:

We did notice that there are some tweaks needed re listpos part (this page as example):
http://develop2.akc.org/learn/akc-gazette/the-akc-gazette-celebrating-the-sport-of-dogs/
x01 ad is not serving at all regardless of platform but it is still in Listpos line, so if it should not be serving at all then it should be removed from listpos line (or ad call added for it to start serving ads)
in mobile we can only see x25 mobile ad serving but no x01 nor x11

**Comment by toshan2014** [comment]
Changes made in Learn section per Yourbow:
x01,x11 only on list pages ( mobile and dekstop ) [ ex http://develop2.akc.org/learn/dog-health/care/page/P20/ ]
x25 (mobile only) & x11,x05 ( desktop only ) [ ex http://develop2.akc.org/learn/dog-health/probiotics-for-dogs/ ]

Please QA / see console.log

Note: Because the 'squeeze' keyword was decided to be removed in one of the previous tickets, the ads do not resize ( they remain in their original size ). Therefore on small mobile devices they might take more space than expected.

**Comment by spaulenoff** [comment]
Verified by yourbow:

Yes, coding in place is making right ad calls and we are seeing all called ads serving now. 
Note that there is only one ad serving on mobile now (x25 300x50), so if there is need for more ads on mobile (like 300x250 pehaps) it can be added as well

**Comment by toshan2014** [comment]
Email sent to Yourbow to cross verify changes : 

> _Thanks Novak
> 
> We plan to make the changes live today. The final adjustments are in our staging environment. I have reviewed them and they seem fine. Could you please do a final check to confirm the ads conform to your guidelines:
> 
> http://stage-ng.akc.org/content/dog-breeding/articles/ovulation-in-the-bitch/
> 
> http://stage-ng.akc.org/content/dog-breeding/videos/the-baer-hearing-test-for-dogs/
> 
> http://stage-ng.akc.org/content/dog-care/photo-galleries/common-dangerous-foods-for-your-dog/
> 
> http://stage-ng.akc.org/content/dog-breeding/tips-from-experts/
> 
> http://stage-ng.akc.org/content/dog-breeding/
> 
> http://stage-ng.akc.org/learn/
> 
> http://stage-ng.akc.org/learn/akc-gazette/the-akc-gazette-celebrating-the-sport-of-dogs/
> 
> Many thanks again
> 
> Toshan_

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on dev2 & stage, ‘OAS_listpos’ is found on dev2 & stage (checked on some pages)

**Comment by toshan2014** [comment]
Verified in prod:
http://www.akc.org/content/entertainment/
http://www.akc.org/content/entertainment/trending/
http://www.akc.org/content/entertainment/articles/man-calls-dogs-over/
http://www.akc.org/content/entertainment/photo-galleries/diy-dog-paw-towel/

**Comment by toshan2014** [comment]
Time spent: 5h

**Comment by spaulenoff** [comment]
Verified on Prod per Yourbow
