### ISSUE TITLE
Add Teads In-Content Video code to Generic Page Templates 

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#246]
We want to add the option to have teads in content video adds to generic 1 and generic 2 templates: Set it on a page-by-page basis, not as a global.

Generic: 
http://www.akc.org/clubs/how-to-form-club/
http://www.akc.org/clubs/promote/

Generic 2:
http://www.akc.org/clubs/

Mockup:
![clubs-events-ads-with-gumgum 3](https://cloud.githubusercontent.com/assets/13648969/15153702/3fbd06c4-16a8-11e6-98f7-85c81380e5ea.jpg)

Related to #206 #164 #103

**Comment by stevepessah** [comment]
Moved to JIRA
