### ISSUE TITLE
Modify OAS_query for learn section

### ISSUE THREAD

**Issue by toshan2014** [akcdotorg/akc.org#248]
Modify OAS_query in learn section per YourBow email:

> In page code it should be set like this:
> 
> http://www.akc.org/learn/dog-health/4-tips-to-protect-your-dog-from-heartworm/   - OAS_query = 'learn-page&learn&4-tips-to-protect-your-dog-from-heartworm';
> 
> http://www.akc.org/learn/dog-health/4-tips-to-help-keep-your-dog-safe-from-fleas-and-ticks/ - OAS_query = 'learn-page&learn&4-tips-to-help-keep-your-dog-safe-from-fleas-and-ticks';

**Comment by toshan2014** [comment]
Develop2 : 
view-source:http://develop2.akc.org/learn/dog-health/4-tips-to-help-keep-your-dog-safe-from-fleas-and-ticks/

**Comment by spaulenoff** [comment]
@toshan2014 I am seeing it work correctly now on dev 2 Please confirm if this is ready to push.

Please also let us know what caused this issue

**Comment by toshan2014** [comment]
Tested on preflight : 
view-source:http://stage-ng.akc.org/learn/family-dog/what-does-it-mean-to-be-a-family-dog/

On 4/22/2016 the condition for that section was removed. I'm not sure what the reasoning was behind but that's what caused this.

**Comment by toshan2014** [comment]
Time spent: 1.5h

**Comment by toshan2014** [comment]
prod:
view-source:http://www.akc.org/learn/dog-health/4-tips-to-protect-your-dog-from-heartworm/
view-source:http://www.akc.org/learn/dog-health/4-tips-to-help-keep-your-dog-safe-from-fleas-and-ticks/

please inform Rebecca that this is resolved

**Comment by spaulenoff** [comment]
Verified on Prod
