### ISSUE TITLE
Ipad Pro Portrait Nav

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#249]
We need to fix the header nav on Ipad Pro Portrait orientation. We need to fit all nav items on one line.
Please note: This refers only to the TOP NAV (Note how Shop is shifted to the next line in the screenshot.)

![screen shot 2016-05-11 at 9 55 26 am](https://cloud.githubusercontent.com/assets/13648969/15183589/a83dc8fc-175f-11e6-8e08-aceffc8b4bda.png)

**Comment by skt2** [comment]
Time Spent: 50m

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on dev2 & stage. Note that since iPad pro isn't available (real device & emulator) this ticket was tested on iPad air-iOS 9.2 'emulator' & iPad 2 'real device'.

**Comment by aalattili** [comment]
@spaulenoff 
Verified on prod
