### ISSUE TITLE
Issue with dropdown in zipcode field

### ISSUE THREAD

**Issue by toshan2014** [akcdotorg/akc.org#251]
http://www.akc.org/find-a-match/#slide1

If the zipcode is clicked/selected from the dropdown, "Continue" does not activate ( ie. it does not turn orange ). See screenshot:

<img width="960" alt="zip-code-issue" src="https://cloud.githubusercontent.com/assets/6847220/15190715/4dac961e-1766-11e6-9e84-30bcc21fafd7.png">

**Comment by skt2** [comment]
@toshan2014 somehow I don't see any dropdown while typing zipcode but I found this:
![screen shot 2016-05-11 at 2 56 44 pm](https://cloud.githubusercontent.com/assets/16002526/15192757/9c2872aa-1788-11e6-910b-fcca6a444540.png)

**Comment by toshan2014** [comment]
@skt2 
1) The drop-down is cached in the browser once it's used before. It's chrome/firefox autofill.
2) Yeah we need to make that "This value...." text smaller or move "Continue" a bit down

**Comment by stevepessah** [comment]
When clicking the autofill selection, a yellow background shows. We would like that to be removed.

![screen shot 2016-05-12 at 3 07 13 pm](https://cloud.githubusercontent.com/assets/1063028/15227024/4aa91346-1853-11e6-998b-5246bf2ba94c.png)

**Comment by kylejbertelsen** [comment]
Check to see if action is on keyup -- maybe change to blur/focus?

**Comment by skt2** [comment]
Time Spent: 3h
Tested on: http://develop2.akc.org/find-a-match/#slide1

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting results:
1- Select a zipcode from cached list, will enable 'continue' link
- Passed on GC 50
- No cache list on IE 11& Devices
- Failed on FF 45 (FF-Select from list doesn't enable continue link.jpg)
  ![ff-select from list doesn t enable continue link](https://cloud.githubusercontent.com/assets/12289479/15462219/cfde2d16-20c9-11e6-8dc3-e0e6aeb988fd.jpg)

2- Overlapping issue
- Passed on desktop browsers (GC, IE & FF) & devices (iPhone 6s plus, Samsung galaxy S6 & Samsung Tab)

**Comment by skt2** [comment]
@aalattili @spaulenoff 
Somehow I am not able to replicate issue in FF(though FF version is 46.0.1) so can you please check this at your end once again? Please clear the browser cache once before testing.
![screen shot 2016-05-23 at 9 44 29 am](https://cloud.githubusercontent.com/assets/16002526/15472876/3cf41856-20cb-11e6-8ba9-7f8f20e30d02.png)

**Comment by spaulenoff** [comment]
Verified its working for me on stage

**Comment by aalattili** [comment]
@spaulenoff 
Verified on production
Tested on Chrome , Firefox

**Comment by spaulenoff** [comment]
Verified on Prod
