### ISSUE TITLE
Breed details page - Style issue on Tablet

### ISSUE THREAD

**Issue by skt2** [akcdotorg/akc.org#252]
http://stage-ng.akc.org/dog-breeds/affenpinscher/ - Hero Image and other content is messed up.

![screen shot 2016-05-11 at 2 15 35 pm](https://cloud.githubusercontent.com/assets/16002526/15191473/dee8c488-1782-11e6-90b6-8ad21ed043ad.png)

**Comment by spaulenoff** [comment]
in jira
