### ISSUE TITLE
Investigate JS error 

### ISSUE THREAD

**Issue by toshan2014** [akcdotorg/akc.org#253]
A JS error appears in the console for certain pages. Needs investigation:

http://stage-ng.akc.org/dog-breeds/neapolitan-mastiff/care/
<img width="576" alt="js-error2" src="https://cloud.githubusercontent.com/assets/6847220/15191494/c8f74744-1769-11e6-926c-6f17e4e5cb7a.PNG">

**Comment by stevepessah** [comment]
Moved to JIRA
