### ISSUE TITLE
Learn Section - no padding

### ISSUE THREAD

**Issue by toshan2014** [akcdotorg/akc.org#254]
It seems there's no ( or not enough ) padding in the learn section. See screenshot: 
http://stage-ng.akc.org/learn/family-dog/glucosamine-for-dogs/

<img width="652" alt="learn-no-paddig" src="https://cloud.githubusercontent.com/assets/6847220/15192074/7f06d50c-176c-11e6-8779-3bdb73753fdb.PNG">

**Comment by kylejbertelsen** [comment]
worst. Screenshot. Ever.
