### ISSUE TITLE
Video partly hidden on smaller screens desktops

### ISSUE THREAD

**Issue by toshan2014** [akcdotorg/akc.org#255]
http://stage-ng.akc.org/content/dog-breeding/videos/canine-health-testing/

The video is partly hidden. I have to scroll down to see the video. See screenshot:

<img width="865" alt="small-screen-video" src="https://cloud.githubusercontent.com/assets/6847220/15192324/89c9f004-176d-11e6-8539-3aed4248f4b9.PNG">

These videos are uploaded through JW Player

**Comment by toshan2014** [comment]
dev2: http://develop2.akc.org/content/dog-breeding/videos/why-eye-tests-are-important-for-breeding-programs/

**Comment by toshan2014** [comment]
stg: 
http://stage-ng.akc.org/content/dog-breeding/videos/why-eye-tests-are-important-for-breeding-programs/

**Comment by spaulenoff** [comment]
@toshan2014 Not verified still not working on chrome for windows 7
![image](https://cloud.githubusercontent.com/assets/13648969/15407324/43051f74-1dd8-11e6-8a37-f8549db8653a.png)

It is working on FF and IE11 however

**Comment by toshan2014** [comment]
@sip please check again

**Comment by spaulenoff** [comment]
Verified on stage

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on dev2 & stage - Tested on browsers (GC 50, FF 45 & IE 11) & devices (Samsung tab, iPhone 6s plus & Samsung galaxy S6)

**Comment by aalattili** [comment]
@spaulenoff 
IE 11 issue-Video can't be maximized:
1- Maximizing video while playing, will change the location of the video & control bar from central to the left hand side of the window.
2- Maximize video while it is paused-video will be maximized but when pressing on play button, video will be minimized and move the the left hand side of window
![ie 11-video is improperly maximized](https://cloud.githubusercontent.com/assets/12289479/15453829/cb7e7372-202c-11e6-8be9-2cffb537277f.jpg)

**Comment by toshan2014** [comment]
Should be fixed : http://stage-ng.akc.org/content/dog-breeding/videos/why-eye-tests-are-important-for-breeding-programs/

**Comment by aalattili** [comment]
QA retesting on IE 11 passed on both dev2 & stage-ng
(IE 11-Video is maximized properly.jpg)
![ie 11-video is maximized properly](https://cloud.githubusercontent.com/assets/12289479/15466200/f7c44376-20e0-11e6-934b-363c87807570.jpg)

**Comment by toshan2014** [comment]
pf : http://stage-ng.akc.org/content/dog-breeding/videos/why-eye-tests-are-important-for-breeding-programs/  ( tested ok on IE 11 and chrome )

**Comment by toshan2014** [comment]
Spent : 3h

**Comment by toshan2014** [comment]
prod (tested on Chrome and IE11): 
http://www.akc.org/content/dog-breeding/videos/canine-health-testing/

**Comment by aalattili** [comment]
Verified on production 
Tested on Chrome and IE 11.

**Comment by spaulenoff** [comment]
Verified on Prod
