### ISSUE TITLE
Fix List style on /learn/ Articles

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#266]
http://www.akc.org/learn/akc-training/dog-facts/

The list font style needs to be the same font size as the rest of the article

**Comment by skt2** [comment]
Time Spent: 30m

**Comment by aalattili** [comment]
@spaulenoff , is it the list showing in screenshot below? 
if yes then, QA retesting results-Tested on browsers (GC 50, IE 11 & FF 45):
- Passed on dev2 
- Failed on stage 
  (Learn page-List style failed on stage.jpg)
  ![learn page-list style failed on stage](https://cloud.githubusercontent.com/assets/12289479/15454494/9a01f5d8-2042-11e6-8323-68871a5dd142.jpg)

**Comment by spaulenoff** [comment]
@skt2 Please advise on the above

**Comment by skt2** [comment]
@spaulenoff @aalattili 
On Production:
![screen shot 2016-05-25 at 10 59 59 am](https://cloud.githubusercontent.com/assets/16002526/15544766/e8ba5b58-2267-11e6-899e-92b4d5a11da2.png)

On Develop2:
![screen shot 2016-05-25 at 11 00 15 am](https://cloud.githubusercontent.com/assets/16002526/15544782/f7fd5872-2267-11e6-8523-5b5660541653.png)

On Stage:
![screen shot 2016-05-25 at 11 00 26 am](https://cloud.githubusercontent.com/assets/16002526/15544789/01a33a36-2268-11e6-9a1a-12209c197eb3.png)

I am not sure about this but this how its looking for me on stage which identical to akc.org, don't know what is wrong with dev2.

**Comment by skt2** [comment]
@spaulenoff: I'll check with @toshan2014 once as this changes might related to #276

**Comment by aalattili** [comment]
@skt2 
Also for me options in list aren't clickable neither on production nor on stage, i mean they don't direct to related pages 
![list not clickable](https://cloud.githubusercontent.com/assets/12289479/15545479/1a88d01e-22a5-11e6-97b5-bdaa74659f64.jpg)

**Comment by skt2** [comment]
@aalattili if the issue is on production then I guess this is different issue and new ticket should be added for this.
Frankly speaking this dropdown issue is not related to my changes but I'll still look into this and see if I can find anything.

**Comment by skt2** [comment]
**CMS Changes:**
Snippets Update: update {snip-scripts-microblog}

**Comment by skt2** [comment]
@spaulenoff @aalattili Fixed dropdown issue.

**Comment by aalattili** [comment]
@skt2  @spaulenoff QA retest results:
1- Passed-dev2 & stage, now drop-down design is matching
2- Passed-options in list are clickable
![list is clickable](https://cloud.githubusercontent.com/assets/12289479/15569551/0b49d590-233a-11e6-845b-c55a779b5a75.jpg)

**Comment by aalattili** [comment]
@spaulenoff 
Verified on production
Tested on Chrome, Firefox

**Comment by spaulenoff** [comment]
Verified on Prod
