### ISSUE TITLE
Add Marketplace button back to Breed pages on Mobile

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#269]
Somehow the marketplace button on breed pages disappeared on Mobile. We need to add it back.

Example URLs where this is missing:
www.akc.org/dog-breeds/skye-terrier/
http://www.akc.org/dog-breeds/basset-hound/

**Comment by spaulenoff** [comment]
Please add an estimate to this ticket @skt2

**Comment by kylejbertelsen** [comment]
@spaulenoff: are there any (known) examples where it is not missing?

@skt2: when investigating, please let me know which templates/scripts/css are involved.

**Comment by skt2** [comment]
@kylejbertelsen 
src/scss/pages/_breedfeed.scss
../templates/default_site/breed.group/.overview.html

**Comment by skt2** [comment]
Time spent: 15m

**Comment by spaulenoff** [comment]
@kylejbertelsen Haven't been able to check all breed pages, but it seems to be missing on everyone i checked so far

**Comment by skt2** [comment]
Reason: while working on previous ticket(I'll update ticket number once I find in closed tickets) to hide learn more button on mobile, there was style conflict with Marketplace button. 
@spaulenoff: fixing style will fix it on all breed pages.

**Comment by spaulenoff** [comment]
This was ticket #207

**Comment by spaulenoff** [comment]
Verified on Prod

**Comment by skt2** [comment]
Time Spent: 30m
