### ISSUE TITLE
PROJECT: Feature Story Template 

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#27]
We would like to create a page type template in the CMS for our features stories. The design of the page should be based off of akc.org/social/veteran-service-dog-team-personify-the-importance-of-perserverance/?lSADsa.

We would need the ability to nest the URL under any directory such as /news

**Comment by pps2010** [comment]
Link provided leads to 404 error.

**Comment by stevepessah** [comment]
@elieo can you send over a new link?

**Comment by elieo** [comment]
http://www.akc.org/social/veteran-service-dog-team-personify-the-importance-of-perseverance/

**Comment by elieo** [comment]
To clarify, we just want the ability to list this template style in the news section. http://www.akc.org/news/ 

The article should also be listed in the Google news sitemap. http://www.akc.org/blog/sitemap/

**Comment by stevepessah** [comment]
@elieo so for any article in the /news/ section, you want the ability to use either the current template or this new Featured Story template?

**Comment by spaulenoff** [comment]
@kylejbertelsen Is any more information needed here?
@spaulenoff: not that I can see, no.

**Comment by skt2** [comment]
Time spent: 3h(6th Apr)
Time spent: 4h(12th Apr)
Time spent: 1h(14th Apr)

@spaulenoff : Need more clarification.

What I have understand so far is we want to show featured story(only one at a time) on /news/ template and design of the featured story should be like http://www.akc.org/social/veteran-service-dog-team-personify-the-importance-of-perseverance/ 

In above link it display the article with full description so how we want to show the featured article so it doesn't mess with news listing?

**Comment by spaulenoff** [comment]
@skt2 We just want to add a new template in the CMS that matches the format for the above linked story. That means font size, style, social button, images, etc. the above link was customly made by the content team but we want to make it easier for them to publish content formatted like this in the future.

**Comment by skt2** [comment]
Talked with @spaulenoff, It seems we need to create a new channel and new template for this.
@kylejbertelsen can you please confirm?

**Comment by kylejbertelsen** [comment]
Incorrect. As I see it (and @stevepessah and @elieo should confirm), all we want is a new generic template, selectable from the Structure tab, and any piece of content could use this newly-styled display.

**Comment by skt2** [comment]
After talking with @kylejbertelsen and @spaulenoff, Adding new template under blog group named: .featured-story and focusing on news and akc-dog-lovers article to display under this newly created template when selected.

**Comment by skt2** [comment]
Test Link: http://develop2.akc.org/news/war-dog-handler-reunite/

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev2. I checked the following pages and they seem to be looking good to me: http://develop2.akc.org/news/oscar-the-dachsie-dazzles/
http://develop2.akc.org/news/war-dog-handler-reunite/

**Comment by stevepessah** [comment]
@spaulenoff pages look good. Did you check out the other parts:
- we just want the ability to list this template style in the news section. http://www.akc.org/news/
- the article should also be listed in the Google news sitemap. http://www.akc.org/blog/sitemap/

**Comment by spaulenoff** [comment]
@stevepessah 
1. It is only an option in the news article
2. @skt2 can you confirm?

**Comment by stevepessah** [comment]
@spaulenoff @skt2 if there is an ad in the sidebar on desktop, don't display on mobile.

**Comment by skt2** [comment]
Sitemap link: http://develop2.akc.org/blog/sitemap/

**Comment by spaulenoff** [comment]
Verified on Stage

**Comment by spaulenoff** [comment]
@skt2 Sorry but we found a few additional issues that were not caught on first QA. @aalattili has found the following issues:

http://stage-ng.akc.org/news/oscar-the-dachsie-dazzles/
http://stage-ng.akc.org/news/first-2-canine-officers-recognized/

iPhone - News article, for article with new design, Facebook Comment Section  components are displaying improperly
![iphone-news - facebook comment section components display improperly](https://cloud.githubusercontent.com/assets/13648969/14536155/fe96aa42-023e-11e6-9b43-88587b37fffc.PNG)

News article, for article with new design, title of some article is partially hidden 
![news - title of some article is partially hidden](https://cloud.githubusercontent.com/assets/13648969/14536134/f0b2c0b4-023e-11e6-87f4-89865b3640f0.jpg)

Moving back to on stage until this is resolved.

**Comment by skt2** [comment]
@spaulenoff Fixed. ^

**Comment by skt2** [comment]
@spaulenoff fixed additional issue in the same ticket. you can test it on stage now. Thanks!

**Comment by AKCOsama** [comment]
@spaulenoff @skt2 QA statuses for above mentioned issues:
1. News article, for article with new design, title of some article is partially:
              QA Passed, this issue is fixed and verified on stage.
   See News Articles - Title is fully display.png snapshot 
   ![news articles - title is fully display](https://cloud.githubusercontent.com/assets/16208336/14585747/a2cbea82-0488-11e6-90bb-4610faf998fb.png)
1.  iPhone - News article, for article with new design, Facebook Comment Section components are displaying improperly:
              QA Failed, this issue still not fixed.

**Comment by skt2** [comment]
Tested Article: http://www.akc.org/news/police-dogs-protecting-their-humans/

**Comment by spaulenoff** [comment]
Verified on Prod
