### ISSUE TITLE
New ad units on /learn article pages

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#271]
# Desktop
- new 728x90 ad unit directly below top hero image
- please use the existing tan background behind the ad instead of the grey
- Mockup:
  ![desktop-v1 1](https://cloud.githubusercontent.com/assets/1063028/15303358/5eeb8a20-1b85-11e6-9399-b389ebc02a7b.png)
# Mobile
- center top ad
- place 300x250 ad after first paragraph
- Mockup:

![mobile-v1 1](https://cloud.githubusercontent.com/assets/1063028/15303359/5eedbfa2-1b85-11e6-88c4-5fa4b4dd2658.png)

**Comment by kylejbertelsen** [comment]
@stevepessah: I need the ad codes for those two ads ASAP. Please confirm that they're activated by yourbow ASAP, as well.

**Comment by spaulenoff** [comment]
@kylejbertelsen x03 for the 728x90 on desktop and x01 for the 300x250 on mobile

**Comment by kylejbertelsen** [comment]
Estimated time:
2015-05-17 - kyle - 3 hours

**Comment by spaulenoff** [comment]
@aalattili Please Qa on Dev2 and Stage

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on Dev2 & Stage, across browsers (FF 45, GC 50 & IE 11) & devices (iPad & Samsung S5).

**Comment by spaulenoff** [comment]
Pushed to Prod as part of 5/18 Release
