### ISSUE TITLE
Sitespeed - Optimize favicon

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#272]
@skt2 to discuss with Alla on how to optimize favicon further.

**Comment by skt2** [comment]
FYI: This is how I resized favicon before.
https://scotch.io/tutorials/all-favicons-for-all-devices-and-sizes

**Comment by skt2** [comment]
Time Spent: 15m

**Comment by skt2** [comment]
How to QA:
1. check the favicon display fine on different pages. 
2. view source > find favicon > click and download and see size is 1kb
3. compare with akc.org and let me know if you find any major difference

**Comment by spaulenoff** [comment]
@aalattili Please Qa on Dev2 and Stage

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting results as following:
- In Deve2 & Stage-ng --> favicon size=1.32 kb not 1 kb
- In Production --> favicon size=322 kb

**Comment by skt2** [comment]
@spaulenoff @aalattili 
![screen shot 2016-05-18 at 9 14 36 am](https://cloud.githubusercontent.com/assets/16002526/15359803/0698b208-1cd9-11e6-8d5a-d9dc8640943e.png)
