### ISSUE TITLE
Uncaught ReferenceError: jwplayer is not defined - JS Error on the pages without jwplayer

### ISSUE THREAD

**Issue by skt2** [akcdotorg/akc.org#273]
![screen shot 2016-05-18 at 2 15 01 pm](https://cloud.githubusercontent.com/assets/16002526/15370271/3c853db6-1d04-11e6-83c9-bf506d22d61b.png)

**Comment by toshan2014** [comment]
@spaulenoff 
Do you know of anywhere else where the JW player is used apart from the /content section?

**Comment by spaulenoff** [comment]
breed pages and some SEO pages

**Comment by toshan2014** [comment]
@spaulenoff 
This was being generated by an external JS ( not under our control ) and it seems that it has been fixed since we ( with Shailesh) are not seeing the error on develop2, stage or production anymore.
