### ISSUE TITLE
Center Month Dropdown on Mobile /news/ hub 

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#274]
Can we center the month dropdown on /news/ hub 
http://www.akc.org/news/
http://stage-ng.akc.org/news/

![canine partner spotlight page 2](https://cloud.githubusercontent.com/assets/13648969/15474009/d11c2226-20d0-11e6-9e2a-60c54a646780.png)

**Comment by toshan2014** [comment]
dev2 :  http://www.akc.org/news/2015/05/

**Comment by toshan2014** [comment]
Spent 20min

**Comment by toshan2014** [comment]
stg : http://stage-ng.akc.org/news/

**Comment by aalattili** [comment]
QA retest passed on dev2 & stage

**Comment by toshan2014** [comment]
pf : http://stage-ng.akc.org/news/

**Comment by toshan2014** [comment]
Spent 20min

**Comment by toshan2014** [comment]
prod : 
http://www.akc.org/news/

**Comment by aalattili** [comment]
@spaulenoff 
Tested on Samsung S5 & iPhone 6s plus verified on live site

**Comment by spaulenoff** [comment]
Verified on Prod
