### ISSUE TITLE
Intermittent issue on content hub, learn & news articles-Posting an FB comment cause an error to display

### ISSUE THREAD

**Issue by aalattili** [akcdotorg/akc.org#275]
STRs:
1. Navigate to content hub, learn articles or news articles. ex: http://stage-ng.akc.org/content/dog-breeding/videos/why-eye-tests-are-important-for-breeding-programs/
2. Enter a comment then click on 'Log in & post' button
3. In FB login pop up, login with valid credentials
4. Observe error the displayed error massage "Object Invalid Value"
5. In error msg pop up, click on 'Ok' button
6. Observe that 'Post' button is disabled & post wasn't published
7. Refresh page & observe that post is there

Notes:
- Its an intermittent issue
- Applicable on dev2 & stage
- please check the screenshot below.
  ![content hub-facebook comment-object invalid value](https://cloud.githubusercontent.com/assets/12289479/15474896/a6e68eee-210f-11e6-818f-03fdc248d06b.jpg)

**Comment by spaulenoff** [comment]
Moved to Jira
