### ISSUE TITLE
Fix Learn Hub Pages on Mobile

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#276]
http://www.akc.org/learn/
http://stage-ng.akc.org/learn/

The Learn Hub Pages are not adjusting responsively on mobile. Needs to resize the adds and tiles so they fit better on mobile.

![learn pages](https://cloud.githubusercontent.com/assets/13648969/15475711/688a1bb0-20d9-11e6-8d74-ba9c908a0ebe.png)

**Comment by toshan2014** [comment]
@spaulenoff 
For this we need to contact YourBow and ask them not to serve RM ads, instead serve resizeable ads on the learn pages as it was being done before. I can email them.

**Comment by toshan2014** [comment]
Email sent to YourBow:

> Hi Novak
> 
> We need to have non RM ads serve on the listing pages in the learn section so the ads resize on mobile devices. In the past we have used the keyword "squeezed" for this purpose.
> 
> I've differentiated the listing pages (ex http://develop2.akc.org/learn/, http://develop2.akc.org/learn/dog-health/, http://develop2.akc.org/learn/dog-health/care/ ) from the detail pages with keywords: "learn-page-listing" and "learn-page-detail"  (ex http://develop2.akc.org/learn/dog-health/can-dogs-get-lice/ ). Are you able to serve non RM ads on the pages with keyword "learn-page-listing"? Will this cause any disruption?
> 
> Please advise,
> 
> Thanks
> 
> Toshan

**Comment by toshan2014** [comment]
Reply from Yourbow:

> HI Toshan
> 
> Yes we can do that. Once this is live please let us know so we can check if all works well
> 
> Thanks!
> 
> Novak

**Comment by toshan2014** [comment]
From me:

> Are you able to set it up so we can see how it looks like on develop2 first? Thanks Novak

**Comment by toshan2014** [comment]
YourBow:

> ok, we will have to revisit most of the campaigns to accomplish this, so once done we will get back to you
> 
> Thanks!
> 
> Novak
> 
> This is completed. Now we only have images serving in learn-page-listing, so no RM will be serving there
> 
> Thanks!
> 
> Novak

**Comment by toshan2014** [comment]
dev2 : http://develop2.akc.org/learn/

**Comment by spaulenoff** [comment]
Close but can we center the pagination at the bottom on mobile portrait mode?

**Comment by toshan2014** [comment]
@sip please check again

**Comment by toshan2014** [comment]
stg: http://stage-ng.akc.org/learn/

**Comment by aalattili** [comment]
QA retest passed on dev2 & stage-ng

**Comment by toshan2014** [comment]
pf :  http://stage-ng.akc.org/learn/

**Comment by toshan2014** [comment]
Spent: 3h

**Comment by toshan2014** [comment]
prod:
http://www.akc.org/learn/
http://www.akc.org/learn/page/P10/
http://www.akc.org/learn/dog-health/
http://www.akc.org/learn/dog-health/page/P10/
http://www.akc.org/learn/dog-health/nutrition/
http://www.akc.org/learn/dog-health/nutrition/page/P10/

**Comment by aalattili** [comment]
@spaulenoff 
Tested on Samsung S5 & iPhone 6s plus verified on live site

**Comment by spaulenoff** [comment]
Verified on Prod
