### ISSUE TITLE
Make sure pages with tables are responsive

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#28]
Please provide at least 3 links to pages containing tables, preferrably of different content types (but ideally with tables placed in a somewhat 'default' manner, so we can adjust the default behavior of tables), so we can know that we have a good cross-section of pages that contain tables.

**Comment by kylejbertelsen** [comment]
Blocked until at least 3 sample links are provided.

**Comment by stevepessah** [comment]
Moved to JIRA
