### ISSUE TITLE
Update all OAS tags

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#29]
Use article.group/index.html as a guide.

Scan through template to gather the OAS positions used in that template, and add a stash variable, like so:

{exp:stash:set name="adscalled"}x36,x20,x38{/exp:stash:set}

Each template contains variables which list the available ad spaces on that page, to wit:
{exp:stash:set name="adscalled"}
x35,x37
{/exp:stash:set}
// list of ad positions in this template (templates, in this case, meaning those in (for example) article.group/index.html, or blog.group/.listing.html)
<body class="layout-training
{exp:akc_body_class:output}
{layout:templates_used}
" data-ad-slots="
{layout:adscalled}
" data-ad-site-page="/
{segment_1}" data-ad-query="{segment_1}
,
{last_segment}
"> in each of the layout.group/ templates, the body tag contains output of these layout:adscalled variables, triggering the OAS calls for the correct ad positions.

**Comment by stevepessah** [comment]
@spaulenoff can this one be removed?

**Comment by kylejbertelsen** [comment]
Closing as invalid.
