### ISSUE TITLE
Change title tag on 404 page

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#30]
Can we please change the title tag on the 404 page on akc.org to: 404 Error - American Kennel Club

This will help us keep track of 404 errors on the site via Google analytics and diagnose them. 

How to QA: go to this page, and check the title tag: http://www.akc.org/adf/ it should be what is listed above.

**Comment by toshan2014** [comment]
Please qa :  http://develop2.akc.org/zdfsfds/

**Comment by toshan2014** [comment]
Time spent: 30min

**Comment by spaulenoff** [comment]
@stevepessah Verified on dev2:
http://develop2.akc.org/content/westminster-dog-show/videos/jkdaslgsajk/
http://develop2.akc.org/events/ffdbjkgds/
http://develop2.akc.org/news/fffdhdaG/
http://develop2.akc.org/zdfsfds/

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by toshan2014** [comment]
Stage :
http://stage-ng.akc.org/zdfsfds/

**Comment by spaulenoff** [comment]
@stevepessah Please verify on stage: http://stage-ng.akc.org/dfskdfhfdsfh/
http://stage-ng.akc.org/content/westminster-dog-show/articles/fdjkafdklhg/
http://stage-ng.akc.org/content/westminster-dog-show/videos/dbnajkbdlfg/
http://stage-ng.akc.org/events/fhfdzfhd/
http://stage-ng.akc.org/news/dfhahnasfdn/

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by toshan2014** [comment]
pf : 
http://develop2.akc.org/zdfsfds/

**Comment by spaulenoff** [comment]
verified on preflight

**Comment by toshan2014** [comment]
prod http://www.akc.org/hhh

**Comment by spaulenoff** [comment]
Verified on Prod
