### ISSUE TITLE
Breed care and detail pages should use breed hero image when shared

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#32]
When sharing one of the /detail or /care links, it uses the standard AKC dog image instead of the breed image.

og:image, and other meta tags should be using the hero image URL

**Comment by skt2** [comment]
Tested here:
http://develop2.akc.org/dog-breeds/airedale-terrier/detail/
http://develop2.akc.org/dog-breeds/airedale-terrier/care/
@spaulenoff if any of the other page didn't work for you then please go to: https://developers.facebook.com/tools/debug/ -- paste that url and click debug and try again.

**Comment by skt2** [comment]
Time spent: 3h

**Comment by skt2** [comment]
Tested here:
http://stage-ng.akc.org/dog-breeds/american-hairless-terrier/detail/
http://stage-ng.akc.org/dog-breeds/american-hairless-terrier/care/

**Comment by aalattili** [comment]
QA retesting Failed on dev2 & stage as folowing, (Note that these issues are applicable on both environments)
Tested on browsers (GC 50, FF 45 & IE 11):
1- Sometimes image takes long time to load
2- For some pages, Image is missing. ex: http://develop2.akc.org/dog-breeds/alaskan-malamute/detail/
(Shared link-Missing dog breed hero image.jpg)
![shared link-missing dog breed hero image](https://cloud.githubusercontent.com/assets/12289479/15454130/f986973a-2037-11e6-8acf-2c79d0f5042a.jpg)
3- For Some page unclear Image is displaying. ex: http://stage-ng.akc.org/dog-breeds/affenpinscher/detail/
(Shared link-Un clear image.jpg)
![shared link-un clear image](https://cloud.githubusercontent.com/assets/12289479/15454309/d40d85b2-203d-11e6-835d-d5580d91758d.jpg)
4- For Some pages, image for breed not related to the shared link is displaying. ex: http://develop2.akc.org/dog-breeds/airedale-terrier/detail/
(Shared link-Not hero image is displaying.jpg)
![shared link-not hero image is displaying](https://cloud.githubusercontent.com/assets/12289479/15454333/7a305c1c-203e-11e6-8845-52fc48b3cf5c.jpg)

**Comment by skt2** [comment]
Tested here:
http://www.akc.org/dog-breeds/airedale-terrier/detail/
http://www.akc.org/dog-breeds/airedale-terrier/care/
Note: if any of the other page didn't work for you then please go to: https://developers.facebook.com/tools/debug/ -- paste that url and click debug and try again.
@aalattili @spaulenoff

**Comment by spaulenoff** [comment]
Verified on Prod
