### ISSUE TITLE
Remove unnecessary step on mobile when navigating from homepage to browse all breeds page 

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#33]
https://akcorg.atlassian.net/browse/AKC2-137

**Comment by spaulenoff** [comment]
When navigating on mobile from the homepage to the breeds page, there is an unnecessary step After clicking breeds, you get brought to the following page:

![image](https://cloud.githubusercontent.com/assets/13648969/13399262/7080c0da-ded0-11e5-8270-1e48a4927a65.png)
Once you click Browse All Breeds, you are brought to the next, unnecessary page:

![image](https://cloud.githubusercontent.com/assets/13648969/13399275/7f455fc2-ded0-11e5-9aaf-e266b6eb3482.png)

Can we remove step 2 and just go directly from clicking browse all breeds to the breeds page?

**Comment by skt2** [comment]
Time Spent: 1h

**Comment by skt2** [comment]
**CMS Changes**
Snippet Update: {snip-header}

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on dev2 & stage, 'All Breeds' link is removed- Tested on devices (Samsung tab, iPhone 6s plus & Samsung galaxy S6)

**Comment by aalattili** [comment]
@spaulenoff 
Verified on production.
Tested on Iphone s6 plus and Samsung s5.

**Comment by spaulenoff** [comment]
Verified on Prod
