### ISSUE TITLE
When clicking on National Breed Club on Breed Pages – this action should open a new window and not close our site. The same action should occur for users clicking on ‘Local Clubs’. 

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#34]
https://akcorg.atlassian.net/browse/AKC2-255

**Comment by spaulenoff** [comment]
When clicking on National Breed Club (screen shot below) on Breed Pages – this action should open a new window and not close our site. The same action should occur for users clicking on ‘Local Clubs’. 
![image](https://cloud.githubusercontent.com/assets/13648969/13399306/9e8ee8f8-ded0-11e5-8d6c-83537f897809.png)

**Comment by spaulenoff** [comment]
Closing as this is already on live site
