### ISSUE TITLE
Ad alignment on breed detail page

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#35]
https://akcorg.atlassian.net/browse/AKC2-205

**Comment by spaulenoff** [comment]
Can we center the ad placement on the breed detail page? It is currently shown as below:
![image](https://cloud.githubusercontent.com/assets/13648969/13399332/bade3734-ded0-11e5-8936-7bf7913f5349.png)

http://www.akc.org/dog-breeds/golden-retriever/care/#grooming

**Comment by spaulenoff** [comment]
Closed and resolved as part of #214
