### ISSUE TITLE
Firefox loads non-mobile version of site on Android phone

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#36]
Firefox loads non-mobile version of site on Android phone. Possible cause: user-agent is outdated?
FF v. 42.0.2 / Sony Xperia

User-agent is unlikely, because we do no browser-sniffing. I'd bet google searching 'android firefox mobile version' or similar would give clues.

![screenshot_2015-12-11-10-51-06](https://cloud.githubusercontent.com/assets/1063028/13357995/050a6b5a-dc7b-11e5-8889-d6ad70c29c67.png)

**Comment by kylejbertelsen** [comment]
Most-likely that FF is reporting the dimensions of the window incorrectly. Please record your findings (and any solution) in the wiki.

**Comment by stevepessah** [comment]
Moved to JIRA
