### ISSUE TITLE
Issue with table spacing on generic template on mobile

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#37]
There is an issue with table spacing on mobile
exmple URL: http://www.akc.org/dog-breeders/bred-with-heart/health-testing-requirements/#Affenpinscher

IMPORTANT: describe the 'issue' -- do not rely on others to interpret such an ambiguous description. As it stands, I would reject this issue.

**Comment by kylejbertelsen** [comment]
Blocked until the issue is either described, or a good screenshot is attached.

**Comment by stevepessah** [comment]
Moved to JIRA
