### ISSUE TITLE
You vs. Breed "Not Steve Pessah" link not working

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#38]
If you login to Facebook for You vs. Breed, the link above the image doesn't work. Goes here - http://www.akc.org/you-vs-breed/#

Kyle: This would be the link by which we trigger the login. Possible that we'd want to use that link to log-out of Gigya, and re-trigger the Gigya log-in

**Comment by kylejbertelsen** [comment]
I can't seem to locate this link. Please screenshot it.

**Comment by stevepessah** [comment]
Moved to JIRA
