### ISSUE TITLE
Consistent letter sizes in mobile pagination

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#39]
On the /dog-breeds pages on mobile, the paginated letters are different widths. Can we make these uniform and try and get 13 on each line so it looks cleaner?

![img_2961 1](https://cloud.githubusercontent.com/assets/1063028/13358073/79f1ac4e-dc7b-11e5-9b1c-36a062a04c9e.png)

**Comment by kylejbertelsen** [comment]
The only way to do this is to use a monospaced font. Do we have a monospaced font we use? We should have one, but I think we don't have one that we've standardized-on. Courier or Andale Mono are choices. Please pick one, and we'll move ahead.

**Comment by stevepessah** [comment]
Moved to JIRA
