### ISSUE TITLE
SEO: Author & Publisher OG Tags

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#4]
![screen shot 2016-02-25 at 4 53 04 pm](https://cloud.githubusercontent.com/assets/1063028/13335688/4a8b8218-dbe0-11e5-9e98-d0134f7d5d01.png)

Lets add in some Open Graph data to get our authors bio linked.  

See more: 

http://garage.socialisten.at/2013/06/new-open-graph-tags-for-article-publisher-author/
https://developers.facebook.com/docs/reference/opengraph/object-type/article

Can we add the following code the head section:

<meta property="article:publisher"
      content="https://www.facebook.com/americankennelclub" />
<meta property="article:author"
      content="https://www.facebook.com/[author-link]" />

https://www.facebook.com/[author-link] - This variable should be tied to the author's profile page. 

Authors should be able to add their Facebook URL in the backend settings

**Comment by kylejbertelsen** [comment]
If /content -- the meta tags are applied in embeds.group/content-headers.html

If elsewhere -- find 'em -- possibly in each layout.group/*, minus training and photo-gallery

**Comment by toshan2014** [comment]
"Author facebook screenname" field added to Media and Articles channels.

Please QA : 

view-source:https://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0

view-source:https://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Comment by spaulenoff** [comment]
@toshan2014 How do you add in a an author in the CMS? Not seeing 
Also can you please add this functionality to /news/, /akc-dog-lovers/ and /learn/ articles
Also still seeing by American Kennel Club when i try to share
![image](https://cloud.githubusercontent.com/assets/13648969/13672624/a3b43876-e6a3-11e5-8486-b3e7e83a6423.png)

**Comment by toshan2014** [comment]
@spaulenoff OPTION 1: I need to know whether we want to have a new channel where authors and their facebook can be entered. Upon publishing the author can be chosen from a drop-down list like:
<img width="927" alt="authors" src="https://cloud.githubusercontent.com/assets/6847220/13691411/7a55f6dc-e6ed-11e5-978a-70fdeaf158d0.PNG">

OR
OPTION 2: Use the existing/automated {author} field which uses the login profile details of the person who published the article. However this option will need every author to log in the system and enter their facebook URL in their profile (My account > Edit Profile). 

I would suggest OPTION 2 if we want this change in /news and /akcdoglovers  as they are already using OPTION 2. Choosing OPTION 1 could mean changing all articles in those sections and assigning an author from the dropdown.

Advantage of OPTION 1: On the long run, it makes things more flexible.

Your call.

**Comment by toshan2014** [comment]
Going with OPTION 1 after scrum consensus: 

Content - Article : https://develop2.akc.org/content/westminster-dog-show/articles/author-fb-test-article/

Content - Video : https://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/

Content - Photos : https://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=0

News: http://develop2.akc.org/news/new-device-helps-monitor-guide-dog-health-well-being/

akc-dog-lovers: https://develop2.akc.org/akc-dog-lovers/why-the-miniature-american-shepherd-would-win-the-dog-olympics/

**Comment by spaulenoff** [comment]
@toshan2014 Looks Good on my end, can you please confirm these updates have been made on /news/ articles and /akc-dog-lovers/ articles?
/news/ - https://develop2.akc.org/news/dog-finds-lost-toddler-in-woods/
/akc-dog-lovers/ - https://develop2.akc.org/akc-dog-lovers/why-the-miniature-american-shepherd-would-win-the-dog-olympics/

**Comment by spaulenoff** [comment]
Per convo with ELie, we have decided to switch to option 2

**Comment by toshan2014** [comment]
Now using built-in member module ( Option 2 ) :

IMPORTANT Note:  Every Author will need to log in and update their profile with the following:
1) Edit Profile > AOL IM ( Put your facebook or other social media profile URL here)
2) Username and Password > Screen Name ( this is the name you want to appear on social media )

Example:
https://develop2.akc.org/content/westminster-dog-show/articles/author-fb-test-article/
https://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/
https://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=0
https://develop2.akc.org/news/dog-finds-lost-toddler-in-woods/
https://develop2.akc.org/akc-dog-lovers/why-the-miniature-american-shepherd-would-win-the-dog-olympics/

**Comment by spaulenoff** [comment]
@toshan2014 Per Discussion, please make the AOL IM field to be Facebook Profile Field

**Comment by toshan2014** [comment]
@spaulenoff Change made - sorry did not realize it was a simple text change in some file.

**Comment by spaulenoff** [comment]
@toshan2014 /news/ and /akc-dog-lovers/ doesnt seem to be working properly
https://develop2.akc.org/news/dog-finds-lost-toddler-in-woods/
https://develop2.akc.org/akc-dog-lovers/why-the-miniature-american-shepherd-would-win-the-dog-olympics/

Getting this error on the Facebook Dubugger Tool (https://developers.facebook.com/tools/debug/og/object/):
![image](https://cloud.githubusercontent.com/assets/13648969/13715093/b9fd60be-e7a0-11e5-8e22-f0c652565a81.png)

**Comment by spaulenoff** [comment]
Nevermind its working properly now once i remove the https: @elieo and @stevepessah  Please confirm on Dev2:
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/
http://develop2.akc.org/content/westminster-dog-show/articles/author-fb-test-article/
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video/
http://develop2.akc.org/akc-dog-lovers/why-the-miniature-american-shepherd-would-win-the-dog-olympics/
http://develop2.akc.org/news/dog-finds-lost-toddler-in-woods/

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by toshan2014** [comment]
please verify on stg

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage
http://stage-ng.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0
http://stage-ng.akc.org/content/westminster-dog-show/videos/westminster-test-video/
http://stage-ng.akc.org/content/westminster-dog-show/articles/masters-agility-and-obedience-results/

**Comment by toshan2014** [comment]
pf:

http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/
http://develop2.akc.org/content/westminster-dog-show/articles/author-fb-test-article/
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video/
http://develop2.akc.org/akc-dog-lovers/why-the-miniature-american-shepherd-would-win-the-dog-olympics/
http://develop2.akc.org/news/dog-finds-lost-toddler-in-woods/

**Comment by spaulenoff** [comment]
@toshan2014 Verified on prod. Please add comment with time tracking

**Comment by toshan2014** [comment]
Spent around: 6h ( option2 was chosen over option1 mid-progress affecting the initial estimate )
