### ISSUE TITLE
On the android device(Android - Samsung) sometimes "Sign Out" button is not clickable.

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#40]
When tried to click on "Sign Out", Nothing happens.

**Comment by toshan2014** [comment]
@spaulenoff 
I've been checking on this on both my cell and browserstack and can't replicate since the fix for #41 was applied. Can you confirm?

**Comment by spaulenoff** [comment]
ya im seeing it working fine now on browserstack.

**Comment by toshan2014** [comment]
stage: checked on my cell and bs, seems to be working fine

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on dev2 & stage across devices (Samsung galaxy S6 & Samsung Tab).

**Comment by toshan2014** [comment]
No change made - Fixed as part of #41

**Comment by aalattili** [comment]
@spaulenoff 
Not verified on prod, Tested on Samsung s5
Clicking on user name doesn't open the menu

**Comment by toshan2014** [comment]
tested ok on samsung s6 ( browserstack )

**Comment by aalattili** [comment]
@spaulenoff @toshan2014 
failed due to an issue on opening the menu

Ticket is verified on prod
