### ISSUE TITLE
Mobile: User menu popup never comes up

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#41]
It is very hard to get user menu on the Android devices(Samsung - Galaxy), When tried to touch user icon or display name after sign-in, it just redirect to market place page. It never popup the user menu.

**Comment by kylejbertelsen** [comment]
Probably do this in-conjunction with #40

**Comment by skt2** [comment]
@spaulenoff @kylejbertelsen 
User Menu is wrapped with Anchor tag so on mobile devices it always execute click event before touch or tap event and since it is link, it redirect to apps page. We might need to remove link from user menu and add additional link in "My Account" section i.e. Account Overview

**Comment by skt2** [comment]
@spaulenoff give it a try. Once logged, look for link My Account > Account Overview.
Don't worry about the link showing on desktop as well, once this changes is approved and if we still don't want link on desktop then I can find something to hide link on desktop view.

**Comment by skt2** [comment]
Time Spent: 5h

**Comment by skt2** [comment]
**CMS Changes**
CMS > Content > Edit > MyAKC Navigation
Add new link under My Account:
Label:Account Overview 
Link: //apps.akc.org/apps/online_accounts/index.cfm
Move it to top

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed across devices (Samsung galaxy S6 & Samsung Tab)-(Passed - User menu popup is working fine.jpg)
![passed - user menu popup is working fine](https://cloud.githubusercontent.com/assets/12289479/15462537/10815e22-20cc-11e6-92ed-122550a8e151.jpg)

**Comment by aalattili** [comment]
@spaulenoff ,
Menu need double click to open

**Comment by spaulenoff** [comment]
not working when tried on Browserstack Galaxy S6

**Comment by skt2** [comment]
@spaulenoff what do you mean by not working? This is what I got when I test it.
![screen shot 2016-05-26 at 4 34 17 pm](https://cloud.githubusercontent.com/assets/16002526/15589178/b744caf6-235f-11e6-98ae-acf90481479b.png)

**Comment by spaulenoff** [comment]
Seeing it now. Verified on Prod
