### ISSUE TITLE
SEO: Change sitemap

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#44]
Change sitemap declaration on this XML sitemap.  Currently, it is set as a video sitemap, and it needs to be set as a regular sitemap. 

http://www.akc.org/homepage/compare-breeds-xml/

**Comment by skt2** [comment]
@stevepessah by regular sitemap you mean this:
`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">`

**Comment by skt2** [comment]
Time spent: 30m
Tested Here: http://develop2.akc.org/homepage/compare-breeds-xml/

**Comment by spaulenoff** [comment]
Its looking good to me, @elieo Can you please confirm this XML sitemap is now functioning properly?
Tested Here: http://develop2.akc.org/homepage/compare-breeds-xml/

**Comment by spaulenoff** [comment]
Verified on Dev2

**Comment by aalattili** [comment]
@spaulenoff 
QA retesting passed on stage & dev2.

**Comment by aalattili** [comment]
@spaulenoff ,
Verified on live site

**Comment by spaulenoff** [comment]
Verified on Prod
