### ISSUE TITLE
SEO: RSS for editorial picks 

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#5]
Need to create a RSS feed of articles from the news section that are our "editorial picks". We will use this feed to get our news content featured on Google News. (see example feed attached) 
[editorial-picks-rss-feed-example.docx](https://github.com/akcdotorg/akc.org/files/147333/editorial-picks-rss-feed-example.docx)

https://support.google.com/news/publisher/answer/1407682#general 

We will need the functionality in the CMS to specify which articles we want to feature in this editorial picks RSS feed. 

Articles should expire after 48 hours atomically, and be removed from the RSS Feed. We will need a logo in the feed (attached) 

![really-small-logo](https://cloud.githubusercontent.com/assets/1063028/13335742/8c25cff8-dbe0-11e5-8ead-8a497ac81004.gif)

**Kyle to discuss process with Elie.**
Options:
- new field (checkbox, checked by default for inclusion)
- Add as an AKC Vocabulary term, to be set on 'categories' tab
- Add as an Extra Metatags term, to be set on 'categories' tab

Questions:
- Is there a desired URL for this rss feed?
- Is there somewhere we want to register the eventual URL?
- Is there a minimum/maximum number of results in this feed?

**Comment by spaulenoff** [comment]
Added to Jira
