### ISSUE TITLE
Usability Inadvertent Errors

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#50]
Created the following Google Doc to help track issues that we find on account of the Usability tickets
https://docs.google.com/spreadsheets/d/1RkCbmJ2GtiX6j8ObhMojzfZzltMTXQP51-NZrmh8dSc/edit?usp=sharing
Please add to that list as you find issues

**Comment by spaulenoff** [comment]
ticket was pushed with usability updates
