### ISSUE TITLE
Video/Article/Photo Gallery: Implement Social Share Counters

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#51]
https://akcorg.atlassian.net/browse/AKC2-550

**Comment by spaulenoff** [comment]
Need to implement social share counters on article, Video and Photo Gallery pages: http://www.akc.org/media/article/gail-miller-bisher-takes-communications-reins-from-david-frei
http://stage-ng.akc.org/content/westminster-dog-show/photo-galleries/cuties-dog-breeds/?photo_id=0
http://stage-ng.akc.org/content/westminster-dog-show/videos/video-of-dogs/

Should look like this: 
![photo gallery social buttons](https://cloud.githubusercontent.com/assets/13648969/13398577/fdb88b62-decc-11e5-9f2e-d72e6bb0203a.JPG)

**Comment by skt2** [comment]
@spaulenoff There is caching time after how long the counter should updated. It was set to 1 day before which I have changed(after talking with @kylejbertelsen ) to 10 min. so can you please confirm this once and let me know me what exact time we want to set for this?

**Comment by spaulenoff** [comment]
@skt2 once every 24 hours is preferred. If you need to make it more often just to test it is working correctly thats fine. But ultimately we only want it to update once every 24 hours

**Comment by skt2** [comment]
Example: http://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

**Comment by spaulenoff** [comment]
@skt2 Its working for me, but i am only seeing one share. I though I shared on facebook and pinterest. Can you please confirm its working for you as well?

**Comment by spaulenoff** [comment]
@skt2 Can't test on prod as it is a 24 hour counter. Please add time tracking to this ticket

**Comment by skt2** [comment]
Time Spent: 5h
