### ISSUE TITLE
Category Page - Mobile: Left Navigation not working correctly

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#52]
https://akcorg.atlassian.net/browse/AKC2-549

**Comment by spaulenoff** [comment]
Mobile left navigation not workig on category pages (see mockups for reference). Needs to be added in and based off of wygwam content if possible.
![image](https://cloud.githubusercontent.com/assets/13648969/13399395/12189990-ded1-11e5-8aac-4dbbba1a8d9e.png)

Expanded:
![image](https://cloud.githubusercontent.com/assets/13648969/13399404/21b68402-ded1-11e5-966f-2e03bbadb698.png)

**Comment by spaulenoff** [comment]
From Simon Paulenoff 2/16/16 4:47pm: Kyle J Bertelsen Needs to have this mobile nav that it doesn't currently have
![image](https://cloud.githubusercontent.com/assets/13648969/13399439/4e6cbba6-ded1-11e5-8581-9c283d395b91.png)

Needs to be related to the links on the desktop pages

**Comment by kylejbertelsen** [comment]
@spaulenoff : define what is the way it shouldn't be, and what the way it should be is. Please don't bounce ppl all over the internet to understand what they're to do.

**Comment by spaulenoff** [comment]
Currently there is no navigation the category pages on mobile. We want it to work as it is in the mockup above

**Comment by stevepessah** [comment]
(Related to https://github.com/akcdotorg/akc.org/issues/98)

**Comment by spaulenoff** [comment]
@kylejbertelsen Not Verified as there isn't a way to minimize this navigation on mobile and categories with mores ub categories move all the way down the page on mobile http://develop2.akc.org/content/dog-health/
![image](https://cloud.githubusercontent.com/assets/13648969/13783718/d5c5a5a4-eaa2-11e5-982d-6b4d99eb1ad8.png)

**Comment by kylejbertelsen** [comment]
Instructions:

To toggle all side-navigation, tap/click 'Related Links' (perhaps some instruction, such as 'click to see all' would be wise --- that'd be my take, anyway)

Each heading there (ex: Entertainment, Dog Health) is toggled in the same manner as the bottom nav on mobile.

**Comment by spaulenoff** [comment]
@kylejbertelsen As discussed please include symbols to show that usercs can expand and minimize the navigation

**Comment by spaulenoff** [comment]
@elieo @stevepessah Please QA on Dev 2 mobile http://develop2.akc.org/content/westminster-dog-show/ (Category Page)
http://develop2.akc.org/content/breeders/science/ (Sub Cat Page)

Please note, it will not match up styling wise with the mockup, but the functionality is there

**Comment by spaulenoff** [comment]
@kylejbertelsen Per our Conversation, Please make the following updates:
- Match the styling of CATEGORIES to the styling of learn in the mockup
  ![pasted image at 2016_03_15 04_29 pm](https://cloud.githubusercontent.com/assets/13648969/13813189/94b926e4-eb56-11e5-94fd-0cae248b994c.png)
- Add lines to break up the expand categories and sub categories like mockup
- Add Line above the top category to further differentiate between the CATEGORY header and the individual categories
- Match the category pixel height to the pixel height of the subcategories

**Comment by spaulenoff** [comment]
@kylejbertelsen Verified on Dev 2

**Comment by spaulenoff** [comment]
@kylejbertelsen Verified on Prod. Please add ticket with time tracking for this ticket

**Comment by spaulenoff** [comment]
@kylejbertelsen Verified on Prod. Please add ticket with time tracking for this ticket

**Comment by kylejbertelsen** [comment]
Approx. time spent: 16 hours, over estimate because of in-progress direction changes.
