### ISSUE TITLE
Photo Gallery Page - Mobile: Title of photo-gallery and circled arrows below gallery are not in correct styling

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#54]
Should look like this: https://akcorg.atlassian.net/secure/attachment/14882/14882_mobile+photo+title.JPG

Currently looks like this: http://develop2.akc.org/media/view/test-photo-gallery/?photo_id=0

**Comment by toshan2014** [comment]
@spaulenoff Looks like another old ticket. I remember fixing this. Look fine on develop2. Please confirm.

**Comment by spaulenoff** [comment]
Confirmed will close
