### ISSUE TITLE
BUG: FSS and Miscellaneous are missing from the Dog Groups dropdown under Breeds

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#55]
These need to be added back in there.

**Comment by toshan2014** [comment]
Please QA :
https://develop2.akc.org

**Comment by toshan2014** [comment]
Time spent: 30min

**Comment by spaulenoff** [comment]
@stevepessah Currently These are listed in alphabetical order on dev2:
1. FSS
2. Herding
3. Hound
4. Miscellaneous
5. Non Sporting
6. Sporting
7. Terrier
8. Toy
9. Working

Can you please confirm where you want FSS and Miscellaneous placed, I am thinking at the bottom of the list under working so it would go:

...Working, Miscellaneous, FSS

**Comment by stevepessah** [comment]
@spaulenoff it should be FSS, Misc at the end.

**Comment by spaulenoff** [comment]
@toshan2014 Please adjust the list to follow:
1. Herding
2. Hound
3. Non Sporting
4. Sporting
5. Terrier
6. Toy
7. Working
8. FSS
9. Miscellaneous

**Comment by toshan2014** [comment]
Order change - please check : https://develop2.akc.org/

**Comment by spaulenoff** [comment]
@stevepessah I am seeing it working for me. Please verify on dev2

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by toshan2014** [comment]
stage -
http://stage-ng.akc.org/

**Comment by spaulenoff** [comment]
@stevepessah Please verify on stage

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by toshan2014** [comment]
verified on pf

**Comment by spaulenoff** [comment]
Verified on Pre-Flight

**Comment by toshan2014** [comment]
Time spent: 1h

**Comment by toshan2014** [comment]
verified on prod

**Comment by spaulenoff** [comment]
Verified on Prod
