### ISSUE TITLE
Tablet Header Nav Covers Sign in/MyAKC

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#57]
Tablet Header Nav Covers Sign in/MyAKC in landscape mode

![tablet nav covers sign in](https://cloud.githubusercontent.com/assets/1063028/13364960/3f2798a6-dca0-11e5-9d8c-cf1ea2c6de59.JPG)

**Comment by kylejbertelsen** [comment]
@toshan2014: repair for the existing CSS, and add a comment to this ticket explaining what you did to fix it: we'll want to replicate that fix in the Compass/Foundation SCSS as well.

**Comment by toshan2014** [comment]
Fix: changed padding-left: 10em --> 6em in public_html/src/scss/components/_nav.scss

```
@media screen and (min-width: 64em)
body.not-learn-page .main-nav .top-level-nav {
    padding-top: 2.3em;
    padding-left: 6em; 
}
```

**Comment by toshan2014** [comment]
Time spent: 30min

**Comment by toshan2014** [comment]
Please QA : http://develop2.akc.org/

**Comment by toshan2014** [comment]
stage : http://stage-ng.akc.org/

**Comment by toshan2014** [comment]
pf :
 http://develop2.akc.org/

**Comment by skt2** [comment]
Time Spent: 30m

**Comment by spaulenoff** [comment]
Verified on Prod
