### ISSUE TITLE
General UI issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#58]
https://akcorg.atlassian.net/browse/AKC2-286

**Comment by AKCOsama** [comment]
Hi @spaulenoff, here are some issues compatible on stage environment and looks good on develop2:
1. Learn - Article size isn't standardized, the size of article depends on how long the title is [see Learn - Articles size.png snapshot.]
   ![learn - articles size](https://cloud.githubusercontent.com/assets/16208336/14418921/be6357ca-ffca-11e5-9e0a-d73cbc419f7c.png)
2. Learn - Drop down list have no style and some options (links/text) are partially hidden,
   also these options don't redirect to any chosen page [see Learn - Drop down list.png snapshot.]
   ![learn - drop down list](https://cloud.githubusercontent.com/assets/16208336/14418973/13dc0f08-ffcb-11e5-8536-cc9e054f6dc4.png)
