### ISSUE TITLE
SEO: Add custom GA dimensions to AKC.org 

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#6]
We would like to push custom data to Google Analytics to make our reporting better on akc.org. We would like to add data regarding the Author of a URL and the Date it was published. 

We need to add the following codes to the current GA tracking code. The dimensionValue will need replaced with the variable. 

Author 
var dimensionValue = 'SOME_DIMENSION_VALUE';
ga('set', 'dimension1', dimensionValue);

Date Published
 var dimensionValue = 'SOME_DIMENSION_VALUE';
ga('set', 'dimension2', dimensionValue);

This needs to be done in Tag manager. This would be a good article to read: https://support.google.com/analytics/answer/6164990?hl=en

**Comment by stevepessah** [comment]
**Open questions:**
- Could I get the desired URL for this sitemap?
- Is this a request for a new sitemap, or a replacement for an existing one?

Edit kjb: What? I don't see anything in this ticket that has anything to do with a site map -- was this comment intended for a different ticket?

**Comment by kylejbertelsen** [comment]
Need confirmation on the names of the GA variables -- are 'dimension1' and 'dimension2' the actual, for-real names we'd be sending to GA?
