### ISSUE TITLE
Compare Breeds - Issue when there is limited data on the breed on Results page

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#62]
https://akcorg.atlassian.net/browse/AKC2-405

**Comment by spaulenoff** [comment]
Replace A with N/A when no information is provided for a trait

![image](https://cloud.githubusercontent.com/assets/13648969/15229679/22ea9b1a-1860-11e6-9c48-89645a5d255e.png)

**Comment by spaulenoff** [comment]
Moved to Jira
