### ISSUE TITLE
SEO: Add News and Updates to SEO pages 

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#64]
https://akcorg.atlassian.net/browse/AKC2-411

**Comment by spaulenoff** [comment]
Can we please add a "news and update" section to the right sidebar on the Main SEO pages. We also want to remove the 300x 600 ad unit on the top of the page. This change should apply to all SEO pages (include sub pages, such as http://www.akc.org/dog-breeds/smallest-dog-breeds/)
See screenshot attached.
![image](https://cloud.githubusercontent.com/assets/13648969/13401343/c0c9f7d8-ded9-11e5-9f76-0964bf86de3b.png)

**Comment by toshan2014** [comment]
Please QA : 
http://develop2.akc.org/dog-breeds/smallest-dog-breeds/
http://develop2.akc.org/dog-breeds/

**Comment by toshan2014** [comment]
Time spent: 1h30min

**Comment by spaulenoff** [comment]
@stevepessah Please verify on develop2 (it will be on the right rail under the first 200x250):
http://develop2.akc.org/dog-breeds/
http://develop2.akc.org/dog-breeds/smallest-dog-breeds/
http://develop2.akc.org/dog-breeds/groups/terrier/
http://develop2.akc.org/dog-breeds/largest-dog-breeds/
http://develop2.akc.org/dog-breeds/best-family-dogs/

**Comment by stevepessah** [comment]
Verified on dev2.

@spaulenoff I saw two pages still have the 300x600 ad unit. Is that being taken care of in another ticket? If so, this can be moved to the Verified on Dev2 pipeline.

**Comment by stevepessah** [comment]
Verifying.

**Comment by toshan2014** [comment]
Stage :
http://stage-ng.akc.org/dog-breeds/smallest-dog-breeds/
http://stage-ng.akc.org/dog-breeds/

**Comment by spaulenoff** [comment]
@stevepessah Please QA on stage: http://stage-ng.akc.org/dog-breeds/largest-dog-breeds/
http:http://stage-ng.akc.org/dog-breeds/groups/hound/
http://stage-ng.akc.org/dog-breeds/best-dogs-for-kids/
http://stage-ng.akc.org/dog-breeds/
http://stage-ng.akc.org/dog-breeds/?letter=M

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by toshan2014** [comment]
pf:
http://develop2.akc.org/dog-breeds/smallest-dog-breeds/
http://develop2.akc.org/dog-breeds/

**Comment by spaulenoff** [comment]
Verified on PF

**Comment by toshan2014** [comment]
verified on prod - @spaulenoff please double check
http://www.akc.org/dog-breeds/smallest-dog-breeds/

**Comment by spaulenoff** [comment]
Verified on Prod
