### ISSUE TITLE
Need ability to save and input saved sidebar navs

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#65]
We need the ability in the CMS to add and save sidebar navigation links for use in future articles. In generic 2, you can add sidebar navigation, but you have to input the navigation links with each new article. We want to be able to to create articles and just input a saved side navigation bar from a past generic 2 template page such as http://www.akc.org/events/aenc/2015-aenc-results/

Time Spent: 1.5h(22 Apr)

**CMS Changes**
CMS > Channel > Channel Fields > SEO Overview > Create New Field
Type: Relationships
Label: Sidebar Menu
Name: seo_overview_sidebar_menu_links
Select channels to relate: Sidebar Navigation
Limit entries by category: Any
Authors:  Any
Limit entries by status: Open

CMS > Channel > Channel Fields > SEO Pages > Create New Field
Type: Relationships
Label: Sidebar Menu
Name: seo_sidebar_menu_links
Select channels to relate: Sidebar Navigation
Limit entries by category: --- Any ---
Authors: --- Any ---
Limit entries by status: Open

**Comment by spaulenoff** [comment]
Time Spent: 1.5h(22 Apr)

Is this the same as #3?

**Comment by kylejbertelsen** [comment]
Create a new content type, and allow it to be inserted into various other content types. @spaulenoff: please determine which content-types. Obviously Articles is one, maybe Generics? Etc?

**Comment by spaulenoff** [comment]
@kylejbertelsen This would mainly be used for Generic 2 templates as well as SEO Pages.

**Comment by skt2** [comment]
@stevepessah @spaulenoff do We want this for SEO Overview pages as well? http://www.akc.org/dog-breeds/

**Comment by spaulenoff** [comment]
That ability will be helpful yes.

**Comment by skt2** [comment]
NOTE: http://develop2.akc.org/dog-breeds/ -- This page is cached so every time you change menu, you need to clear the cache. @spaulenoff

**Comment by skt2** [comment]
Tested here: http://stage-ng.akc.org/dog-breeds/smartest-dogs/

**Comment by spaulenoff** [comment]
Verified on Prod
