### ISSUE TITLE
Add tracking to See more button in UGC section on breed pages

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#66]
https://akcorg.atlassian.net/browse/AKC2-229

**Comment by spaulenoff** [comment]
Kyle Bertelson 1/5/16 12:32pm:
So, we want to add some kind of tracking of the actual clicks. Can G.A. do that? If so, how?
Developer who tackles this: please document the process in comments here. I want both how-to research links, and preferably some sample markup of the implementation in the page.
