### ISSUE TITLE
Maintenance: Make closed pages 404  

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#67]
We need to make sure all closed pages in the CMS 404 on the front end. 

Example of pages that are closed in the backend, but are live on the front end: 

http://www.akc.org/dog-breeds/dachshund-smooth/
http://www.akc.org/dog-breeds/corgi/
http://www.akc.org/dog-breeds/laborador/ 

How to QA: 
1) Click links above and if you get a 404 page
2) Close an entry in each channel group and make sure that you get the 404 page on the font end, after the entry has been closed.

**Comment by spaulenoff** [comment]
Moved to Jira
