### ISSUE TITLE
SEO: XML Sitemaps

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#7]
1) We need to create a regular XML sitemap that include all pages on akc.org each pages should also list the respective images on the page. 

This sitemap should: 
not include pages from the compare breed app (http://www.akc.org/find-a-match/compare-breeds/)
and not include AKC News (http://www.akc.org/news/)
and not include any apps.akc.org pages.

https://support.google.com/webmasters/answer/183668?hl=enhttps://support.google.com/webmasters/answer/178636?hl=en

**Comment by spaulenoff** [comment]
Per @elieo Please include new content hub

**Comment by pps2010** [comment]
I have a tool that can generate the sitemap....we should review the output and make sure it looks good before we implement. May have to limit which images show up in the sitemap. here's an example for one page. (attached).
[sitemap.txt](https://github.com/akcdotorg/akc.org/files/198601/sitemap.txt)

**Comment by kylejbertelsen** [comment]
Look in JIRA for previous tickets involving the sitemap -- there are likely to be tips in there for generating/changing this.

**Comment by kylejbertelsen** [comment]
Look through old JIRA tickets for times we'd edited the sitemap in the past. See if there's tips to be had in there.

**Comment by pps2010** [comment]
I also noticed that a lot of the pages have images defined in the background - my tool is not picking those up. e.g on the homepage 
<li class="slide" style="background: url(http://cdn.akc.org/akcdoglovers/Norwich_Terrier_163X140.jpg) no-repeat center center; background-size: cover; -ms-behavior: url(/bower_components/background-size-polyfill/backgroundsize.min.htc);">
                    <a href="/dog-breeds/norwich-terrier/">
                        <span class="name">Norwich Terrier</span>
                    </a>
                </li>

**Comment by pps2010** [comment]
I have discussed with Elie and he is aware of the issue with background images. He is ok with us not generating the images for the sitemap. I am also updating the description of this issue with another section he does not want us to generate a sitemap for viz. AKC News (http://www.akc.org/news/)

**Comment by skt2** [comment]
Sitemap tickets on JIRA: https://akcorg.atlassian.net/issues/?jql=text%20~%20%22sitemap%22

**Comment by pps2010** [comment]
Sitemap as of 4/12/2016 uploaded here. I suggest we add this to our source code that would deploy to the site (the XML file) and provide Elie with a link for the same. Then we can update the sitemap on a regular basis. Discuss in the next standup.

[AKC.ORG-sitemap-2016-04-12.xml.txt](https://github.com/akcdotorg/akc.org/files/216072/AKC.ORG-sitemap-2016-04-12.xml.txt)
[AKC.org-sitemap-2016-04-12.csv.txt](https://github.com/akcdotorg/akc.org/files/216073/AKC.org-sitemap-2016-04-12.csv.txt)

**Comment by pps2010** [comment]
Please use this site map (attached here) and save it on the site as sitemap.xml (can be in the root folder). The URL for this file must be added to Google Search Console. 
This file is generated using a link checker - so it only surfaces links to pages on the site. 
[AKC.ORG-sitemap-2016-04-12.txt](https://github.com/akcdotorg/akc.org/files/219025/AKC.ORG-sitemap-2016-04-12.txt)

**Comment by skt2** [comment]
@pps2010 I have pushed above sitemap.xml to develop2. As of now I put it under common template group and link for that is: http://develop2.akc.org/common/sitemap
There is also http://develop2.akc.org/sitemap.xml in root folder which generated by EE add-ons(I guess), just in case if we want to compare anything there.

**Comment by elieo** [comment]
@kylejbertelsen  what is the hold up on this?

**Comment by pps2010** [comment]
we have decided that there is already a sitemap available http://www.akc.org/sitemap.xml - this lists all pages built via ExpressionEngine - and should be used as-is….

if we need to remove some of the sections from the sitemap (e.g. /news) then that will be a change made by Kyle’s team to make that happen…..

**Comment by spaulenoff** [comment]
@elieo Please see Purvi's comment above

**Comment by elieo** [comment]
@pps2010  that is exactly what I was looking for. Thanks

**Comment by elieo** [comment]
@kylejbertelsen  we need to remove the old media pages. For example: http://www.akc.org/media/article/7-fun-things-to-do-with-your-dog-in-los-angeles/

**Comment by skt2** [comment]
@spaulenoff  You can test it here: http://develop2.akc.org/sitemap.xml/
Removed all /news, /media and /1 pages
Please confirm with @elieo

**Comment by spaulenoff** [comment]
@pps2010 @elieo can you check this on dev2 and stage

**Comment by skt2** [comment]
Tested here: http://stage-ng.akc.org/sitemap.xml/

**Comment by spaulenoff** [comment]
@elieo Can you please glance over this to make sure it looks correct to you? Please check per Shailesh's note above

**Comment by elieo** [comment]
@skt2  the /content/ pages are missing from the sitemap

**Comment by skt2** [comment]
Okay. I am looking into this.

**Comment by skt2** [comment]
Talked with @kylejbertelsen and revert the changes as we want to generate sitemap using channel entries instead of structure.

**Comment by skt2** [comment]
Time Spent: 5h

How to test: @spaulenoff 
Go to: http://develop2.akc.org/sitemap.xml/
Find for /content/

**Comment by aalattili** [comment]
@spaulenoff 
Verified on Dev2 
![dev2-xml sitemap](https://cloud.githubusercontent.com/assets/12289479/15016592/930ba8e0-121a-11e6-8d4a-318d7644b59b.jpg)

**Comment by elieo** [comment]
Looks good. Thanks

**Comment by spaulenoff** [comment]
@skt2 Please privde a URL to check

**Comment by skt2** [comment]
http://stage-ng.akc.org/sitemap.xml/

**Comment by aalattili** [comment]
@spaulenoff , verified on stage
![stage-xml sitemap](https://cloud.githubusercontent.com/assets/12289479/15017662/20876890-121f-11e6-8dbe-11c723398e62.jpg)

**Comment by aalattili** [comment]
@spaulenoff , verified on prod

**Comment by spaulenoff** [comment]
@elieo Please confirm the sitemap looks good to you on Production
