### ISSUE TITLE
Sitespeed - Make it so there is only one Global fav icon for the site

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#74]
Shailesh Thanki 1/11/16 3:11pm: 
Simon Paulenoff Please test this in all the devices to make sure that favicon looks good on all of them and if you find anything is not right on any of the device make note of that device.

Shailesh Thanki 1/11/16 4:16pm:
Kyle J Bertelsen Toshan Reebye FYI
Reference: https://scotch.io/tutorials/all-favicons-for-all-devices-and-sizes

**Comment by skt2** [comment]
Time Spent: 2h

**Comment by spaulenoff** [comment]
Verified on Prod
