### ISSUE TITLE
Sitespeed: Implement AMP on mobile pages

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#76]
Can we implement what is on this page into our mobile pages: https://www.ampproject.org/

**Comment by spaulenoff** [comment]
Blocked by #136

**Comment by skt2** [comment]
Some of the important HTML Tags are prohibited like script, form, input, option and we already using it in our HTML. see full list here: https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#html-tags
So, let's discuss more on Monday. @spaulenoff @kylejbertelsen

**Comment by kylejbertelsen** [comment]
Pulled from sprint. May not be compatible to our needs.

**Comment by kylejbertelsen** [comment]
Is not compatible with our needs. Closing.

**Comment by stevepessah** [comment]
@kylejbertelsen @spaulenoff can we implement this on the article pages if we can't do the full site?

**Comment by spaulenoff** [comment]
Added to Jira
