### ISSUE TITLE
Mobile Find a match

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#8]
https://akcorg.atlassian.net/browse/AKC2-281

**Comment by spaulenoff** [comment]
- Mobile Find a match
  - replaces sign in with My AKC  [^my akc top right - signed in signed out on find a match.mov] 
  - gives you a random zip code
  -  continue button moves down once zipcode is entered  [^continue button disappears and then reshows lower than it should be.mov]

**Comment by kylejbertelsen** [comment]
@spaulenoff : Still a problem, or invalid?
