### ISSUE TITLE
Media Page: Content of some media appears and placed improperly

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#80]
Steps to reproduce:
1. Navigate to Media Pages URL: (http://stage-ng.akc.org/media/).
2. Observe that content of some Images and Videos is appear and place improperly.

Actual Result:
Media Pages - Content of some Images and Videos is place improperly.

Expected Result:
Content (Text, Icons..) of each media should be placed properly.

Note:
1. This issue is applicable on All devices and Platforms.
2. Please refer to attached snapshots: (Media - Images and Videos.png and iPhon 6 Media - Images and Videos.png).

![media - images and videos](https://cloud.githubusercontent.com/assets/1063028/13410279/e542e4b4-df04-11e5-9e88-1c2bc7ca4a21.png)
![iphon 6 media - images and videos](https://cloud.githubusercontent.com/assets/1063028/13410280/e543af84-df04-11e5-9a58-0664b87363b6.png)

**Comment by kylejbertelsen** [comment]
Willing to bet these are missing thumbnails. Start there.

**Comment by elieo** [comment]
@spaulenoff  needs to clarify this and give the developers clear instructions on what needs to be done here.

**Comment by spaulenoff** [comment]
It is a Thumbnail issue. Added thumbnails to a few that were missing them and they worked.

**Comment by spaulenoff** [comment]
Closing this ticket as it was a thumbnail issue
