### ISSUE TITLE
Article Page - Desktop: 3 issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#81]
- Facebook comment should be greater width (need to clarify with Elie the desired size)
- Need ablity to set global photosets, that could be added to any article. Not just photosets on a per article basis.
- Right rail Email CTA should crawl with you (Questionable. Please give @spaulenoff an estimate on this portion)

**Comment by toshan2014** [comment]
@spaulenoff 
please  clarify 
1) first point - which size?
2) second point regarding photosets. Are we referring to some sort of generic gallery?
3) is the desired eddfect being the CTA would stay fixed upon scrolling?

**Comment by spaulenoff** [comment]
@toshan2014 
1. @elieo please confirm
2. Yes correct
3. Correct

**Comment by toshan2014** [comment]
1. @spaulenoff  Where would that new gallery go? - a mockup would be useful here

**Comment by spaulenoff** [comment]
@toshan2014 https://www.dropbox.com/sh/y8u622vaekwevu1/AABUZnK1mgmTtFPjPm_fCtH2a/Desktop?dl=0&preview=article-page.jpg

![image](https://cloud.githubusercontent.com/assets/13648969/13610056/def2b488-e529-11e5-91db-bacfc66aa290.png)

**Comment by spaulenoff** [comment]
@skt2 Please check to see what happened to the most popular in section

**Comment by skt2** [comment]
@spaulenoff its part of @toshan2014's conflict, it has nothing to do with changes from this ticket.

**Comment by spaulenoff** [comment]
@skt2 Not verified on Dev2 Mobile http://develop2.akc.org/content/westminster-dog-show/articles/author-fb-test-article/
![image](https://cloud.githubusercontent.com/assets/13648969/13793456/58492e86-eacd-11e5-9b4c-aa6a020d08c4.png)

How it should look (http://stage-ng.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-1/)
![image](https://cloud.githubusercontent.com/assets/13648969/13793488/76da0f5a-eacd-11e5-97fa-d9991c320ce1.png)

**Comment by spaulenoff** [comment]
@stevepessah Please only QA the first note. Will create seperate tickets for other notes:
http://develop2.akc.org/content/westminster-dog-show/articles/gail-miller-bisher-takes-communications-reins-from-david-frei/
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-2
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-3

**Comment by spaulenoff** [comment]
Verified on Stage

**Comment by spaulenoff** [comment]
@skt2 Verified on Prod. Please add comment regarding time tracking for this ticket

**Comment by skt2** [comment]
Time Spent: 1
