### ISSUE TITLE
Sub-Category Page - Add filters to subcategory pages

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#82]
- Include featured content on page to replace top hero image
  (Replace hero image with the hero carousel) related to ticket #107 Will remove
- Turn filters on on the category pages

**Comment by kylejbertelsen** [comment]
@spaulenoff : What is this 'featured content'?
Which filters?

**Comment by spaulenoff** [comment]
@kylejbertelsen Featured Content is that top section of the following mockup and /media/ page:
https://www.dropbox.com/sh/y8u622vaekwevu1/AABUZnK1mgmTtFPjPm_fCtH2a/Desktop?dl=0&preview=sub-category-page.jpg
http://stage-ng.akc.org/media/
Relates to #99

**Comment by kylejbertelsen** [comment]
@spaulenoff Still need to know what filters.

**Comment by spaulenoff** [comment]
The filters would be:
- Most Popular
- Alphabetical
- Most Recent

@stevepessah please confirm if I am missing any

**Comment by kylejbertelsen** [comment]
@toshan2014: Please read this ticket, and let me know whether you understand what they want, and give an estimate on how long it would take you, according to your understanding of the ticket.

**Comment by toshan2014** [comment]
@spaulenoff @kylejbertelsen  by "Most popular", do we mean "Most viewed/read"?

Also can I be provided with an example of "featured content". I want to see how they are being distinguished from usual content.

**Comment by spaulenoff** [comment]
@elieo @stevepessah Can you please confirm filters you would like to use on subcategory pages?

Currently what I am thinking is:
- Most Viewed
- Most Recent
- Alphabetical
- Most Comments and/or Social Shares

**Comment by toshan2014** [comment]
just FYI, most "Most Comments and/or Social Shares" is not one of EE's built-in filters (unless we use EE's commenting module rather than Facebook's ). We'll have to discuss with Kyle for other ways to implement this if that's chosen.
@spaulenoff @kylejbertelsen

**Comment by kylejbertelsen** [comment]
@spaulenoff: can we get a meeting w/ stakeholders about this? I'd like to get the wishlist here gelled into something more well-defined. I'm sure we can deliver whatever they want, but let's get that settled once-and-for-all.

**Comment by elieo** [comment]
This is low priority. Please hold for now.

**Comment by spaulenoff** [comment]
Moved to Jira
