### ISSUE TITLE
Photo Gallery Page - Mobile: 3 issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#83]
- Remove Arrow on Begin Slide show slide
- Gallery images should be same size
- End card missing "Next" button

**Comment by kylejbertelsen** [comment]
@spaulenoff -- please discuss point 4 above with Elie and/or Steve -- 'previous' and 'next' button is not possible within Expression Engine, the way that the templates are currently assembled.

Options: 
a) an additional 8 hours of development to reorganize those templates;
b) adding a field to the Media type, where editors would expressly select a previous Media and a Next Media -- add 2 hours to estimate;
c) come up with something else to fill this space, estimate to be determined with whatever is chosen for this space;
d) leave it as-is;

**Comment by spaulenoff** [comment]
Per mockup, we do not want social buttons on individual slides
![image](https://cloud.githubusercontent.com/assets/13648969/13613156/f4f71968-e538-11e5-9e77-07550b9bc9c5.png)

**Comment by spaulenoff** [comment]
@kylejbertelsen @skt2 Spoke with Steve and Elie and they want to go with the following option for view next gallery button:

adding a field to the Media type, where editors would expressly select a Next Media -- add 2 hours to estimate. A button will only show up when a link is selected in the CMS

**Comment by skt2** [comment]
Added Next Gallery Link. Example: http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=5

**Comment by spaulenoff** [comment]
Please QA on Mobile Dev2 http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/

Please note, the view next gallery button will only show if a link is added in the CMS

**Comment by stevepessah** [comment]
@spaulenoff I used @skt2's [link](http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=5) which has a Next Gallery so I tested and the functionality works, but the design needs fixing.

https://www.dropbox.com/sh/y8u622vaekwevu1/AACGPzVpI6K-cEmZneW9bmZTa/Mobile?dl=0&preview=AKC_Mobile_UX_Photo-070215-end.jpg

**Comment by spaulenoff** [comment]
@skt2 Please fix design on next gallery button on the end card to match Mockup
![image](https://cloud.githubusercontent.com/assets/13648969/13640580/357d0e7a-e5e3-11e5-9295-4b484e7edbcd.png)

Can we also add a field to the cms under the next media content link that you can add a title as well.

Please also add a description and example of what needs to be added to each field. Please also put a note saying that button will not appear if no link is added.

**Comment by spaulenoff** [comment]
@skt2 Looks good to me design wise, however when i click the next gallery link (http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=5), i get directed to this page that doesn't exist http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/%7bnext_media_item_link%7d/

Also i am seeing a difference on the opening slide on the following galleries:

Correct:
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=0
![image](https://cloud.githubusercontent.com/assets/13648969/13645428/fd3a8a5e-e5f8-11e5-9d87-1eb783b71186.png)

Incorrect:
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0
![image](https://cloud.githubusercontent.com/assets/13648969/13645455/169503b2-e5f9-11e5-8b08-6f7792dbf100.png)

The Begin Slideshow box is not located in the same part of the slide

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev 2 Please QA on Mobile Dev2 http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=5
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=6

**Comment by stevepessah** [comment]
Verified on mobile on dev2.

**Comment by skt2** [comment]
*_CMS Changes: *_
Admin > Channel Admin > Channel Fields
Media > Add New Field
Field Type: Grid
Field Label: Next Media Item
Field Name: next_media_item

Field 1: Text Input
Label: Title
Name: title
Instructions: Title for next media link. Recommended length 55 characters.

Field 2: Text Input
Label: Link
Name: link
Instructions: Link for next media page. Do not include domain name. Example: /content/westminster-dog-show/photo-galleries/westminster-gallery

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage http://stage-ng.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0 (Mobile)

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by spaulenoff** [comment]
@skt2 Verified on prod. Please add comment regarding time tracking.

**Comment by skt2** [comment]
Time Spent: 4
