### ISSUE TITLE
Global - Desktop: 2 issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#84]
- Selected navigation tab needs to include orange underline

https://www.dropbox.com/sh/y8u622vaekwevu1/AABUZnK1mgmTtFPjPm_fCtH2a/Desktop?dl=0&preview=category+page.jpg
- Most Popular section needs to include all media type

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev2
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video/
http://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/

Please only QA per the second note as the first note was resolved in https://github.com/akcdotorg/akc.org/issues/105

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage:
http://stage-ng.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-1/
http://stage-ng.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/
http://stage-ng.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0

Please only QA the second note, as the first note will be resolved when #105 gets pushed to stage

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by spaulenoff** [comment]
@skt2  Verified on Prod. Please add ticket with time tracking for this ticket

**Comment by skt2** [comment]
Time Spent: 6
