### ISSUE TITLE
Category Page - Mobile: Entire page rework

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#85]
Entire page layout needs updating. Should be single tile with ability to swipe.

https://www.dropbox.com/sh/y8u622vaekwevu1/AACGPzVpI6K-cEmZneW9bmZTa/Mobile?dl=0&preview=AKC_Mobile_UX_Hub-070215.jpg

Please review above mockup. See below for a few specific issues:
- Missing category indication on hero image (that should be the H1 tag)
- Missing subheader (H2) for each section in body
- Missing category title next to thumbnails
- Thumbnail and description ratio needs fixing

**Comment by kylejbertelsen** [comment]
@spaulenoff: Please define how this differs from what currently is.

**Comment by spaulenoff** [comment]
@kylejbertelsen Currently it just lists out the top pieces of content similar to how it is on desktop

Needs to match mockup here: https://www.dropbox.com/sh/y8u622vaekwevu1/AACGPzVpI6K-cEmZneW9bmZTa/Mobile?dl=0&preview=AKC_Mobile_UX_Hub-070215.jpg

**Comment by spaulenoff** [comment]
@stevepessah Please QA on http://develop2.akc.org/content/westminster-dog-show/ (mobile)

**Comment by stevepessah** [comment]
Above issues verified on dev. Below issues still need work:
- Remove padding above hero image
- Fix hero image size
- Top navigation is missing (will be added as part of https://github.com/akcdotorg/akc.org/issues/52)
- Circles are not centered
- Add media-type squares back on thumbnails
- Pop out nav shows BREEDS row enlarged

**Comment by spaulenoff** [comment]
@stevepessah Looks good to me. Please QA on Dev2 http://develop2.akc.org/content/westminster-dog-show/

**Comment by stevepessah** [comment]
Everything looks good except for the left nav, but we can address that in a different ticket. @spaulenoff can you make one for the left nav or add it to #52?

Only thing I see now is the caption sizes aren't the same, so we need to decide how to standardize.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage http://stage-ng.akc.org/content/westminster-dog-show/ (mobile) Looks good to me

**Comment by spaulenoff** [comment]
@skt2 Please add a field in the CMS for adding a mobile Hero image for category pages. Recommended size 375px X 280px

**Comment by skt2** [comment]
@spaulenoff Please make sure to upload the mobile hero image before you test it.
Also, this changes do not have mobile hero image for sub-category pages. I'll push those changes to AKC3-99 branch.

**Comment by skt2** [comment]
**CMS Changes**
Admin > Channel Admin > Channel Fields > Category Page
Add new field:
Field Type: Assets
Label: Category Mobile Hero
Name: category_mobile_hero
Instruction: Small image for mobile. Recommended Image Size 375px X 280px
Field Option: All
View Options: List, Columns: Check All
Multiple Selection: No

**Comment by spaulenoff** [comment]
@skt2  Verified on Prod. Please add ticket with time tracking for this ticket

**Comment by skt2** [comment]
Time Spent: 12
