### ISSUE TITLE
Category Page - Desktop: 2 issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#86]
https://www.dropbox.com/sh/y8u622vaekwevu1/AABUZnK1mgmTtFPjPm_fCtH2a/Desktop?dl=0&preview=category+page.jpg
- Missing category indication on hero image (that should be the H1 tag)
- Missing subheader (H2) for each section in body

**Comment by spaulenoff** [comment]
@stevepessah Please QA on http://develop2.akc.org/content/westminster-dog-show/ (Desktop)

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage http://stage-ng.akc.org/content/westminster-dog-show/ (desktop) Looks good to me

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by spaulenoff** [comment]
@skt2 Verified on Prod. Please add ticket with time tracking for this ticket

**Comment by skt2** [comment]
Time Spent: 3
