### ISSUE TITLE
Sub-Category Page - Mobile: 1 issue

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#87]
https://www.dropbox.com/sh/y8u622vaekwevu1/AACGPzVpI6K-cEmZneW9bmZTa/Mobile?dl=0&preview=AKC_Mobile_UX_Media-070215.jpg
- Thumbnail and description ratio needs fixing

**Comment by toshan2014** [comment]
@spaulenoff - that page on the mockup seems to be the old /media page - now in /content it looks like this : http://develop2.akc.org/content/westminster-dog-show/

please confirm if this is correct and if there's still an issue here.

**Comment by spaulenoff** [comment]
@toshan2014 The Subctegory pages should look similar to the content type pages on mobile http://develop2.akc.org/content/westminster-dog-show/videos/

**Comment by toshan2014** [comment]
@spaulenoff  Looking similar now to http://develop2.akc.org/content/westminster-dog-show/videos/
Please confirm

**Comment by spaulenoff** [comment]
@toshan2014 close! Couple of things i noticed,
Can you add the content type symbols to each type of content? like in the mock?
![image](https://cloud.githubusercontent.com/assets/13648969/13671751/c07e8da2-e69f-11e5-957c-623056b6a2ff.png)

Also it looks like your changes were pushed on the category pages as well. Please check with @skt2 
http://develop2.akc.org/content/westminster-dog-show/

**Comment by toshan2014** [comment]
@spaulenoff : Media type symbols added with category like in the mockup. I do think having the category is redundant. Let me know if you want it removed

https://develop2.akc.org/content/westminster-dog-show/live-coverage/

**Comment by spaulenoff** [comment]
@stevepessah @elieo Please QA https://develop2.akc.org/content/westminster-dog-show/live-coverage/

I do agree with Toshan that the Category being show for each piece of content is a bit redundant. Let's discuss if we should remove it.

**Comment by stevepessah** [comment]
Issues with Title
- Remove all caps
- Fix font color
- Double check on Filter
- Ensure that the View More button works
- See if we can remove title from each thumbnail and place in top orange part instead (since main category will always be the same under sub-category pages)

**Comment by spaulenoff** [comment]
@toshan2014 Talked with Elie, please remove the category title for each piece of content. Since we have no filter currently, we will skip this for now. Please look at Steve's other comments as well

**Comment by toshan2014** [comment]
Please clarify @spaulenoff 
#1 Remove all caps - from where exactly? If we are referring to the category heading in orange for each tile, that heading will be removed completely.

#2 Fix font color - are we referring to the purple text? Because that mockup was before the UX changes. Now we are not using that purple of texts in general texts anymore. The new color is #333 which is used across board ( example: https://develop2.akc.org/news/dog-finds-lost-toddler-in-woods/ )

**Comment by toshan2014** [comment]
#3 Filter and Sort functionalities are disabled overall.

#4 View More - Working fine ( same way as desktop )

#5 Title removed from each tile - Top orange part ( I believe we are referring to Hero section ? ) showing Subcat title

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev2 on mobile http://develop2.akc.org/content/westminster-dog-show/live-coverage/

Please note the category titles were removed from the content tiles per Elie's instructions

**Comment by toshan2014** [comment]
@spaulenoff  please check on stage

http://stage-ng.akc.org/content/westminster-dog-show/live-coverage/

**Comment by toshan2014** [comment]
pf:

http://develop2.akc.org/content/westminster-dog-show/live-coverage

**Comment by spaulenoff** [comment]
@toshan2014 Verified on Prod. Please add ticket with time tracking for this ticket

**Comment by toshan2014** [comment]
Spent: around 2h
