### ISSUE TITLE
Article Page - Mobile: 2 issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#88]
https://www.dropbox.com/sh/y8u622vaekwevu1/AACGPzVpI6K-cEmZneW9bmZTa/Mobile?dl=0&preview=AKC_Mobile_UX_Article-070215.jpg
- Remove padding between hero image and top navigation horizontal line
- Hero size needs to match mockup

**Comment by spaulenoff** [comment]
@stevepessah Please Qa on Dev2 on Mobile http://develop2.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-2/
http://develop2.akc.org/content/westminster-dog-show/articles/gail-miller-bisher-takes-communications-reins-from-david-frei/

These changes look good to me on dev2

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage http://stage-ng.akc.org/content/westminster-dog-show/articles/westminster-group-results-day-1/ (Mobile)

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by spaulenoff** [comment]
@skt2 Verified on Prod. Please add comment regarding time tracking for this ticket

**Comment by skt2** [comment]
Time Spent: 2
