### ISSUE TITLE
Video Page - Desktop: 3 issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#89]
https://www.dropbox.com/sh/y8u622vaekwevu1/AABUZnK1mgmTtFPjPm_fCtH2a/Desktop?dl=0&preview=video-page.jpg
- Missing video runtime next to Title
- When scrolling the page, lightbox should stay static and not cover the video
- Missing "Next Video" button after video ends

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev 2 http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video/

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by spaulenoff** [comment]
@skt2 Per our conversation, please move the run time of the video up next the title on Desktop, but leave the runtime where it is on mobile per #90

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage http://stage-ng.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/ (Desktop)

Please note i manually entered the length in the CMS so anytime can be entered there

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by spaulenoff** [comment]
@skt2 Verified on prod. please add comment regarding time tracking

**Comment by skt2** [comment]
Time Spent: 5

**Comment by skt2** [comment]
@spaulenoff The reason we did video overlay changes because video was covered by overlay when someone scroll the page.
