### ISSUE TITLE
Redesign Find a Match - Mobile

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#9]
- Heavy emphasis on mobile
- Remove "find a MATCH" header at the top
- step 4 options below image are too close together
- steps load at different heights
- step 6 doesn't show all image
- on landscape the image is not centered

![img_3862 1](https://cloud.githubusercontent.com/assets/1063028/13357537/d5e97ca0-dc78-11e5-935d-fdccf9053491.png)

**Comment by kylejbertelsen** [comment]
@spaulenoff: still valid? Maybe a project to rebuild this, mobile-first?

**Comment by spaulenoff** [comment]
Still Valid. But yes we need to rebuild the mobile version of this
