### ISSUE TITLE
Video Page - Mobile: 3 issues, Mobile Tweaks

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#90]
https://www.dropbox.com/sh/y8u622vaekwevu1/AACGPzVpI6K-cEmZneW9bmZTa/Mobile?dl=0&preview=AKC_Mobile_UX_Video-062915.jpg
- Remove padding between hero image and top navigation horizontal line
- Page title, date, and author need to move above video
- Include runtime next to title

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Dev2:
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-3
http://develop2.akc.org/content/westminster-dog-show/videos/westminster-test-video-2
- Remove padding between hero image and top navigation horizontal line (looks fixed)
- Page title, date, and author need to move above video (looks fixed)
- Include runtime next to title (Will check back after https://github.com/akcdotorg/akc.org/issues/89 is implemented)

**Comment by stevepessah** [comment]
Those two issued are verified on mobile on dev2.

**Comment by skt2** [comment]
**CMS Changes:**
Admin > Channel Admin > Channel Fields
Media > Add New Field
Field Type: Grid
Field Label: Video
Field Name: video

Field 1: Text Input
Label: Link
Name: link
Instructions: Link to xml video on on jwplatform. For example: http://content.jwplatform.com/jw6/Uj7QLOaM.xml

Field 2: Text Input
Label: Runtime
Name: runtime
Instructions: Video Play Time

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage http://stage-ng.akc.org/content/westminster-dog-show/videos/westminster-test-video-3/ (mobile)

Please note I manually entered the time in the CMS so it can show anytime entered

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by spaulenoff** [comment]
@skt2 Verified on prod. please add comment regarding time tracking

**Comment by skt2** [comment]
Time Spent: 3
