### ISSUE TITLE
Photo Gallery Page - Desktop: 7 issues

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#92]
https://www.dropbox.com/sh/y8u622vaekwevu1/AABUZnK1mgmTtFPjPm_fCtH2a/Desktop?dl=0&preview=gallery-page-1.jpg
- Text is getting cut off
- Body text is moving too far to the right. Should not interfere with social buttons.
- Date published is being removed from all slides except the first
- On second slide and so on, title tag should reflect the name of the page's H1 tag.
- Meta description should be consistent across all slides and should be pulled from the CMS.
- Title tag for interstitial and end card should default to the title tag of the first slide.
- Missing the "View Next Gallery" button

**Comment by skt2** [comment]
Date published is being removed from all slides except the first - This need to be added in CMS in order to show front side.

![date-in-cms](https://cloud.githubusercontent.com/assets/16002526/13639895/ca634098-e5e0-11e5-97a9-2ca2eaf5031e.png)

On second slide and so on, title tag should reflect the name of the page's H1 tag. -- This need to be added in CMS in order to show front side.

**Comment by spaulenoff** [comment]
@stevepessah Please Qa on Dev2 http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=0
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0

**Comment by stevepessah** [comment]
- Text is getting cut off

**Verified on dev2.**
- Body text is moving too far to the right. Should not interfere with social buttons.

**Verified on dev2.**
- Date published is being removed from all slides except the first

**Verified on dev2.**
- On second slide and so on, title tag should reflect the name of the page's H1 tag.

**Not verified on dev2.**
**Working with http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery-3/?photo_id=0 but not http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=3**
- Meta description should be consistent across all slides and should be pulled from the CMS.

**Not verified on dev2.**
- Title tag for interstitial and end card should default to the title tag of the first slide.

**Verified on dev2.**
- Missing the "View Next Gallery" button

**Verified on dev2.**

**Comment by spaulenoff** [comment]
@skt2 
- Meta description should be consistent across all slides and should be pulled from the CMS.
  Not verified on dev2.

I am not seeing the Meta Description on any indivdual slide:
http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=3

Seeing meta description on first page though: http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0

Please look into this

**Comment by spaulenoff** [comment]
@stevepessah Please QA for meta description on the following gallery, seeing it correctly on all slides on my end http://develop2.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0

**Comment by stevepessah** [comment]
Verified on dev2.

**Comment by spaulenoff** [comment]
@stevepessah Please QA on Stage http://stage-ng.akc.org/content/westminster-dog-show/photo-galleries/westminster-test-gallery/?photo_id=0

**Comment by stevepessah** [comment]
Verified on stage.

**Comment by spaulenoff** [comment]
@skt2 http:Verified on Prod. Please add comment regarding time tracking

**Comment by skt2** [comment]
Time Spent: 2
