### ISSUE TITLE
Category/Subcategory Page - Left Side bar Format/Structure

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#98]
- Need to add Category/SubCategory Menu to Category and Sub Category Pages
- Needs to contain all categories with the subcategories for that specific category you are in open at all times
- These need to be added above the current editable sublinks menu (Admin>Channel Admin>Categories>Sublinks,Category Sidbar Text

**Comment by kylejbertelsen** [comment]
Plain text example. Assume you're on 'Category A' page  (or Category A Subcats):

Category A
  Subcat A 1
  Subcat A 2
Category B
Category Z
space
Category A Sublinks

Or if you're on Category B (or Category B Subcats):
Category A
Category B
  Subcat B 1
  Subcat B 2
Category Z
space
Category B Sublinks

**Comment by spaulenoff** [comment]
Per @elieo There needs to be a way for users to go from sub category of one category to te subcategory of a completely different category

Ex... Subcat A 1 to Subcat B 2

**Comment by spaulenoff** [comment]
@elieo @kylejbertelsen  is asking for a mock up of what you want the left Sidebar to look like and function

**Comment by toshan2014** [comment]
I've done it as below. The subcategories show in a sliding fashion upon clicking on the parent category - I believe this is what you're after:

<img width="541" alt="slider-cat" src="https://cloud.githubusercontent.com/assets/6847220/13598621/b73168e6-e4d3-11e5-8e6d-d2a83fcc34df.PNG">

**Comment by spaulenoff** [comment]
@toshan2014 That style/format for the sidebar menu is correct as long as you can expand each category to get to the sub categories. And then also be able to minimize each category if you want

**Comment by spaulenoff** [comment]
@elieo @stevepessah Please QA on Dev2 https://develop2.akc.org/content/westminster-dog-show/ and we can discuss with @kylejbertelsen on how we want to proceed with this

**Comment by spaulenoff** [comment]
Working correctly on Category Pages http://develop2.akc.org/content/westminster-dog-show/
Not Working correctly on SubCat Pages http://develop2.akc.org/content/westminster-dog-show/live-coverage/

**Comment by spaulenoff** [comment]
@kylejbertelsen Still not working on subcategory pages http://develop2.akc.org/content/westminster-dog-show/live-coverage/

**Comment by kylejbertelsen** [comment]
The `embeds/.media-list-subcat` template was not updated to use the correct subnavigation file. I have instructed @toshan2014 to fix this, but for the moment, I have fixed it in the Template Manager in the CMS.

**Comment by spaulenoff** [comment]
@stevepessah and @elieo Please QA on Dev2: Elie confirmed the style of the sidebar for now. (Desktop)

Category: http://develop2.akc.org/content/westminster-dog-show/
SubCategory: http://develop2.akc.org/content/westminster-dog-show/live-coverage/

**Comment by spaulenoff** [comment]
@kylejbertelsen Verified on Prod. Please add ticket with time tracking for this ticket

**Comment by kylejbertelsen** [comment]
Approx. time spent: 24 hours
